// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_s2c.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//发送给客户端所有消息协议封包，buff是具体的结构体内容，需要端对照相应的协议解析
type S2CMsg struct {
	MainCmd              int32    `protobuf:"varint,1,opt,name=mainCmd,proto3" json:"mainCmd"`
	SubCmd               int32    `protobuf:"varint,2,opt,name=subCmd,proto3" json:"subCmd"`
	Buff                 []byte   `protobuf:"bytes,3,opt,name=buff,proto3" json:"buff"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CMsg) Reset()         { *m = S2CMsg{} }
func (m *S2CMsg) String() string { return proto.CompactTextString(m) }
func (*S2CMsg) ProtoMessage()    {}
func (*S2CMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{0}
}

func (m *S2CMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMsg.Unmarshal(m, b)
}
func (m *S2CMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMsg.Marshal(b, m, deterministic)
}
func (m *S2CMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMsg.Merge(m, src)
}
func (m *S2CMsg) XXX_Size() int {
	return xxx_messageInfo_S2CMsg.Size(m)
}
func (m *S2CMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMsg proto.InternalMessageInfo

func (m *S2CMsg) GetMainCmd() int32 {
	if m != nil {
		return m.MainCmd
	}
	return 0
}

func (m *S2CMsg) GetSubCmd() int32 {
	if m != nil {
		return m.SubCmd
	}
	return 0
}

func (m *S2CMsg) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

//房间基本信息，大厅显示
type S2CRoomBaseInfo struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	LimitAmount          int64             `protobuf:"varint,3,opt,name=limitAmount,proto3" json:"limitAmount"`
	MaxRed               int64             `protobuf:"varint,4,opt,name=maxRed,proto3" json:"maxRed"`
	RedArr               []*S2CRedInfo     `protobuf:"bytes,5,rep,name=redArr,proto3" json:"redArr"`
	UserArr              []*S2CUserInfo    `protobuf:"bytes,6,rep,name=userArr,proto3" json:"userArr"`
	UserCount            int64             `protobuf:"varint,7,opt,name=userCount,proto3" json:"userCount"`
	SelfInfo             *S2CUserInfo      `protobuf:"bytes,8,opt,name=selfInfo,proto3" json:"selfInfo"`
	RedConfig            *S2CRedConfigInfo `protobuf:"bytes,9,opt,name=redConfig,proto3" json:"redConfig"`
	WaitSendCount        int32             `protobuf:"varint,10,opt,name=waitSendCount,proto3" json:"waitSendCount"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *S2CRoomBaseInfo) Reset()         { *m = S2CRoomBaseInfo{} }
func (m *S2CRoomBaseInfo) String() string { return proto.CompactTextString(m) }
func (*S2CRoomBaseInfo) ProtoMessage()    {}
func (*S2CRoomBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{1}
}

func (m *S2CRoomBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRoomBaseInfo.Unmarshal(m, b)
}
func (m *S2CRoomBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRoomBaseInfo.Marshal(b, m, deterministic)
}
func (m *S2CRoomBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRoomBaseInfo.Merge(m, src)
}
func (m *S2CRoomBaseInfo) XXX_Size() int {
	return xxx_messageInfo_S2CRoomBaseInfo.Size(m)
}
func (m *S2CRoomBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRoomBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRoomBaseInfo proto.InternalMessageInfo

func (m *S2CRoomBaseInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2CRoomBaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2CRoomBaseInfo) GetLimitAmount() int64 {
	if m != nil {
		return m.LimitAmount
	}
	return 0
}

func (m *S2CRoomBaseInfo) GetMaxRed() int64 {
	if m != nil {
		return m.MaxRed
	}
	return 0
}

func (m *S2CRoomBaseInfo) GetRedArr() []*S2CRedInfo {
	if m != nil {
		return m.RedArr
	}
	return nil
}

func (m *S2CRoomBaseInfo) GetUserArr() []*S2CUserInfo {
	if m != nil {
		return m.UserArr
	}
	return nil
}

func (m *S2CRoomBaseInfo) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *S2CRoomBaseInfo) GetSelfInfo() *S2CUserInfo {
	if m != nil {
		return m.SelfInfo
	}
	return nil
}

func (m *S2CRoomBaseInfo) GetRedConfig() *S2CRedConfigInfo {
	if m != nil {
		return m.RedConfig
	}
	return nil
}

func (m *S2CRoomBaseInfo) GetWaitSendCount() int32 {
	if m != nil {
		return m.WaitSendCount
	}
	return 0
}

//红包配置（点击发送红包之后红包的页面数据）
type S2CRedConfigInfo struct {
	Odds                 int32    `protobuf:"varint,1,opt,name=odds,proto3" json:"odds"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	Amount               []int64  `protobuf:"varint,3,rep,packed,name=amount,proto3" json:"amount"`
	SpaceAmount          int64    `protobuf:"varint,4,opt,name=spaceAmount,proto3" json:"spaceAmount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedConfigInfo) Reset()         { *m = S2CRedConfigInfo{} }
func (m *S2CRedConfigInfo) String() string { return proto.CompactTextString(m) }
func (*S2CRedConfigInfo) ProtoMessage()    {}
func (*S2CRedConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{2}
}

func (m *S2CRedConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedConfigInfo.Unmarshal(m, b)
}
func (m *S2CRedConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedConfigInfo.Marshal(b, m, deterministic)
}
func (m *S2CRedConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedConfigInfo.Merge(m, src)
}
func (m *S2CRedConfigInfo) XXX_Size() int {
	return xxx_messageInfo_S2CRedConfigInfo.Size(m)
}
func (m *S2CRedConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedConfigInfo proto.InternalMessageInfo

func (m *S2CRedConfigInfo) GetOdds() int32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func (m *S2CRedConfigInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *S2CRedConfigInfo) GetAmount() []int64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *S2CRedConfigInfo) GetSpaceAmount() int64 {
	if m != nil {
		return m.SpaceAmount
	}
	return 0
}

//用户信息数组
type S2CUserInfoArr struct {
	Current              int32          `protobuf:"varint,1,opt,name=current,proto3" json:"current"`
	Size                 int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Total                int64          `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	Pages                int32          `protobuf:"varint,4,opt,name=pages,proto3" json:"pages"`
	UserArr              []*S2CUserInfo `protobuf:"bytes,5,rep,name=userArr,proto3" json:"userArr"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CUserInfoArr) Reset()         { *m = S2CUserInfoArr{} }
func (m *S2CUserInfoArr) String() string { return proto.CompactTextString(m) }
func (*S2CUserInfoArr) ProtoMessage()    {}
func (*S2CUserInfoArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{3}
}

func (m *S2CUserInfoArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUserInfoArr.Unmarshal(m, b)
}
func (m *S2CUserInfoArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUserInfoArr.Marshal(b, m, deterministic)
}
func (m *S2CUserInfoArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUserInfoArr.Merge(m, src)
}
func (m *S2CUserInfoArr) XXX_Size() int {
	return xxx_messageInfo_S2CUserInfoArr.Size(m)
}
func (m *S2CUserInfoArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUserInfoArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUserInfoArr proto.InternalMessageInfo

func (m *S2CUserInfoArr) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *S2CUserInfoArr) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *S2CUserInfoArr) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *S2CUserInfoArr) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *S2CUserInfoArr) GetUserArr() []*S2CUserInfo {
	if m != nil {
		return m.UserArr
	}
	return nil
}

//用户基本信息
type S2CUserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Head                 string   `protobuf:"bytes,3,opt,name=head,proto3" json:"head"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount"`
	ChairId              int32    `protobuf:"varint,5,opt,name=chairId,proto3" json:"chairId"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status"`
	RobbedAmount         int64    `protobuf:"varint,7,opt,name=robbedAmount,proto3" json:"robbedAmount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CUserInfo) Reset()         { *m = S2CUserInfo{} }
func (m *S2CUserInfo) String() string { return proto.CompactTextString(m) }
func (*S2CUserInfo) ProtoMessage()    {}
func (*S2CUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{4}
}

func (m *S2CUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUserInfo.Unmarshal(m, b)
}
func (m *S2CUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUserInfo.Marshal(b, m, deterministic)
}
func (m *S2CUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUserInfo.Merge(m, src)
}
func (m *S2CUserInfo) XXX_Size() int {
	return xxx_messageInfo_S2CUserInfo.Size(m)
}
func (m *S2CUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUserInfo proto.InternalMessageInfo

func (m *S2CUserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *S2CUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2CUserInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *S2CUserInfo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *S2CUserInfo) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CUserInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *S2CUserInfo) GetRobbedAmount() int64 {
	if m != nil {
		return m.RobbedAmount
	}
	return 0
}

//红包基本信息
type S2CRedInfo struct {
	RedId                int64    `protobuf:"varint,1,opt,name=redId,proto3" json:"redId"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	MineNum              int64    `protobuf:"varint,5,opt,name=mineNum,proto3" json:"mineNum"`
	Route                int32    `protobuf:"varint,6,opt,name=route,proto3" json:"route"`
	RobbedCount          int64    `protobuf:"varint,7,opt,name=robbedCount,proto3" json:"robbedCount"`
	SenderId             int64    `protobuf:"varint,8,opt,name=senderId,proto3" json:"senderId"`
	IsAi                 bool     `protobuf:"varint,9,opt,name=isAi,proto3" json:"isAi"`
	Time                 int64    `protobuf:"varint,10,opt,name=time,proto3" json:"time"`
	Level                int32    `protobuf:"varint,11,opt,name=level,proto3" json:"level"`
	Speed                []int32  `protobuf:"varint,12,rep,packed,name=speed,proto3" json:"speed"`
	SenderName           string   `protobuf:"bytes,13,opt,name=senderName,proto3" json:"senderName"`
	RedFlood             int64    `protobuf:"varint,14,opt,name=redFlood,proto3" json:"redFlood"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedInfo) Reset()         { *m = S2CRedInfo{} }
func (m *S2CRedInfo) String() string { return proto.CompactTextString(m) }
func (*S2CRedInfo) ProtoMessage()    {}
func (*S2CRedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{5}
}

func (m *S2CRedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedInfo.Unmarshal(m, b)
}
func (m *S2CRedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedInfo.Marshal(b, m, deterministic)
}
func (m *S2CRedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedInfo.Merge(m, src)
}
func (m *S2CRedInfo) XXX_Size() int {
	return xxx_messageInfo_S2CRedInfo.Size(m)
}
func (m *S2CRedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedInfo proto.InternalMessageInfo

func (m *S2CRedInfo) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

func (m *S2CRedInfo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *S2CRedInfo) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *S2CRedInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *S2CRedInfo) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

func (m *S2CRedInfo) GetRoute() int32 {
	if m != nil {
		return m.Route
	}
	return 0
}

func (m *S2CRedInfo) GetRobbedCount() int64 {
	if m != nil {
		return m.RobbedCount
	}
	return 0
}

func (m *S2CRedInfo) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *S2CRedInfo) GetIsAi() bool {
	if m != nil {
		return m.IsAi
	}
	return false
}

func (m *S2CRedInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *S2CRedInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *S2CRedInfo) GetSpeed() []int32 {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *S2CRedInfo) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *S2CRedInfo) GetRedFlood() int64 {
	if m != nil {
		return m.RedFlood
	}
	return 0
}

//抢红包的信息
type S2CRobRed struct {
	RedId                int64    `protobuf:"varint,1,opt,name=redId,proto3" json:"redId"`
	IsMine               bool     `protobuf:"varint,2,opt,name=isMine,proto3" json:"isMine"`
	RobbedAmount         int64    `protobuf:"varint,3,opt,name=robbedAmount,proto3" json:"robbedAmount"`
	NotRobbedCount       int64    `protobuf:"varint,4,opt,name=notRobbedCount,proto3" json:"notRobbedCount"`
	Amount               int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount"`
	SenderName           string   `protobuf:"bytes,6,opt,name=senderName,proto3" json:"senderName"`
	MineNum              int64    `protobuf:"varint,7,opt,name=mineNum,proto3" json:"mineNum"`
	Level                int32    `protobuf:"varint,8,opt,name=level,proto3" json:"level"`
	Score                int64    `protobuf:"varint,9,opt,name=score,proto3" json:"score"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRobRed) Reset()         { *m = S2CRobRed{} }
func (m *S2CRobRed) String() string { return proto.CompactTextString(m) }
func (*S2CRobRed) ProtoMessage()    {}
func (*S2CRobRed) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{6}
}

func (m *S2CRobRed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRobRed.Unmarshal(m, b)
}
func (m *S2CRobRed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRobRed.Marshal(b, m, deterministic)
}
func (m *S2CRobRed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRobRed.Merge(m, src)
}
func (m *S2CRobRed) XXX_Size() int {
	return xxx_messageInfo_S2CRobRed.Size(m)
}
func (m *S2CRobRed) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRobRed.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRobRed proto.InternalMessageInfo

func (m *S2CRobRed) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

func (m *S2CRobRed) GetIsMine() bool {
	if m != nil {
		return m.IsMine
	}
	return false
}

func (m *S2CRobRed) GetRobbedAmount() int64 {
	if m != nil {
		return m.RobbedAmount
	}
	return 0
}

func (m *S2CRobRed) GetNotRobbedCount() int64 {
	if m != nil {
		return m.NotRobbedCount
	}
	return 0
}

func (m *S2CRobRed) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *S2CRobRed) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *S2CRobRed) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

func (m *S2CRobRed) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *S2CRobRed) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

//红包列表
type S2CRedArr struct {
	RedArr               []*S2CRedInfo `protobuf:"bytes,1,rep,name=redArr,proto3" json:"redArr"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2CRedArr) Reset()         { *m = S2CRedArr{} }
func (m *S2CRedArr) String() string { return proto.CompactTextString(m) }
func (*S2CRedArr) ProtoMessage()    {}
func (*S2CRedArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{7}
}

func (m *S2CRedArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedArr.Unmarshal(m, b)
}
func (m *S2CRedArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedArr.Marshal(b, m, deterministic)
}
func (m *S2CRedArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedArr.Merge(m, src)
}
func (m *S2CRedArr) XXX_Size() int {
	return xxx_messageInfo_S2CRedArr.Size(m)
}
func (m *S2CRedArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedArr proto.InternalMessageInfo

func (m *S2CRedArr) GetRedArr() []*S2CRedInfo {
	if m != nil {
		return m.RedArr
	}
	return nil
}

//狩猎记录-发送记录
type S2CSendRedRecordArr struct {
	TotalAmount          int64               `protobuf:"varint,1,opt,name=totalAmount,proto3" json:"totalAmount"`
	TotalCount           int64               `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount"`
	RedArr               []*S2CSendRedRecord `protobuf:"bytes,3,rep,name=redArr,proto3" json:"redArr"`
	Current              int32               `protobuf:"varint,4,opt,name=current,proto3" json:"current"`
	Size                 int32               `protobuf:"varint,5,opt,name=size,proto3" json:"size"`
	Total                int64               `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
	Pages                int32               `protobuf:"varint,7,opt,name=pages,proto3" json:"pages"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *S2CSendRedRecordArr) Reset()         { *m = S2CSendRedRecordArr{} }
func (m *S2CSendRedRecordArr) String() string { return proto.CompactTextString(m) }
func (*S2CSendRedRecordArr) ProtoMessage()    {}
func (*S2CSendRedRecordArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{8}
}

func (m *S2CSendRedRecordArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CSendRedRecordArr.Unmarshal(m, b)
}
func (m *S2CSendRedRecordArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CSendRedRecordArr.Marshal(b, m, deterministic)
}
func (m *S2CSendRedRecordArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CSendRedRecordArr.Merge(m, src)
}
func (m *S2CSendRedRecordArr) XXX_Size() int {
	return xxx_messageInfo_S2CSendRedRecordArr.Size(m)
}
func (m *S2CSendRedRecordArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CSendRedRecordArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CSendRedRecordArr proto.InternalMessageInfo

func (m *S2CSendRedRecordArr) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *S2CSendRedRecordArr) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *S2CSendRedRecordArr) GetRedArr() []*S2CSendRedRecord {
	if m != nil {
		return m.RedArr
	}
	return nil
}

func (m *S2CSendRedRecordArr) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *S2CSendRedRecordArr) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *S2CSendRedRecordArr) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *S2CSendRedRecordArr) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

type S2CSendRedRecord struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level"`
	RedAmount            int64    `protobuf:"varint,3,opt,name=redAmount,proto3" json:"redAmount"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	MineNum              int64    `protobuf:"varint,5,opt,name=mineNum,proto3" json:"mineNum"`
	TotalMineAmount      int64    `protobuf:"varint,6,opt,name=totalMineAmount,proto3" json:"totalMineAmount"`
	RedId                int64    `protobuf:"varint,7,opt,name=redId,proto3" json:"redId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CSendRedRecord) Reset()         { *m = S2CSendRedRecord{} }
func (m *S2CSendRedRecord) String() string { return proto.CompactTextString(m) }
func (*S2CSendRedRecord) ProtoMessage()    {}
func (*S2CSendRedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{9}
}

func (m *S2CSendRedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CSendRedRecord.Unmarshal(m, b)
}
func (m *S2CSendRedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CSendRedRecord.Marshal(b, m, deterministic)
}
func (m *S2CSendRedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CSendRedRecord.Merge(m, src)
}
func (m *S2CSendRedRecord) XXX_Size() int {
	return xxx_messageInfo_S2CSendRedRecord.Size(m)
}
func (m *S2CSendRedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CSendRedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_S2CSendRedRecord proto.InternalMessageInfo

func (m *S2CSendRedRecord) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *S2CSendRedRecord) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *S2CSendRedRecord) GetRedAmount() int64 {
	if m != nil {
		return m.RedAmount
	}
	return 0
}

func (m *S2CSendRedRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *S2CSendRedRecord) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

func (m *S2CSendRedRecord) GetTotalMineAmount() int64 {
	if m != nil {
		return m.TotalMineAmount
	}
	return 0
}

func (m *S2CSendRedRecord) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

//狩猎记录-抢包记录
type S2CRobbedRedInfoArr struct {
	TotalAmount          int64               `protobuf:"varint,1,opt,name=totalAmount,proto3" json:"totalAmount"`
	TotalCount           int64               `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount"`
	RobbedArr            []*S2CRobbedRedInfo `protobuf:"bytes,3,rep,name=robbedArr,proto3" json:"robbedArr"`
	Current              int32               `protobuf:"varint,4,opt,name=current,proto3" json:"current"`
	Size                 int32               `protobuf:"varint,5,opt,name=size,proto3" json:"size"`
	Total                int64               `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
	Pages                int32               `protobuf:"varint,7,opt,name=pages,proto3" json:"pages"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *S2CRobbedRedInfoArr) Reset()         { *m = S2CRobbedRedInfoArr{} }
func (m *S2CRobbedRedInfoArr) String() string { return proto.CompactTextString(m) }
func (*S2CRobbedRedInfoArr) ProtoMessage()    {}
func (*S2CRobbedRedInfoArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{10}
}

func (m *S2CRobbedRedInfoArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRobbedRedInfoArr.Unmarshal(m, b)
}
func (m *S2CRobbedRedInfoArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRobbedRedInfoArr.Marshal(b, m, deterministic)
}
func (m *S2CRobbedRedInfoArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRobbedRedInfoArr.Merge(m, src)
}
func (m *S2CRobbedRedInfoArr) XXX_Size() int {
	return xxx_messageInfo_S2CRobbedRedInfoArr.Size(m)
}
func (m *S2CRobbedRedInfoArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRobbedRedInfoArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRobbedRedInfoArr proto.InternalMessageInfo

func (m *S2CRobbedRedInfoArr) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *S2CRobbedRedInfoArr) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *S2CRobbedRedInfoArr) GetRobbedArr() []*S2CRobbedRedInfo {
	if m != nil {
		return m.RobbedArr
	}
	return nil
}

func (m *S2CRobbedRedInfoArr) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *S2CRobbedRedInfoArr) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *S2CRobbedRedInfoArr) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *S2CRobbedRedInfoArr) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

type S2CRobbedRedInfo struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level"`
	SenderName           string   `protobuf:"bytes,3,opt,name=senderName,proto3" json:"senderName"`
	RobbedAmount         int64    `protobuf:"varint,4,opt,name=robbedAmount,proto3" json:"robbedAmount"`
	RedAmount            int64    `protobuf:"varint,5,opt,name=redAmount,proto3" json:"redAmount"`
	IsMine               bool     `protobuf:"varint,6,opt,name=isMine,proto3" json:"isMine"`
	MineNum              int64    `protobuf:"varint,7,opt,name=mineNum,proto3" json:"mineNum"`
	RedId                int64    `protobuf:"varint,8,opt,name=redId,proto3" json:"redId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRobbedRedInfo) Reset()         { *m = S2CRobbedRedInfo{} }
func (m *S2CRobbedRedInfo) String() string { return proto.CompactTextString(m) }
func (*S2CRobbedRedInfo) ProtoMessage()    {}
func (*S2CRobbedRedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{11}
}

func (m *S2CRobbedRedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRobbedRedInfo.Unmarshal(m, b)
}
func (m *S2CRobbedRedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRobbedRedInfo.Marshal(b, m, deterministic)
}
func (m *S2CRobbedRedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRobbedRedInfo.Merge(m, src)
}
func (m *S2CRobbedRedInfo) XXX_Size() int {
	return xxx_messageInfo_S2CRobbedRedInfo.Size(m)
}
func (m *S2CRobbedRedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRobbedRedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRobbedRedInfo proto.InternalMessageInfo

func (m *S2CRobbedRedInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *S2CRobbedRedInfo) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *S2CRobbedRedInfo) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *S2CRobbedRedInfo) GetRobbedAmount() int64 {
	if m != nil {
		return m.RobbedAmount
	}
	return 0
}

func (m *S2CRobbedRedInfo) GetRedAmount() int64 {
	if m != nil {
		return m.RedAmount
	}
	return 0
}

func (m *S2CRobbedRedInfo) GetIsMine() bool {
	if m != nil {
		return m.IsMine
	}
	return false
}

func (m *S2CRobbedRedInfo) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

func (m *S2CRobbedRedInfo) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

//踢人
type S2CKickOutUser struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	Reason               int32    `protobuf:"varint,2,opt,name=reason,proto3" json:"reason"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CKickOutUser) Reset()         { *m = S2CKickOutUser{} }
func (m *S2CKickOutUser) String() string { return proto.CompactTextString(m) }
func (*S2CKickOutUser) ProtoMessage()    {}
func (*S2CKickOutUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{12}
}

func (m *S2CKickOutUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CKickOutUser.Unmarshal(m, b)
}
func (m *S2CKickOutUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CKickOutUser.Marshal(b, m, deterministic)
}
func (m *S2CKickOutUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CKickOutUser.Merge(m, src)
}
func (m *S2CKickOutUser) XXX_Size() int {
	return xxx_messageInfo_S2CKickOutUser.Size(m)
}
func (m *S2CKickOutUser) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CKickOutUser.DiscardUnknown(m)
}

var xxx_messageInfo_S2CKickOutUser proto.InternalMessageInfo

func (m *S2CKickOutUser) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *S2CKickOutUser) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

//房间数组
type S2CRoomInfoArr struct {
	RoomArr              []*S2CRoomInfo `protobuf:"bytes,1,rep,name=roomArr,proto3" json:"roomArr"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CRoomInfoArr) Reset()         { *m = S2CRoomInfoArr{} }
func (m *S2CRoomInfoArr) String() string { return proto.CompactTextString(m) }
func (*S2CRoomInfoArr) ProtoMessage()    {}
func (*S2CRoomInfoArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{13}
}

func (m *S2CRoomInfoArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRoomInfoArr.Unmarshal(m, b)
}
func (m *S2CRoomInfoArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRoomInfoArr.Marshal(b, m, deterministic)
}
func (m *S2CRoomInfoArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRoomInfoArr.Merge(m, src)
}
func (m *S2CRoomInfoArr) XXX_Size() int {
	return xxx_messageInfo_S2CRoomInfoArr.Size(m)
}
func (m *S2CRoomInfoArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRoomInfoArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRoomInfoArr proto.InternalMessageInfo

func (m *S2CRoomInfoArr) GetRoomArr() []*S2CRoomInfo {
	if m != nil {
		return m.RoomArr
	}
	return nil
}

//房间信息
type S2CRoomInfo struct {
	Level                string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	LimitAmount          int64    `protobuf:"varint,2,opt,name=limitAmount,proto3" json:"limitAmount"`
	MaxRed               int64    `protobuf:"varint,3,opt,name=maxRed,proto3" json:"maxRed"`
	Tax                  int64    `protobuf:"varint,4,opt,name=tax,proto3" json:"tax"`
	MaxAllIn             int64    `protobuf:"varint,5,opt,name=maxAllIn,proto3" json:"maxAllIn"`
	Id                   int32    `protobuf:"varint,6,opt,name=id,proto3" json:"id"`
	UserCount            int64    `protobuf:"varint,7,opt,name=userCount,proto3" json:"userCount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRoomInfo) Reset()         { *m = S2CRoomInfo{} }
func (m *S2CRoomInfo) String() string { return proto.CompactTextString(m) }
func (*S2CRoomInfo) ProtoMessage()    {}
func (*S2CRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{14}
}

func (m *S2CRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRoomInfo.Unmarshal(m, b)
}
func (m *S2CRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRoomInfo.Marshal(b, m, deterministic)
}
func (m *S2CRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRoomInfo.Merge(m, src)
}
func (m *S2CRoomInfo) XXX_Size() int {
	return xxx_messageInfo_S2CRoomInfo.Size(m)
}
func (m *S2CRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRoomInfo proto.InternalMessageInfo

func (m *S2CRoomInfo) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *S2CRoomInfo) GetLimitAmount() int64 {
	if m != nil {
		return m.LimitAmount
	}
	return 0
}

func (m *S2CRoomInfo) GetMaxRed() int64 {
	if m != nil {
		return m.MaxRed
	}
	return 0
}

func (m *S2CRoomInfo) GetTax() int64 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *S2CRoomInfo) GetMaxAllIn() int64 {
	if m != nil {
		return m.MaxAllIn
	}
	return 0
}

func (m *S2CRoomInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2CRoomInfo) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

//狩猎记录-中雷记录
type S2CMinRecordArr struct {
	TotalAmount          int64           `protobuf:"varint,1,opt,name=totalAmount,proto3" json:"totalAmount"`
	TotalCount           int64           `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount"`
	MineArr              []*S2CMinRecord `protobuf:"bytes,3,rep,name=mineArr,proto3" json:"mineArr"`
	Current              int32           `protobuf:"varint,4,opt,name=current,proto3" json:"current"`
	Size                 int32           `protobuf:"varint,5,opt,name=size,proto3" json:"size"`
	Total                int64           `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
	Pages                int32           `protobuf:"varint,7,opt,name=pages,proto3" json:"pages"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *S2CMinRecordArr) Reset()         { *m = S2CMinRecordArr{} }
func (m *S2CMinRecordArr) String() string { return proto.CompactTextString(m) }
func (*S2CMinRecordArr) ProtoMessage()    {}
func (*S2CMinRecordArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{15}
}

func (m *S2CMinRecordArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMinRecordArr.Unmarshal(m, b)
}
func (m *S2CMinRecordArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMinRecordArr.Marshal(b, m, deterministic)
}
func (m *S2CMinRecordArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMinRecordArr.Merge(m, src)
}
func (m *S2CMinRecordArr) XXX_Size() int {
	return xxx_messageInfo_S2CMinRecordArr.Size(m)
}
func (m *S2CMinRecordArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMinRecordArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMinRecordArr proto.InternalMessageInfo

func (m *S2CMinRecordArr) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *S2CMinRecordArr) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *S2CMinRecordArr) GetMineArr() []*S2CMinRecord {
	if m != nil {
		return m.MineArr
	}
	return nil
}

func (m *S2CMinRecordArr) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *S2CMinRecordArr) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *S2CMinRecordArr) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *S2CMinRecordArr) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

type S2CMinRecord struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level"`
	SenderName           string   `protobuf:"bytes,3,opt,name=senderName,proto3" json:"senderName"`
	RobbedAmount         int64    `protobuf:"varint,4,opt,name=robbedAmount,proto3" json:"robbedAmount"`
	MineAmount           int64    `protobuf:"varint,5,opt,name=mineAmount,proto3" json:"mineAmount"`
	MineNum              int64    `protobuf:"varint,6,opt,name=mineNum,proto3" json:"mineNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CMinRecord) Reset()         { *m = S2CMinRecord{} }
func (m *S2CMinRecord) String() string { return proto.CompactTextString(m) }
func (*S2CMinRecord) ProtoMessage()    {}
func (*S2CMinRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{16}
}

func (m *S2CMinRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMinRecord.Unmarshal(m, b)
}
func (m *S2CMinRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMinRecord.Marshal(b, m, deterministic)
}
func (m *S2CMinRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMinRecord.Merge(m, src)
}
func (m *S2CMinRecord) XXX_Size() int {
	return xxx_messageInfo_S2CMinRecord.Size(m)
}
func (m *S2CMinRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMinRecord.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMinRecord proto.InternalMessageInfo

func (m *S2CMinRecord) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *S2CMinRecord) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *S2CMinRecord) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *S2CMinRecord) GetRobbedAmount() int64 {
	if m != nil {
		return m.RobbedAmount
	}
	return 0
}

func (m *S2CMinRecord) GetMineAmount() int64 {
	if m != nil {
		return m.MineAmount
	}
	return 0
}

func (m *S2CMinRecord) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

//每秒更新红包血量
type S2CRedFlood struct {
	RedId                int64    `protobuf:"varint,1,opt,name=redId,proto3" json:"redId"`
	RobbedCount          int64    `protobuf:"varint,2,opt,name=robbedCount,proto3" json:"robbedCount"`
	RedFlood             int64    `protobuf:"varint,3,opt,name=redFlood,proto3" json:"redFlood"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedFlood) Reset()         { *m = S2CRedFlood{} }
func (m *S2CRedFlood) String() string { return proto.CompactTextString(m) }
func (*S2CRedFlood) ProtoMessage()    {}
func (*S2CRedFlood) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{17}
}

func (m *S2CRedFlood) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedFlood.Unmarshal(m, b)
}
func (m *S2CRedFlood) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedFlood.Marshal(b, m, deterministic)
}
func (m *S2CRedFlood) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedFlood.Merge(m, src)
}
func (m *S2CRedFlood) XXX_Size() int {
	return xxx_messageInfo_S2CRedFlood.Size(m)
}
func (m *S2CRedFlood) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedFlood.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedFlood proto.InternalMessageInfo

func (m *S2CRedFlood) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

func (m *S2CRedFlood) GetRobbedCount() int64 {
	if m != nil {
		return m.RobbedCount
	}
	return 0
}

func (m *S2CRedFlood) GetRedFlood() int64 {
	if m != nil {
		return m.RedFlood
	}
	return 0
}

func (m *S2CRedFlood) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

//坐标轴
type S2CAxis struct {
	XAxis                int32    `protobuf:"varint,1,opt,name=XAxis,proto3" json:"XAxis"`
	YAxis                int32    `protobuf:"varint,2,opt,name=YAxis,proto3" json:"YAxis"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CAxis) Reset()         { *m = S2CAxis{} }
func (m *S2CAxis) String() string { return proto.CompactTextString(m) }
func (*S2CAxis) ProtoMessage()    {}
func (*S2CAxis) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{18}
}

func (m *S2CAxis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CAxis.Unmarshal(m, b)
}
func (m *S2CAxis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CAxis.Marshal(b, m, deterministic)
}
func (m *S2CAxis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CAxis.Merge(m, src)
}
func (m *S2CAxis) XXX_Size() int {
	return xxx_messageInfo_S2CAxis.Size(m)
}
func (m *S2CAxis) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CAxis.DiscardUnknown(m)
}

var xxx_messageInfo_S2CAxis proto.InternalMessageInfo

func (m *S2CAxis) GetXAxis() int32 {
	if m != nil {
		return m.XAxis
	}
	return 0
}

func (m *S2CAxis) GetYAxis() int32 {
	if m != nil {
		return m.YAxis
	}
	return 0
}

//红包消失
type S2CRedDisappear struct {
	RedId                int64    `protobuf:"varint,1,opt,name=redId,proto3" json:"redId"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level"`
	IsRobbed             bool     `protobuf:"varint,3,opt,name=isRobbed,proto3" json:"isRobbed"`
	IsOtherRobbed        bool     `protobuf:"varint,4,opt,name=isOtherRobbed,proto3" json:"isOtherRobbed"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedDisappear) Reset()         { *m = S2CRedDisappear{} }
func (m *S2CRedDisappear) String() string { return proto.CompactTextString(m) }
func (*S2CRedDisappear) ProtoMessage()    {}
func (*S2CRedDisappear) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{19}
}

func (m *S2CRedDisappear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedDisappear.Unmarshal(m, b)
}
func (m *S2CRedDisappear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedDisappear.Marshal(b, m, deterministic)
}
func (m *S2CRedDisappear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedDisappear.Merge(m, src)
}
func (m *S2CRedDisappear) XXX_Size() int {
	return xxx_messageInfo_S2CRedDisappear.Size(m)
}
func (m *S2CRedDisappear) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedDisappear.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedDisappear proto.InternalMessageInfo

func (m *S2CRedDisappear) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

func (m *S2CRedDisappear) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *S2CRedDisappear) GetIsRobbed() bool {
	if m != nil {
		return m.IsRobbed
	}
	return false
}

func (m *S2CRedDisappear) GetIsOtherRobbed() bool {
	if m != nil {
		return m.IsOtherRobbed
	}
	return false
}

//大厅抢包记录
type S2CHallRecordArr struct {
	Current              int32            `protobuf:"varint,1,opt,name=current,proto3" json:"current"`
	Size                 int32            `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Total                int64            `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	Pages                int32            `protobuf:"varint,4,opt,name=pages,proto3" json:"pages"`
	RecordArr            []*S2CHallRecord `protobuf:"bytes,5,rep,name=recordArr,proto3" json:"recordArr"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *S2CHallRecordArr) Reset()         { *m = S2CHallRecordArr{} }
func (m *S2CHallRecordArr) String() string { return proto.CompactTextString(m) }
func (*S2CHallRecordArr) ProtoMessage()    {}
func (*S2CHallRecordArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{20}
}

func (m *S2CHallRecordArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHallRecordArr.Unmarshal(m, b)
}
func (m *S2CHallRecordArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHallRecordArr.Marshal(b, m, deterministic)
}
func (m *S2CHallRecordArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHallRecordArr.Merge(m, src)
}
func (m *S2CHallRecordArr) XXX_Size() int {
	return xxx_messageInfo_S2CHallRecordArr.Size(m)
}
func (m *S2CHallRecordArr) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHallRecordArr.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHallRecordArr proto.InternalMessageInfo

func (m *S2CHallRecordArr) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *S2CHallRecordArr) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *S2CHallRecordArr) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *S2CHallRecordArr) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *S2CHallRecordArr) GetRecordArr() []*S2CHallRecord {
	if m != nil {
		return m.RecordArr
	}
	return nil
}

type S2CHallRecord struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName"`
	RobbedAmount         int64    `protobuf:"varint,3,opt,name=robbedAmount,proto3" json:"robbedAmount"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time"`
	IsMine               bool     `protobuf:"varint,5,opt,name=isMine,proto3" json:"isMine"`
	MineAmount           int64    `protobuf:"varint,6,opt,name=mineAmount,proto3" json:"mineAmount"`
	SenderId             int64    `protobuf:"varint,7,opt,name=senderId,proto3" json:"senderId"`
	SenderName           string   `protobuf:"bytes,8,opt,name=senderName,proto3" json:"senderName"`
	RedAmount            int64    `protobuf:"varint,9,opt,name=redAmount,proto3" json:"redAmount"`
	MineNum              int64    `protobuf:"varint,10,opt,name=mineNum,proto3" json:"mineNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CHallRecord) Reset()         { *m = S2CHallRecord{} }
func (m *S2CHallRecord) String() string { return proto.CompactTextString(m) }
func (*S2CHallRecord) ProtoMessage()    {}
func (*S2CHallRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{21}
}

func (m *S2CHallRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHallRecord.Unmarshal(m, b)
}
func (m *S2CHallRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHallRecord.Marshal(b, m, deterministic)
}
func (m *S2CHallRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHallRecord.Merge(m, src)
}
func (m *S2CHallRecord) XXX_Size() int {
	return xxx_messageInfo_S2CHallRecord.Size(m)
}
func (m *S2CHallRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHallRecord.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHallRecord proto.InternalMessageInfo

func (m *S2CHallRecord) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *S2CHallRecord) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *S2CHallRecord) GetRobbedAmount() int64 {
	if m != nil {
		return m.RobbedAmount
	}
	return 0
}

func (m *S2CHallRecord) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *S2CHallRecord) GetIsMine() bool {
	if m != nil {
		return m.IsMine
	}
	return false
}

func (m *S2CHallRecord) GetMineAmount() int64 {
	if m != nil {
		return m.MineAmount
	}
	return 0
}

func (m *S2CHallRecord) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *S2CHallRecord) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *S2CHallRecord) GetRedAmount() int64 {
	if m != nil {
		return m.RedAmount
	}
	return 0
}

func (m *S2CHallRecord) GetMineNum() int64 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

//红包当前已被抢个数
type S2CRobbedCount struct {
	RobbedCount          int64    `protobuf:"varint,1,opt,name=robbedCount,proto3" json:"robbedCount"`
	RedId                int64    `protobuf:"varint,2,opt,name=redId,proto3" json:"redId"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRobbedCount) Reset()         { *m = S2CRobbedCount{} }
func (m *S2CRobbedCount) String() string { return proto.CompactTextString(m) }
func (*S2CRobbedCount) ProtoMessage()    {}
func (*S2CRobbedCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{22}
}

func (m *S2CRobbedCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRobbedCount.Unmarshal(m, b)
}
func (m *S2CRobbedCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRobbedCount.Marshal(b, m, deterministic)
}
func (m *S2CRobbedCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRobbedCount.Merge(m, src)
}
func (m *S2CRobbedCount) XXX_Size() int {
	return xxx_messageInfo_S2CRobbedCount.Size(m)
}
func (m *S2CRobbedCount) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRobbedCount.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRobbedCount proto.InternalMessageInfo

func (m *S2CRobbedCount) GetRobbedCount() int64 {
	if m != nil {
		return m.RobbedCount
	}
	return 0
}

func (m *S2CRobbedCount) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

func (m *S2CRobbedCount) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

//红包等待发送
type S2CRedWaitSend struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedWaitSend) Reset()         { *m = S2CRedWaitSend{} }
func (m *S2CRedWaitSend) String() string { return proto.CompactTextString(m) }
func (*S2CRedWaitSend) ProtoMessage()    {}
func (*S2CRedWaitSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{23}
}

func (m *S2CRedWaitSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedWaitSend.Unmarshal(m, b)
}
func (m *S2CRedWaitSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedWaitSend.Marshal(b, m, deterministic)
}
func (m *S2CRedWaitSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedWaitSend.Merge(m, src)
}
func (m *S2CRedWaitSend) XXX_Size() int {
	return xxx_messageInfo_S2CRedWaitSend.Size(m)
}
func (m *S2CRedWaitSend) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedWaitSend.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedWaitSend proto.InternalMessageInfo

func (m *S2CRedWaitSend) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//玩家金额
type S2CUserScore struct {
	Score                int64    `protobuf:"varint,1,opt,name=score,proto3" json:"score"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CUserScore) Reset()         { *m = S2CUserScore{} }
func (m *S2CUserScore) String() string { return proto.CompactTextString(m) }
func (*S2CUserScore) ProtoMessage()    {}
func (*S2CUserScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{24}
}

func (m *S2CUserScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUserScore.Unmarshal(m, b)
}
func (m *S2CUserScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUserScore.Marshal(b, m, deterministic)
}
func (m *S2CUserScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUserScore.Merge(m, src)
}
func (m *S2CUserScore) XXX_Size() int {
	return xxx_messageInfo_S2CUserScore.Size(m)
}
func (m *S2CUserScore) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUserScore.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUserScore proto.InternalMessageInfo

func (m *S2CUserScore) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type S2CRedId struct {
	RedId                int64    `protobuf:"varint,1,opt,name=redId,proto3" json:"redId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRedId) Reset()         { *m = S2CRedId{} }
func (m *S2CRedId) String() string { return proto.CompactTextString(m) }
func (*S2CRedId) ProtoMessage()    {}
func (*S2CRedId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{25}
}

func (m *S2CRedId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRedId.Unmarshal(m, b)
}
func (m *S2CRedId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRedId.Marshal(b, m, deterministic)
}
func (m *S2CRedId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRedId.Merge(m, src)
}
func (m *S2CRedId) XXX_Size() int {
	return xxx_messageInfo_S2CRedId.Size(m)
}
func (m *S2CRedId) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRedId.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRedId proto.InternalMessageInfo

func (m *S2CRedId) GetRedId() int64 {
	if m != nil {
		return m.RedId
	}
	return 0
}

//玩家人数
type S2CUserCount struct {
	UserCount            int32    `protobuf:"varint,1,opt,name=userCount,proto3" json:"userCount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CUserCount) Reset()         { *m = S2CUserCount{} }
func (m *S2CUserCount) String() string { return proto.CompactTextString(m) }
func (*S2CUserCount) ProtoMessage()    {}
func (*S2CUserCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{26}
}

func (m *S2CUserCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUserCount.Unmarshal(m, b)
}
func (m *S2CUserCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUserCount.Marshal(b, m, deterministic)
}
func (m *S2CUserCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUserCount.Merge(m, src)
}
func (m *S2CUserCount) XXX_Size() int {
	return xxx_messageInfo_S2CUserCount.Size(m)
}
func (m *S2CUserCount) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUserCount.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUserCount proto.InternalMessageInfo

func (m *S2CUserCount) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

//错误消息
type S2CString struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CString) Reset()         { *m = S2CString{} }
func (m *S2CString) String() string { return proto.CompactTextString(m) }
func (*S2CString) ProtoMessage()    {}
func (*S2CString) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a66076066de807d, []int{27}
}

func (m *S2CString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CString.Unmarshal(m, b)
}
func (m *S2CString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CString.Marshal(b, m, deterministic)
}
func (m *S2CString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CString.Merge(m, src)
}
func (m *S2CString) XXX_Size() int {
	return xxx_messageInfo_S2CString.Size(m)
}
func (m *S2CString) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CString.DiscardUnknown(m)
}

var xxx_messageInfo_S2CString proto.InternalMessageInfo

func (m *S2CString) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*S2CMsg)(nil), "msg.S2CMsg")
	proto.RegisterType((*S2CRoomBaseInfo)(nil), "msg.S2CRoomBaseInfo")
	proto.RegisterType((*S2CRedConfigInfo)(nil), "msg.S2CRedConfigInfo")
	proto.RegisterType((*S2CUserInfoArr)(nil), "msg.S2CUserInfoArr")
	proto.RegisterType((*S2CUserInfo)(nil), "msg.S2CUserInfo")
	proto.RegisterType((*S2CRedInfo)(nil), "msg.S2CRedInfo")
	proto.RegisterType((*S2CRobRed)(nil), "msg.S2CRobRed")
	proto.RegisterType((*S2CRedArr)(nil), "msg.S2CRedArr")
	proto.RegisterType((*S2CSendRedRecordArr)(nil), "msg.S2CSendRedRecordArr")
	proto.RegisterType((*S2CSendRedRecord)(nil), "msg.S2CSendRedRecord")
	proto.RegisterType((*S2CRobbedRedInfoArr)(nil), "msg.S2CRobbedRedInfoArr")
	proto.RegisterType((*S2CRobbedRedInfo)(nil), "msg.S2CRobbedRedInfo")
	proto.RegisterType((*S2CKickOutUser)(nil), "msg.S2CKickOutUser")
	proto.RegisterType((*S2CRoomInfoArr)(nil), "msg.S2CRoomInfoArr")
	proto.RegisterType((*S2CRoomInfo)(nil), "msg.S2CRoomInfo")
	proto.RegisterType((*S2CMinRecordArr)(nil), "msg.S2CMinRecordArr")
	proto.RegisterType((*S2CMinRecord)(nil), "msg.S2CMinRecord")
	proto.RegisterType((*S2CRedFlood)(nil), "msg.S2CRedFlood")
	proto.RegisterType((*S2CAxis)(nil), "msg.S2CAxis")
	proto.RegisterType((*S2CRedDisappear)(nil), "msg.S2CRedDisappear")
	proto.RegisterType((*S2CHallRecordArr)(nil), "msg.S2CHallRecordArr")
	proto.RegisterType((*S2CHallRecord)(nil), "msg.S2CHallRecord")
	proto.RegisterType((*S2CRobbedCount)(nil), "msg.S2CRobbedCount")
	proto.RegisterType((*S2CRedWaitSend)(nil), "msg.S2cRedWaitSend")
	proto.RegisterType((*S2CUserScore)(nil), "msg.S2cUserScore")
	proto.RegisterType((*S2CRedId)(nil), "msg.S2CRedId")
	proto.RegisterType((*S2CUserCount)(nil), "msg.S2CUserCount")
	proto.RegisterType((*S2CString)(nil), "msg.S2CString")
}

func init() { proto.RegisterFile("game_s2c.proto", fileDescriptor_7a66076066de807d) }

var fileDescriptor_7a66076066de807d = []byte{
	// 1321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcf, 0x6e, 0x23, 0xc5,
	0x13, 0xd6, 0xcc, 0xd8, 0xe3, 0x71, 0x27, 0x9b, 0xe4, 0xd7, 0x3f, 0x58, 0x8d, 0x56, 0xcb, 0xca,
	0x6a, 0xad, 0x96, 0x68, 0x59, 0x22, 0xe4, 0x85, 0x0b, 0xe2, 0x12, 0x8c, 0x10, 0x11, 0x4a, 0x56,
	0x6a, 0x6b, 0x05, 0x5c, 0x40, 0x63, 0x4f, 0xc7, 0x69, 0xe1, 0x99, 0xb1, 0xa6, 0xc7, 0xbb, 0x11,
	0x17, 0x0e, 0xbc, 0x03, 0x47, 0xae, 0x3c, 0x01, 0x48, 0xbc, 0x03, 0x4f, 0xc0, 0x89, 0x53, 0x2e,
	0xbc, 0x04, 0xaa, 0xea, 0x9e, 0x99, 0x6e, 0x7b, 0x12, 0xfe, 0x68, 0xc3, 0xad, 0xab, 0xba, 0xdd,
	0x5d, 0x5d, 0xdf, 0x57, 0x5f, 0xd7, 0x98, 0xec, 0x2d, 0x92, 0x4c, 0x7c, 0xa5, 0xc6, 0xf3, 0xa3,
	0x55, 0x59, 0x54, 0x05, 0x0d, 0x32, 0xb5, 0x60, 0x67, 0x24, 0x9c, 0x8e, 0x27, 0xa7, 0x6a, 0x41,
	0x63, 0x32, 0xc8, 0x12, 0x99, 0x4f, 0xb2, 0x34, 0xf6, 0x46, 0xde, 0x61, 0x9f, 0xd7, 0x26, 0xbd,
	0x4b, 0x42, 0xb5, 0x9e, 0xc1, 0x84, 0x8f, 0x13, 0xc6, 0xa2, 0x94, 0xf4, 0x66, 0xeb, 0xf3, 0xf3,
	0x38, 0x18, 0x79, 0x87, 0xbb, 0x1c, 0xc7, 0xec, 0x0f, 0x9f, 0xec, 0x4f, 0xc7, 0x13, 0x5e, 0x14,
	0xd9, 0x87, 0x89, 0x12, 0x27, 0xf9, 0x79, 0x41, 0xf7, 0x88, 0x2f, 0xf5, 0xa6, 0x01, 0xf7, 0x25,
	0xfe, 0x2e, 0x4f, 0x32, 0x81, 0xbb, 0x0d, 0x39, 0x8e, 0xe9, 0x88, 0xec, 0x2c, 0x65, 0x26, 0xab,
	0xe3, 0xac, 0x58, 0xe7, 0x15, 0x6e, 0x19, 0x70, 0xdb, 0x05, 0x51, 0x64, 0xc9, 0x25, 0x17, 0x69,
	0xdc, 0xc3, 0x49, 0x63, 0xd1, 0x37, 0x49, 0x58, 0x8a, 0xf4, 0xb8, 0x2c, 0xe3, 0xfe, 0x28, 0x38,
	0xdc, 0x19, 0xef, 0x1f, 0x65, 0x6a, 0x71, 0x04, 0x31, 0x88, 0x14, 0x8e, 0xe7, 0x66, 0x9a, 0x3e,
	0x26, 0x83, 0xb5, 0x12, 0x25, 0xac, 0x0c, 0x71, 0xe5, 0x41, 0xbd, 0xf2, 0xb9, 0x12, 0x25, 0x2e,
	0xad, 0x17, 0xd0, 0xfb, 0x64, 0x08, 0xc3, 0x09, 0x06, 0x33, 0xc0, 0xf3, 0x5a, 0x07, 0x7d, 0x42,
	0x22, 0x25, 0x96, 0xe7, 0xf0, 0x93, 0x38, 0x1a, 0x79, 0x9d, 0x5b, 0x35, 0x2b, 0xe8, 0x53, 0x32,
	0x2c, 0x45, 0x3a, 0x29, 0xf2, 0x73, 0xb9, 0x88, 0x87, 0xb8, 0xfc, 0x75, 0x2b, 0x46, 0x3d, 0x81,
	0xbf, 0x69, 0xd7, 0xd1, 0x87, 0xe4, 0xce, 0xcb, 0x44, 0x56, 0x53, 0x91, 0xa7, 0x3a, 0x08, 0x82,
	0xa9, 0x77, 0x9d, 0xec, 0x05, 0x39, 0xd8, 0xdc, 0x04, 0xb2, 0x5b, 0xa4, 0xa9, 0x32, 0x20, 0xe2,
	0x98, 0xbe, 0x46, 0xfa, 0x73, 0xdc, 0x45, 0x03, 0xa8, 0x0d, 0xc8, 0x68, 0x52, 0xa7, 0x3b, 0x80,
	0x8c, 0x6a, 0x0b, 0xb0, 0x50, 0xab, 0x64, 0x2e, 0x0c, 0x16, 0x3a, 0xdd, 0xb6, 0x8b, 0x7d, 0xef,
	0x91, 0x3d, 0xeb, 0xb2, 0x90, 0xb1, 0x98, 0x0c, 0xe6, 0xeb, 0xb2, 0x14, 0x79, 0x55, 0xd3, 0xc7,
	0x98, 0x10, 0x90, 0x92, 0xdf, 0x08, 0x73, 0x36, 0x8e, 0x21, 0xa0, 0xaa, 0xa8, 0x92, 0xa5, 0x01,
	0x5a, 0x1b, 0xe0, 0x5d, 0x25, 0x0b, 0xa1, 0xf0, 0xc8, 0x3e, 0xd7, 0x86, 0x8d, 0x5b, 0xff, 0x2f,
	0x70, 0x63, 0x3f, 0x79, 0x64, 0xc7, 0x9a, 0xa0, 0x07, 0x24, 0x58, 0x37, 0xdc, 0x83, 0x61, 0x27,
	0xf9, 0x28, 0xe9, 0x5d, 0x88, 0x24, 0xc5, 0x60, 0x86, 0x1c, 0xc7, 0x56, 0x72, 0x0c, 0xdd, 0x4c,
	0x72, 0xe0, 0x9e, 0x17, 0x89, 0x2c, 0x4f, 0xd2, 0xb8, 0x6f, 0xee, 0xa9, 0x4d, 0x2c, 0x93, 0x2a,
	0xa9, 0xd6, 0x2a, 0x0e, 0x4d, 0x99, 0xa0, 0x45, 0x19, 0xd9, 0x2d, 0x8b, 0xd9, 0x4c, 0xa4, 0x26,
	0x9f, 0x9a, 0x4e, 0x8e, 0x8f, 0x5d, 0xf9, 0x84, 0xb4, 0x94, 0x85, 0x44, 0x94, 0x22, 0x3d, 0xa9,
	0x03, 0xd7, 0x86, 0x15, 0x92, 0xef, 0x84, 0xd4, 0xa0, 0x6b, 0x92, 0xd9, 0xa0, 0x6b, 0xc2, 0xe9,
	0x39, 0xe1, 0x40, 0x9d, 0xcb, 0x5c, 0x9c, 0xad, 0x33, 0xbc, 0x40, 0xc0, 0x6b, 0x13, 0x4f, 0x2d,
	0xd6, 0x95, 0x30, 0xf1, 0x6b, 0x03, 0xd8, 0xa0, 0x43, 0xb5, 0x8b, 0xc1, 0x76, 0xd1, 0x7b, 0x50,
	0x0e, 0x79, 0x2a, 0x20, 0x27, 0x11, 0x4e, 0x37, 0x36, 0xa4, 0x56, 0xaa, 0x63, 0x89, 0xbc, 0x8f,
	0x38, 0x8e, 0xc1, 0x57, 0xc9, 0x4c, 0x20, 0xa5, 0x03, 0x8e, 0x63, 0x38, 0x7b, 0x29, 0x5e, 0x88,
	0x65, 0xbc, 0xa3, 0xcf, 0x46, 0x03, 0xbc, 0x6a, 0x25, 0x44, 0x1a, 0xef, 0x8e, 0x02, 0xf0, 0xa2,
	0x41, 0x1f, 0x10, 0xa2, 0xf7, 0x3f, 0x03, 0x20, 0xef, 0x20, 0x68, 0x96, 0x07, 0xe2, 0x29, 0x45,
	0xfa, 0xf1, 0xb2, 0x28, 0xd2, 0x78, 0x4f, 0xc7, 0x53, 0xdb, 0xec, 0x3b, 0x9f, 0x0c, 0x51, 0x9f,
	0x66, 0xa0, 0x1d, 0xd7, 0xe6, 0x59, 0xaa, 0x53, 0x99, 0x6b, 0x92, 0x44, 0xdc, 0x58, 0x5b, 0x40,
	0x06, 0xdb, 0x40, 0xd2, 0x47, 0x64, 0x2f, 0x2f, 0x2a, 0x6e, 0x25, 0x4c, 0xd3, 0x67, 0xc3, 0x6b,
	0x61, 0xd9, 0x77, 0xb0, 0x74, 0xef, 0x16, 0x6e, 0xdd, 0xcd, 0x42, 0x6f, 0xb0, 0x85, 0x9e, 0xce,
	0x60, 0xb4, 0x99, 0xc1, 0x79, 0x51, 0x0a, 0x04, 0x20, 0xe0, 0xda, 0x60, 0xef, 0xea, 0x24, 0x68,
	0x5d, 0x6c, 0x05, 0xd4, 0xbb, 0x51, 0x40, 0xd9, 0xef, 0x1e, 0xf9, 0xff, 0x74, 0x3c, 0x01, 0xf9,
	0xe1, 0x22, 0xe5, 0x62, 0x5e, 0x94, 0xb8, 0xc1, 0x88, 0xec, 0x60, 0xfd, 0x9a, 0xb4, 0xe8, 0x5c,
	0xda, 0x2e, 0xb8, 0x15, 0x9a, 0x13, 0x8b, 0xbd, 0x96, 0x87, 0xbe, 0xdd, 0x84, 0x10, 0x60, 0x08,
	0x8d, 0x3e, 0x3a, 0x67, 0x35, 0x4a, 0x6e, 0x69, 0x4d, 0xaf, 0x5b, 0x6b, 0xfa, 0x5d, 0x5a, 0x13,
	0x76, 0x6a, 0xcd, 0xc0, 0xd2, 0x1a, 0xf6, 0xab, 0x87, 0x8a, 0xea, 0x1c, 0xdb, 0xf0, 0xd5, 0xeb,
	0xe2, 0xab, 0xd6, 0x11, 0x93, 0xed, 0xfb, 0x28, 0xf5, 0x0e, 0x3d, 0x5a, 0xc7, 0xbf, 0xa8, 0xc8,
	0x43, 0xb2, 0x8f, 0xd1, 0x02, 0xfd, 0xcc, 0xae, 0xfa, 0x12, 0x9b, 0xee, 0x96, 0xc9, 0x03, 0x8b,
	0xc9, 0xec, 0x4a, 0x23, 0xa6, 0x89, 0x67, 0xe0, 0x7c, 0x35, 0x88, 0xc1, 0xa3, 0xa6, 0x79, 0xbf,
	0x0d, 0x9a, 0x73, 0x1c, 0x6f, 0xd7, 0xdd, 0x22, 0x6e, 0x57, 0x1a, 0x37, 0xe7, 0xe4, 0x7f, 0x80,
	0x9b, 0x5b, 0x75, 0xc1, 0x56, 0xd5, 0x6d, 0x56, 0x7e, 0xaf, 0xa3, 0xf2, 0x1d, 0xec, 0xfb, 0x1d,
	0xd8, 0x1b, 0x4d, 0x09, 0x1d, 0x4d, 0xb9, 0xb1, 0x9e, 0x35, 0xa2, 0x91, 0x8d, 0xe8, 0xfb, 0xf8,
	0xf0, 0x7e, 0x2a, 0xe7, 0x5f, 0x3f, 0x5b, 0x57, 0xf0, 0xcc, 0x75, 0x3c, 0x71, 0x77, 0xa1, 0x9a,
	0x12, 0x55, 0xe4, 0x75, 0xbf, 0xa6, 0x2d, 0xf6, 0x01, 0xfe, 0x16, 0x5a, 0xb3, 0x9a, 0x07, 0x8f,
	0xc9, 0xa0, 0x2c, 0x8a, 0xac, 0xad, 0xfd, 0x83, 0x16, 0x43, 0xbd, 0x8a, 0xd7, 0x0b, 0xd8, 0x2f,
	0xfa, 0x69, 0xad, 0x27, 0xda, 0x4c, 0x7a, 0x76, 0x26, 0x37, 0xfa, 0x38, 0xff, 0xa6, 0x3e, 0x2e,
	0x70, 0xfa, 0xb8, 0x03, 0x12, 0x54, 0xc9, 0xa5, 0x49, 0x2d, 0x0c, 0x41, 0xc7, 0xb3, 0xe4, 0xf2,
	0x78, 0xb9, 0x3c, 0xc9, 0x4d, 0x42, 0x1b, 0xdb, 0xf4, 0x94, 0xfa, 0xa1, 0x82, 0x9e, 0xf2, 0xc6,
	0x86, 0x8d, 0xfd, 0xe6, 0x61, 0x57, 0x7a, 0x2a, 0xf3, 0x57, 0xa9, 0x5a, 0x6f, 0x69, 0xec, 0xda,
	0x0a, 0xf8, 0x5f, 0x9d, 0xbd, 0xe6, 0x20, 0x5e, 0xaf, 0xb8, 0x45, 0xee, 0xff, 0xec, 0x91, 0x5d,
	0xfb, 0xcc, 0xff, 0x98, 0xf7, 0x0f, 0x08, 0xc9, 0x5a, 0x79, 0xd2, 0x38, 0x59, 0x1e, 0x9b, 0xe1,
	0xa1, 0xc3, 0x70, 0xf6, 0x52, 0x13, 0xca, 0x3c, 0xcd, 0xd7, 0x3c, 0xc6, 0x1b, 0xed, 0x87, 0xdf,
	0xd9, 0x7e, 0x34, 0xcf, 0x7d, 0xe0, 0x3e, 0xf7, 0xed, 0xb5, 0x7b, 0xd6, 0xa3, 0xc8, 0xde, 0x23,
	0x83, 0xe9, 0x78, 0x72, 0x7c, 0x29, 0xb1, 0x33, 0xfe, 0x1c, 0x06, 0xa6, 0x69, 0xd5, 0x06, 0x78,
	0xbf, 0x40, 0xaf, 0xe9, 0x97, 0xd1, 0x60, 0xdf, 0xea, 0x4f, 0x1b, 0x91, 0x7e, 0x24, 0x55, 0xb2,
	0x5a, 0x89, 0xa4, 0xbc, 0x26, 0x66, 0x27, 0xd9, 0xcd, 0x53, 0x7c, 0x8f, 0x44, 0x52, 0x69, 0x85,
	0xc2, 0x38, 0x23, 0xde, 0xd8, 0xd0, 0xee, 0x4b, 0xf5, 0xac, 0xba, 0x10, 0xa5, 0x59, 0xd0, 0xc3,
	0x05, 0xae, 0x93, 0xfd, 0xa0, 0x55, 0xee, 0x93, 0x64, 0xb9, 0x6c, 0x79, 0x7c, 0x7b, 0x8d, 0xf7,
	0x3b, 0xa0, 0x68, 0xe6, 0x18, 0xd3, 0x7a, 0xd3, 0x9a, 0xe1, 0x6d, 0x0c, 0xbc, 0x5d, 0xc4, 0x7e,
	0xf4, 0xc9, 0x1d, 0x67, 0x12, 0xaa, 0x1d, 0xca, 0xb0, 0xc9, 0x90, 0xb1, 0x20, 0x19, 0x30, 0x3a,
	0x6b, 0x5b, 0xf1, 0xc6, 0xfe, 0x5b, 0x7d, 0x56, 0xcd, 0xf1, 0x9e, 0xc5, 0xf1, 0x56, 0x63, 0xfb,
	0x8e, 0xc6, 0xba, 0x0c, 0x0d, 0xb7, 0x18, 0x6a, 0xf7, 0xaf, 0x83, 0x8d, 0xfe, 0xd5, 0xad, 0x90,
	0x68, 0xab, 0x42, 0x1c, 0xd5, 0x1f, 0x6e, 0xaa, 0xbe, 0xc5, 0x7d, 0xe2, 0x72, 0xff, 0x4b, 0xa3,
	0xc5, 0x2d, 0x8d, 0x37, 0x88, 0xee, 0x6d, 0x13, 0xbd, 0x21, 0x9b, 0xdf, 0x49, 0xb6, 0xc0, 0xa6,
	0xf8, 0x23, 0xd8, 0x7f, 0xce, 0x45, 0xfa, 0x99, 0xf9, 0x60, 0x6c, 0xbf, 0x12, 0x3c, 0xeb, 0x1b,
	0x90, 0x3d, 0x04, 0xed, 0x98, 0xc3, 0x43, 0x32, 0x85, 0xce, 0xb0, 0xed, 0x17, 0x3d, 0xbb, 0x5f,
	0x1c, 0x91, 0xc8, 0xf4, 0x83, 0xd7, 0x94, 0x29, 0x7b, 0x82, 0x1a, 0xf4, 0xbc, 0xf9, 0x44, 0x76,
	0xf4, 0x58, 0x9f, 0x68, 0xe9, 0xf1, 0x1b, 0xd8, 0x7f, 0x4e, 0xab, 0x52, 0xe6, 0x0b, 0x10, 0xfe,
	0x4c, 0x2d, 0xcc, 0x33, 0x02, 0xc3, 0x59, 0x88, 0x7f, 0x50, 0x3c, 0xfd, 0x33, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0xb1, 0xa1, 0xe2, 0xb2, 0x10, 0x00, 0x00,
}
