// Code generated by protoc-gen-go. DO NOT EDIT.
// source: watch_banker.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端到服务器发送消息的类型
type ReceiveMessageType int32

const (
	ReceiveMessageType_C2SStartID     ReceiveMessageType = 0
	ReceiveMessageType_C2SRobBanker   ReceiveMessageType = 1
	ReceiveMessageType_C2SBetChips    ReceiveMessageType = 2
	ReceiveMessageType_C2SShowCards   ReceiveMessageType = 3
	ReceiveMessageType_C2SDemandCards ReceiveMessageType = 4
)

var ReceiveMessageType_name = map[int32]string{
	0: "C2SStartID",
	1: "C2SRobBanker",
	2: "C2SBetChips",
	3: "C2SShowCards",
	4: "C2SDemandCards",
}

var ReceiveMessageType_value = map[string]int32{
	"C2SStartID":     0,
	"C2SRobBanker":   1,
	"C2SBetChips":    2,
	"C2SShowCards":   3,
	"C2SDemandCards": 4,
}

func (x ReceiveMessageType) String() string {
	return proto.EnumName(ReceiveMessageType_name, int32(x))
}

func (ReceiveMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{0}
}

// 服务器发送给客户端的消息类型
type SendToClientMessageType int32

const (
	SendToClientMessageType_S2CStartID         SendToClientMessageType = 0
	SendToClientMessageType_S2CGameStatus      SendToClientMessageType = 1
	SendToClientMessageType_S2CSceneMessage    SendToClientMessageType = 2
	SendToClientMessageType_S2CDeal            SendToClientMessageType = 3
	SendToClientMessageType_S2CShowCards       SendToClientMessageType = 4
	SendToClientMessageType_S2CRobBankerInfo   SendToClientMessageType = 5
	SendToClientMessageType_S2CRobBankerResult SendToClientMessageType = 6
	SendToClientMessageType_S2CBetChipsInfo    SendToClientMessageType = 7
	SendToClientMessageType_S2CSettleResult    SendToClientMessageType = 8
	SendToClientMessageType_S2CUserExit        SendToClientMessageType = 9
	SendToClientMessageType_S2CErrRes          SendToClientMessageType = 10
	SendToClientMessageType_S2CUserSitDown     SendToClientMessageType = 11
	SendToClientMessageType_S2CBetMultiple     SendToClientMessageType = 12
)

var SendToClientMessageType_name = map[int32]string{
	0:  "S2CStartID",
	1:  "S2CGameStatus",
	2:  "S2CSceneMessage",
	3:  "S2CDeal",
	4:  "S2CShowCards",
	5:  "S2CRobBankerInfo",
	6:  "S2CRobBankerResult",
	7:  "S2CBetChipsInfo",
	8:  "S2CSettleResult",
	9:  "S2CUserExit",
	10: "S2CErrRes",
	11: "S2CUserSitDown",
	12: "S2CBetMultiple",
}

var SendToClientMessageType_value = map[string]int32{
	"S2CStartID":         0,
	"S2CGameStatus":      1,
	"S2CSceneMessage":    2,
	"S2CDeal":            3,
	"S2CShowCards":       4,
	"S2CRobBankerInfo":   5,
	"S2CRobBankerResult": 6,
	"S2CBetChipsInfo":    7,
	"S2CSettleResult":    8,
	"S2CUserExit":        9,
	"S2CErrRes":          10,
	"S2CUserSitDown":     11,
	"S2CBetMultiple":     12,
}

func (x SendToClientMessageType) String() string {
	return proto.EnumName(SendToClientMessageType_name, int32(x))
}

func (SendToClientMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{1}
}

// 游戏阶段
type GameStatus int32

const (
	GameStatus_GameInitStatus GameStatus = 0
	GameStatus_ReadyStatus    GameStatus = 1
	GameStatus_StartMove      GameStatus = 2
	GameStatus_RobBanker      GameStatus = 3
	GameStatus_EndRob         GameStatus = 4
	GameStatus_BetChips       GameStatus = 5
	GameStatus_EndBet         GameStatus = 6
	GameStatus_ShowChards     GameStatus = 7
	GameStatus_EndShow        GameStatus = 8
	GameStatus_SettleStatus   GameStatus = 9
	GameStatus_GameOver       GameStatus = 10
)

var GameStatus_name = map[int32]string{
	0:  "GameInitStatus",
	1:  "ReadyStatus",
	2:  "StartMove",
	3:  "RobBanker",
	4:  "EndRob",
	5:  "BetChips",
	6:  "EndBet",
	7:  "ShowChards",
	8:  "EndShow",
	9:  "SettleStatus",
	10: "GameOver",
}

var GameStatus_value = map[string]int32{
	"GameInitStatus": 0,
	"ReadyStatus":    1,
	"StartMove":      2,
	"RobBanker":      3,
	"EndRob":         4,
	"BetChips":       5,
	"EndBet":         6,
	"ShowChards":     7,
	"EndShow":        8,
	"SettleStatus":   9,
	"GameOver":       10,
}

func (x GameStatus) String() string {
	return proto.EnumName(GameStatus_name, int32(x))
}

func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{2}
}

// 用户状态
type UserStatus int32

const (
	UserStatus_UserInitStatus UserStatus = 0
	UserStatus_SitDown        UserStatus = 1
	UserStatus_Ready          UserStatus = 2
	UserStatus_RobAction      UserStatus = 3
	UserStatus_BetAction      UserStatus = 4
	UserStatus_ShowedCards    UserStatus = 5
)

var UserStatus_name = map[int32]string{
	0: "UserInitStatus",
	1: "SitDown",
	2: "Ready",
	3: "RobAction",
	4: "BetAction",
	5: "ShowedCards",
}

var UserStatus_value = map[string]int32{
	"UserInitStatus": 0,
	"SitDown":        1,
	"Ready":          2,
	"RobAction":      3,
	"BetAction":      4,
	"ShowedCards":    5,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{3}
}

//玩家操作类型
type AskDoType int32

const (
	AskDoType_NormalType AskDoType = 0
)

var AskDoType_name = map[int32]string{
	0: "NormalType",
}

var AskDoType_value = map[string]int32{
	"NormalType": 0,
}

func (x AskDoType) String() string {
	return proto.EnumName(AskDoType_name, int32(x))
}

func (AskDoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{4}
}

//牌的类型
type CardsType int32

const (
	CardsType_Normal           CardsType = 0
	CardsType_NotNiu           CardsType = 1
	CardsType_NiuOne           CardsType = 2
	CardsType_NiuTwo           CardsType = 3
	CardsType_NiuThree         CardsType = 4
	CardsType_NiuFour          CardsType = 5
	CardsType_NiuFive          CardsType = 6
	CardsType_NiuSix           CardsType = 7
	CardsType_NiuSeven         CardsType = 8
	CardsType_NiuEight         CardsType = 9
	CardsType_NiuNine          CardsType = 10
	CardsType_NiuNiu           CardsType = 11
	CardsType_FourBomb         CardsType = 12
	CardsType_FiveColourfulNiu CardsType = 13
	CardsType_FiveSmallerNiu   CardsType = 14
)

var CardsType_name = map[int32]string{
	0:  "Normal",
	1:  "NotNiu",
	2:  "NiuOne",
	3:  "NiuTwo",
	4:  "NiuThree",
	5:  "NiuFour",
	6:  "NiuFive",
	7:  "NiuSix",
	8:  "NiuSeven",
	9:  "NiuEight",
	10: "NiuNine",
	11: "NiuNiu",
	12: "FourBomb",
	13: "FiveColourfulNiu",
	14: "FiveSmallerNiu",
}

var CardsType_value = map[string]int32{
	"Normal":           0,
	"NotNiu":           1,
	"NiuOne":           2,
	"NiuTwo":           3,
	"NiuThree":         4,
	"NiuFour":          5,
	"NiuFive":          6,
	"NiuSix":           7,
	"NiuSeven":         8,
	"NiuEight":         9,
	"NiuNine":          10,
	"NiuNiu":           11,
	"FourBomb":         12,
	"FiveColourfulNiu": 13,
	"FiveSmallerNiu":   14,
}

func (x CardsType) String() string {
	return proto.EnumName(CardsType_name, int32(x))
}

func (CardsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{5}
}

// 错误列表
type ErrorList int32

const (
	ErrorList_NoError        ErrorList = 0
	ErrorList_ActionTimeOut  ErrorList = 1
	ErrorList_LackOfFunds    ErrorList = 2
	ErrorList_HangUpTip      ErrorList = 3
	ErrorList_LackOfFundsTip ErrorList = 4
)

var ErrorList_name = map[int32]string{
	0: "NoError",
	1: "ActionTimeOut",
	2: "LackOfFunds",
	3: "HangUpTip",
	4: "LackOfFundsTip",
}

var ErrorList_value = map[string]int32{
	"NoError":        0,
	"ActionTimeOut":  1,
	"LackOfFunds":    2,
	"HangUpTip":      3,
	"LackOfFundsTip": 4,
}

func (x ErrorList) String() string {
	return proto.EnumName(ErrorList_name, int32(x))
}

func (ErrorList) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{6}
}

// 游戏状态消息
type StatusMessageRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status"`
	StatusTime           int32    `protobuf:"varint,2,opt,name=StatusTime,proto3" json:"StatusTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessageRes) Reset()         { *m = StatusMessageRes{} }
func (m *StatusMessageRes) String() string { return proto.CompactTextString(m) }
func (*StatusMessageRes) ProtoMessage()    {}
func (*StatusMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{0}
}

func (m *StatusMessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessageRes.Unmarshal(m, b)
}
func (m *StatusMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessageRes.Marshal(b, m, deterministic)
}
func (m *StatusMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessageRes.Merge(m, src)
}
func (m *StatusMessageRes) XXX_Size() int {
	return xxx_messageInfo_StatusMessageRes.Size(m)
}
func (m *StatusMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessageRes proto.InternalMessageInfo

func (m *StatusMessageRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StatusMessageRes) GetStatusTime() int32 {
	if m != nil {
		return m.StatusTime
	}
	return 0
}

//游戏中玩家的数据
type SeatUserInfoRes struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName"`
	Head                 string   `protobuf:"bytes,2,opt,name=Head,proto3" json:"Head"`
	Coin                 int64    `protobuf:"varint,3,opt,name=Coin,proto3" json:"Coin"`
	ChairId              int32    `protobuf:"varint,4,opt,name=ChairId,proto3" json:"ChairId"`
	Cards                []byte   `protobuf:"bytes,5,opt,name=Cards,proto3" json:"Cards"`
	CardsType            int32    `protobuf:"varint,6,opt,name=CardsType,proto3" json:"CardsType"`
	Status               int32    `protobuf:"varint,8,opt,name=Status,proto3" json:"Status"`
	UserId               int64    `protobuf:"varint,9,opt,name=userId,proto3" json:"userId"`
	BetMultiple          int64    `protobuf:"varint,10,opt,name=BetMultiple,proto3" json:"BetMultiple"`
	RobIndex             int32    `protobuf:"varint,11,opt,name=RobIndex,proto3" json:"RobIndex"`
	IsBanker             bool     `protobuf:"varint,12,opt,name=IsBanker,proto3" json:"IsBanker"`
	Address              string   `protobuf:"bytes,13,opt,name=address,proto3" json:"address"`
	CardsIndexs          []int32  `protobuf:"varint,14,rep,packed,name=CardsIndexs,proto3" json:"CardsIndexs"`
	Sex                  int32    `protobuf:"varint,15,opt,name=Sex,proto3" json:"Sex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatUserInfoRes) Reset()         { *m = SeatUserInfoRes{} }
func (m *SeatUserInfoRes) String() string { return proto.CompactTextString(m) }
func (*SeatUserInfoRes) ProtoMessage()    {}
func (*SeatUserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{1}
}

func (m *SeatUserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatUserInfoRes.Unmarshal(m, b)
}
func (m *SeatUserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatUserInfoRes.Marshal(b, m, deterministic)
}
func (m *SeatUserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatUserInfoRes.Merge(m, src)
}
func (m *SeatUserInfoRes) XXX_Size() int {
	return xxx_messageInfo_SeatUserInfoRes.Size(m)
}
func (m *SeatUserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatUserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_SeatUserInfoRes proto.InternalMessageInfo

func (m *SeatUserInfoRes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SeatUserInfoRes) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *SeatUserInfoRes) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *SeatUserInfoRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *SeatUserInfoRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SeatUserInfoRes) GetCardsType() int32 {
	if m != nil {
		return m.CardsType
	}
	return 0
}

func (m *SeatUserInfoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SeatUserInfoRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SeatUserInfoRes) GetBetMultiple() int64 {
	if m != nil {
		return m.BetMultiple
	}
	return 0
}

func (m *SeatUserInfoRes) GetRobIndex() int32 {
	if m != nil {
		return m.RobIndex
	}
	return 0
}

func (m *SeatUserInfoRes) GetIsBanker() bool {
	if m != nil {
		return m.IsBanker
	}
	return false
}

func (m *SeatUserInfoRes) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SeatUserInfoRes) GetCardsIndexs() []int32 {
	if m != nil {
		return m.CardsIndexs
	}
	return nil
}

func (m *SeatUserInfoRes) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 场景消息
type SceneMessageRes struct {
	UserData             []*SeatUserInfoRes `protobuf:"bytes,1,rep,name=UserData,proto3" json:"UserData"`
	GameStatus           int32              `protobuf:"varint,2,opt,name=GameStatus,proto3" json:"GameStatus"`
	StatusTimeLeft       int64              `protobuf:"varint,3,opt,name=StatusTimeLeft,proto3" json:"StatusTimeLeft"`
	RoomCost             int64              `protobuf:"varint,4,opt,name=RoomCost,proto3" json:"RoomCost"`
	MinLimit             int64              `protobuf:"varint,5,opt,name=MinLimit,proto3" json:"MinLimit"`
	RobIndexs            []int64            `protobuf:"varint,7,rep,packed,name=RobIndexs,proto3" json:"RobIndexs"`
	Reconnect            bool               `protobuf:"varint,8,opt,name=Reconnect,proto3" json:"Reconnect"`
	RoomID               int64              `protobuf:"varint,9,opt,name=RoomID,proto3" json:"RoomID"`
	BetMultiple          *BetMultipleRes    `protobuf:"bytes,10,opt,name=BetMultiple,proto3" json:"BetMultiple"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SceneMessageRes) Reset()         { *m = SceneMessageRes{} }
func (m *SceneMessageRes) String() string { return proto.CompactTextString(m) }
func (*SceneMessageRes) ProtoMessage()    {}
func (*SceneMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{2}
}

func (m *SceneMessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneMessageRes.Unmarshal(m, b)
}
func (m *SceneMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneMessageRes.Marshal(b, m, deterministic)
}
func (m *SceneMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneMessageRes.Merge(m, src)
}
func (m *SceneMessageRes) XXX_Size() int {
	return xxx_messageInfo_SceneMessageRes.Size(m)
}
func (m *SceneMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_SceneMessageRes proto.InternalMessageInfo

func (m *SceneMessageRes) GetUserData() []*SeatUserInfoRes {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *SceneMessageRes) GetGameStatus() int32 {
	if m != nil {
		return m.GameStatus
	}
	return 0
}

func (m *SceneMessageRes) GetStatusTimeLeft() int64 {
	if m != nil {
		return m.StatusTimeLeft
	}
	return 0
}

func (m *SceneMessageRes) GetRoomCost() int64 {
	if m != nil {
		return m.RoomCost
	}
	return 0
}

func (m *SceneMessageRes) GetMinLimit() int64 {
	if m != nil {
		return m.MinLimit
	}
	return 0
}

func (m *SceneMessageRes) GetRobIndexs() []int64 {
	if m != nil {
		return m.RobIndexs
	}
	return nil
}

func (m *SceneMessageRes) GetReconnect() bool {
	if m != nil {
		return m.Reconnect
	}
	return false
}

func (m *SceneMessageRes) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SceneMessageRes) GetBetMultiple() *BetMultipleRes {
	if m != nil {
		return m.BetMultiple
	}
	return nil
}

// 给单个用户的发牌信息
type DealRes struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,3,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealRes) Reset()         { *m = DealRes{} }
func (m *DealRes) String() string { return proto.CompactTextString(m) }
func (*DealRes) ProtoMessage()    {}
func (*DealRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{3}
}

func (m *DealRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealRes.Unmarshal(m, b)
}
func (m *DealRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealRes.Marshal(b, m, deterministic)
}
func (m *DealRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealRes.Merge(m, src)
}
func (m *DealRes) XXX_Size() int {
	return xxx_messageInfo_DealRes.Size(m)
}
func (m *DealRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DealRes.DiscardUnknown(m)
}

var xxx_messageInfo_DealRes proto.InternalMessageInfo

func (m *DealRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *DealRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DealRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 广播摊派信息发牌信息
type ShowCardsRes struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,3,opt,name=ChairId,proto3" json:"ChairId"`
	CardsType            int32    `protobuf:"varint,4,opt,name=CardsType,proto3" json:"CardsType"`
	CardsIndexs          []int32  `protobuf:"varint,5,rep,packed,name=CardsIndexs,proto3" json:"CardsIndexs"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowCardsRes) Reset()         { *m = ShowCardsRes{} }
func (m *ShowCardsRes) String() string { return proto.CompactTextString(m) }
func (*ShowCardsRes) ProtoMessage()    {}
func (*ShowCardsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{4}
}

func (m *ShowCardsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCardsRes.Unmarshal(m, b)
}
func (m *ShowCardsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCardsRes.Marshal(b, m, deterministic)
}
func (m *ShowCardsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCardsRes.Merge(m, src)
}
func (m *ShowCardsRes) XXX_Size() int {
	return xxx_messageInfo_ShowCardsRes.Size(m)
}
func (m *ShowCardsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCardsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCardsRes proto.InternalMessageInfo

func (m *ShowCardsRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *ShowCardsRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ShowCardsRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *ShowCardsRes) GetCardsType() int32 {
	if m != nil {
		return m.CardsType
	}
	return 0
}

func (m *ShowCardsRes) GetCardsIndexs() []int32 {
	if m != nil {
		return m.CardsIndexs
	}
	return nil
}

// 广播用户抢庄信息
type RobBankerInfoRes struct {
	RobIndex             int32    `protobuf:"varint,1,opt,name=RobIndex,proto3" json:"RobIndex"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,3,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobBankerInfoRes) Reset()         { *m = RobBankerInfoRes{} }
func (m *RobBankerInfoRes) String() string { return proto.CompactTextString(m) }
func (*RobBankerInfoRes) ProtoMessage()    {}
func (*RobBankerInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{5}
}

func (m *RobBankerInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobBankerInfoRes.Unmarshal(m, b)
}
func (m *RobBankerInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobBankerInfoRes.Marshal(b, m, deterministic)
}
func (m *RobBankerInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobBankerInfoRes.Merge(m, src)
}
func (m *RobBankerInfoRes) XXX_Size() int {
	return xxx_messageInfo_RobBankerInfoRes.Size(m)
}
func (m *RobBankerInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RobBankerInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_RobBankerInfoRes proto.InternalMessageInfo

func (m *RobBankerInfoRes) GetRobIndex() int32 {
	if m != nil {
		return m.RobIndex
	}
	return 0
}

func (m *RobBankerInfoRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RobBankerInfoRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 广播抢庄结果
type RobBankerResultRes struct {
	RobIndex             int32    `protobuf:"varint,1,opt,name=RobIndex,proto3" json:"RobIndex"`
	Candidates           []int32  `protobuf:"varint,2,rep,packed,name=Candidates,proto3" json:"Candidates"`
	BankerChairId        int32    `protobuf:"varint,3,opt,name=BankerChairId,proto3" json:"BankerChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobBankerResultRes) Reset()         { *m = RobBankerResultRes{} }
func (m *RobBankerResultRes) String() string { return proto.CompactTextString(m) }
func (*RobBankerResultRes) ProtoMessage()    {}
func (*RobBankerResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{6}
}

func (m *RobBankerResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobBankerResultRes.Unmarshal(m, b)
}
func (m *RobBankerResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobBankerResultRes.Marshal(b, m, deterministic)
}
func (m *RobBankerResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobBankerResultRes.Merge(m, src)
}
func (m *RobBankerResultRes) XXX_Size() int {
	return xxx_messageInfo_RobBankerResultRes.Size(m)
}
func (m *RobBankerResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RobBankerResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_RobBankerResultRes proto.InternalMessageInfo

func (m *RobBankerResultRes) GetRobIndex() int32 {
	if m != nil {
		return m.RobIndex
	}
	return 0
}

func (m *RobBankerResultRes) GetCandidates() []int32 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *RobBankerResultRes) GetBankerChairId() int32 {
	if m != nil {
		return m.BankerChairId
	}
	return 0
}

// 广播用户投注信息
type BetChipsInfoRes struct {
	BetMultiple          int64    `protobuf:"varint,1,opt,name=BetMultiple,proto3" json:"BetMultiple"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,3,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetChipsInfoRes) Reset()         { *m = BetChipsInfoRes{} }
func (m *BetChipsInfoRes) String() string { return proto.CompactTextString(m) }
func (*BetChipsInfoRes) ProtoMessage()    {}
func (*BetChipsInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{7}
}

func (m *BetChipsInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetChipsInfoRes.Unmarshal(m, b)
}
func (m *BetChipsInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetChipsInfoRes.Marshal(b, m, deterministic)
}
func (m *BetChipsInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetChipsInfoRes.Merge(m, src)
}
func (m *BetChipsInfoRes) XXX_Size() int {
	return xxx_messageInfo_BetChipsInfoRes.Size(m)
}
func (m *BetChipsInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BetChipsInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_BetChipsInfoRes proto.InternalMessageInfo

func (m *BetChipsInfoRes) GetBetMultiple() int64 {
	if m != nil {
		return m.BetMultiple
	}
	return 0
}

func (m *BetChipsInfoRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BetChipsInfoRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 结算结果
type SettleResult struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	Result               int64    `protobuf:"varint,3,opt,name=Result,proto3" json:"Result"`
	IsBanker             bool     `protobuf:"varint,4,opt,name=IsBanker,proto3" json:"IsBanker"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleResult) Reset()         { *m = SettleResult{} }
func (m *SettleResult) String() string { return proto.CompactTextString(m) }
func (*SettleResult) ProtoMessage()    {}
func (*SettleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{8}
}

func (m *SettleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleResult.Unmarshal(m, b)
}
func (m *SettleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleResult.Marshal(b, m, deterministic)
}
func (m *SettleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleResult.Merge(m, src)
}
func (m *SettleResult) XXX_Size() int {
	return xxx_messageInfo_SettleResult.Size(m)
}
func (m *SettleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleResult.DiscardUnknown(m)
}

var xxx_messageInfo_SettleResult proto.InternalMessageInfo

func (m *SettleResult) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SettleResult) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *SettleResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SettleResult) GetIsBanker() bool {
	if m != nil {
		return m.IsBanker
	}
	return false
}

// 广播结算结果列表
type SettleResultRes struct {
	ResultList           []*SettleResult `protobuf:"bytes,1,rep,name=ResultList,proto3" json:"ResultList"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SettleResultRes) Reset()         { *m = SettleResultRes{} }
func (m *SettleResultRes) String() string { return proto.CompactTextString(m) }
func (*SettleResultRes) ProtoMessage()    {}
func (*SettleResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{9}
}

func (m *SettleResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleResultRes.Unmarshal(m, b)
}
func (m *SettleResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleResultRes.Marshal(b, m, deterministic)
}
func (m *SettleResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleResultRes.Merge(m, src)
}
func (m *SettleResultRes) XXX_Size() int {
	return xxx_messageInfo_SettleResultRes.Size(m)
}
func (m *SettleResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_SettleResultRes proto.InternalMessageInfo

func (m *SettleResultRes) GetResultList() []*SettleResult {
	if m != nil {
		return m.ResultList
	}
	return nil
}

// 广播用户退出信息
type UserExitRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	MsgNum               int32    `protobuf:"varint,3,opt,name=MsgNum,proto3" json:"MsgNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExitRes) Reset()         { *m = UserExitRes{} }
func (m *UserExitRes) String() string { return proto.CompactTextString(m) }
func (*UserExitRes) ProtoMessage()    {}
func (*UserExitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{10}
}

func (m *UserExitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExitRes.Unmarshal(m, b)
}
func (m *UserExitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExitRes.Marshal(b, m, deterministic)
}
func (m *UserExitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExitRes.Merge(m, src)
}
func (m *UserExitRes) XXX_Size() int {
	return xxx_messageInfo_UserExitRes.Size(m)
}
func (m *UserExitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExitRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserExitRes proto.InternalMessageInfo

func (m *UserExitRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserExitRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *UserExitRes) GetMsgNum() int32 {
	if m != nil {
		return m.MsgNum
	}
	return 0
}

// 错误信息响应
type ErrRes struct {
	ErrNum               int32    `protobuf:"varint,1,opt,name=errNum,proto3" json:"errNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrRes) Reset()         { *m = ErrRes{} }
func (m *ErrRes) String() string { return proto.CompactTextString(m) }
func (*ErrRes) ProtoMessage()    {}
func (*ErrRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{11}
}

func (m *ErrRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrRes.Unmarshal(m, b)
}
func (m *ErrRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrRes.Marshal(b, m, deterministic)
}
func (m *ErrRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrRes.Merge(m, src)
}
func (m *ErrRes) XXX_Size() int {
	return xxx_messageInfo_ErrRes.Size(m)
}
func (m *ErrRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrRes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrRes proto.InternalMessageInfo

func (m *ErrRes) GetErrNum() int32 {
	if m != nil {
		return m.ErrNum
	}
	return 0
}

// 广播用户坐下信息
type UserSitDownRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	UserName             string   `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName"`
	Head                 string   `protobuf:"bytes,4,opt,name=Head,proto3" json:"Head"`
	Coin                 int64    `protobuf:"varint,5,opt,name=Coin,proto3" json:"Coin"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	Sex                  int32    `protobuf:"varint,7,opt,name=Sex,proto3" json:"Sex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSitDownRes) Reset()         { *m = UserSitDownRes{} }
func (m *UserSitDownRes) String() string { return proto.CompactTextString(m) }
func (*UserSitDownRes) ProtoMessage()    {}
func (*UserSitDownRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{12}
}

func (m *UserSitDownRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSitDownRes.Unmarshal(m, b)
}
func (m *UserSitDownRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSitDownRes.Marshal(b, m, deterministic)
}
func (m *UserSitDownRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSitDownRes.Merge(m, src)
}
func (m *UserSitDownRes) XXX_Size() int {
	return xxx_messageInfo_UserSitDownRes.Size(m)
}
func (m *UserSitDownRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSitDownRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserSitDownRes proto.InternalMessageInfo

func (m *UserSitDownRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserSitDownRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *UserSitDownRes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserSitDownRes) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UserSitDownRes) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserSitDownRes) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserSitDownRes) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 投注倍率
type BetMultipleRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	Multiples            []int64  `protobuf:"varint,3,rep,packed,name=Multiples,proto3" json:"Multiples"`
	HighestMultiple      int64    `protobuf:"varint,4,opt,name=highestMultiple,proto3" json:"highestMultiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetMultipleRes) Reset()         { *m = BetMultipleRes{} }
func (m *BetMultipleRes) String() string { return proto.CompactTextString(m) }
func (*BetMultipleRes) ProtoMessage()    {}
func (*BetMultipleRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{13}
}

func (m *BetMultipleRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetMultipleRes.Unmarshal(m, b)
}
func (m *BetMultipleRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetMultipleRes.Marshal(b, m, deterministic)
}
func (m *BetMultipleRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetMultipleRes.Merge(m, src)
}
func (m *BetMultipleRes) XXX_Size() int {
	return xxx_messageInfo_BetMultipleRes.Size(m)
}
func (m *BetMultipleRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BetMultipleRes.DiscardUnknown(m)
}

var xxx_messageInfo_BetMultipleRes proto.InternalMessageInfo

func (m *BetMultipleRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BetMultipleRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *BetMultipleRes) GetMultiples() []int64 {
	if m != nil {
		return m.Multiples
	}
	return nil
}

func (m *BetMultipleRes) GetHighestMultiple() int64 {
	if m != nil {
		return m.HighestMultiple
	}
	return 0
}

// 抢庄请求
type RobBankerReq struct {
	RobIndex             int32    `protobuf:"varint,1,opt,name=RobIndex,proto3" json:"RobIndex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobBankerReq) Reset()         { *m = RobBankerReq{} }
func (m *RobBankerReq) String() string { return proto.CompactTextString(m) }
func (*RobBankerReq) ProtoMessage()    {}
func (*RobBankerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{14}
}

func (m *RobBankerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobBankerReq.Unmarshal(m, b)
}
func (m *RobBankerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobBankerReq.Marshal(b, m, deterministic)
}
func (m *RobBankerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobBankerReq.Merge(m, src)
}
func (m *RobBankerReq) XXX_Size() int {
	return xxx_messageInfo_RobBankerReq.Size(m)
}
func (m *RobBankerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RobBankerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RobBankerReq proto.InternalMessageInfo

func (m *RobBankerReq) GetRobIndex() int32 {
	if m != nil {
		return m.RobIndex
	}
	return 0
}

// 投注请求
type BetChipsReq struct {
	BetMultiple          int64    `protobuf:"varint,1,opt,name=BetMultiple,proto3" json:"BetMultiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetChipsReq) Reset()         { *m = BetChipsReq{} }
func (m *BetChipsReq) String() string { return proto.CompactTextString(m) }
func (*BetChipsReq) ProtoMessage()    {}
func (*BetChipsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{15}
}

func (m *BetChipsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetChipsReq.Unmarshal(m, b)
}
func (m *BetChipsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetChipsReq.Marshal(b, m, deterministic)
}
func (m *BetChipsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetChipsReq.Merge(m, src)
}
func (m *BetChipsReq) XXX_Size() int {
	return xxx_messageInfo_BetChipsReq.Size(m)
}
func (m *BetChipsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BetChipsReq.DiscardUnknown(m)
}

var xxx_messageInfo_BetChipsReq proto.InternalMessageInfo

func (m *BetChipsReq) GetBetMultiple() int64 {
	if m != nil {
		return m.BetMultiple
	}
	return 0
}

// 摊派请求
type ShowCardsReq struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowCardsReq) Reset()         { *m = ShowCardsReq{} }
func (m *ShowCardsReq) String() string { return proto.CompactTextString(m) }
func (*ShowCardsReq) ProtoMessage()    {}
func (*ShowCardsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{16}
}

func (m *ShowCardsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCardsReq.Unmarshal(m, b)
}
func (m *ShowCardsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCardsReq.Marshal(b, m, deterministic)
}
func (m *ShowCardsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCardsReq.Merge(m, src)
}
func (m *ShowCardsReq) XXX_Size() int {
	return xxx_messageInfo_ShowCardsReq.Size(m)
}
func (m *ShowCardsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCardsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCardsReq proto.InternalMessageInfo

func (m *ShowCardsReq) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

// 要牌请求
type DemandCardsReq struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemandCardsReq) Reset()         { *m = DemandCardsReq{} }
func (m *DemandCardsReq) String() string { return proto.CompactTextString(m) }
func (*DemandCardsReq) ProtoMessage()    {}
func (*DemandCardsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b17b89c07d6f10, []int{17}
}

func (m *DemandCardsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemandCardsReq.Unmarshal(m, b)
}
func (m *DemandCardsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemandCardsReq.Marshal(b, m, deterministic)
}
func (m *DemandCardsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemandCardsReq.Merge(m, src)
}
func (m *DemandCardsReq) XXX_Size() int {
	return xxx_messageInfo_DemandCardsReq.Size(m)
}
func (m *DemandCardsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DemandCardsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DemandCardsReq proto.InternalMessageInfo

func (m *DemandCardsReq) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterEnum("msg.ReceiveMessageType", ReceiveMessageType_name, ReceiveMessageType_value)
	proto.RegisterEnum("msg.SendToClientMessageType", SendToClientMessageType_name, SendToClientMessageType_value)
	proto.RegisterEnum("msg.GameStatus", GameStatus_name, GameStatus_value)
	proto.RegisterEnum("msg.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("msg.AskDoType", AskDoType_name, AskDoType_value)
	proto.RegisterEnum("msg.CardsType", CardsType_name, CardsType_value)
	proto.RegisterEnum("msg.ErrorList", ErrorList_name, ErrorList_value)
	proto.RegisterType((*StatusMessageRes)(nil), "msg.StatusMessageRes")
	proto.RegisterType((*SeatUserInfoRes)(nil), "msg.SeatUserInfoRes")
	proto.RegisterType((*SceneMessageRes)(nil), "msg.SceneMessageRes")
	proto.RegisterType((*DealRes)(nil), "msg.DealRes")
	proto.RegisterType((*ShowCardsRes)(nil), "msg.ShowCardsRes")
	proto.RegisterType((*RobBankerInfoRes)(nil), "msg.RobBankerInfoRes")
	proto.RegisterType((*RobBankerResultRes)(nil), "msg.RobBankerResultRes")
	proto.RegisterType((*BetChipsInfoRes)(nil), "msg.BetChipsInfoRes")
	proto.RegisterType((*SettleResult)(nil), "msg.SettleResult")
	proto.RegisterType((*SettleResultRes)(nil), "msg.SettleResultRes")
	proto.RegisterType((*UserExitRes)(nil), "msg.UserExitRes")
	proto.RegisterType((*ErrRes)(nil), "msg.ErrRes")
	proto.RegisterType((*UserSitDownRes)(nil), "msg.UserSitDownRes")
	proto.RegisterType((*BetMultipleRes)(nil), "msg.BetMultipleRes")
	proto.RegisterType((*RobBankerReq)(nil), "msg.RobBankerReq")
	proto.RegisterType((*BetChipsReq)(nil), "msg.BetChipsReq")
	proto.RegisterType((*ShowCardsReq)(nil), "msg.ShowCardsReq")
	proto.RegisterType((*DemandCardsReq)(nil), "msg.DemandCardsReq")
}

func init() { proto.RegisterFile("watch_banker.proto", fileDescriptor_c9b17b89c07d6f10) }

var fileDescriptor_c9b17b89c07d6f10 = []byte{
	// 1275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6e, 0xdb, 0x46,
	0x17, 0x36, 0x45, 0x5d, 0x8f, 0x64, 0x79, 0x32, 0x09, 0xf2, 0x13, 0x7f, 0x83, 0x40, 0x20, 0x8a,
	0x40, 0xd0, 0x43, 0xda, 0xb2, 0xe8, 0x02, 0x62, 0xca, 0x69, 0x54, 0xf8, 0x82, 0x92, 0x0e, 0xfa,
	0x98, 0xd2, 0xe2, 0x58, 0x1a, 0x58, 0xe4, 0x38, 0xe4, 0xd0, 0x76, 0xb6, 0xd0, 0xa7, 0x3e, 0x75,
	0x21, 0x59, 0x48, 0x57, 0xd0, 0x9d, 0xf4, 0xa5, 0x38, 0xc3, 0x21, 0x35, 0x54, 0x92, 0x06, 0x0e,
	0xfa, 0x36, 0xdf, 0x99, 0xc3, 0x73, 0xf9, 0xce, 0x65, 0x24, 0xa0, 0xb7, 0x91, 0x5c, 0xae, 0xdf,
	0x5c, 0x44, 0xe9, 0x15, 0xcb, 0x9e, 0x5f, 0x67, 0x42, 0x0a, 0x6a, 0x27, 0xf9, 0xca, 0xfd, 0x09,
	0x48, 0x28, 0x23, 0x59, 0xe4, 0x27, 0x2c, 0xcf, 0xa3, 0x15, 0x0b, 0x58, 0x4e, 0x1f, 0x43, 0xb7,
	0x94, 0x39, 0xd6, 0xc4, 0x9a, 0x76, 0x02, 0x8d, 0xe8, 0x53, 0x80, 0xf2, 0x74, 0xce, 0x13, 0xe6,
	0xb4, 0xd4, 0x9d, 0x21, 0x71, 0xff, 0x6e, 0xc1, 0x41, 0xc8, 0x22, 0xf9, 0x3a, 0x67, 0xd9, 0x22,
	0xbd, 0x14, 0x68, 0xeb, 0xff, 0xd0, 0x47, 0x78, 0x1a, 0x25, 0x4c, 0x59, 0x1b, 0x04, 0x35, 0xa6,
	0x14, 0xda, 0xaf, 0x58, 0x14, 0x2b, 0x4b, 0x83, 0x40, 0x9d, 0x51, 0xe6, 0x0b, 0x9e, 0x3a, 0xf6,
	0xc4, 0x9a, 0xda, 0x81, 0x3a, 0x53, 0x07, 0x7a, 0xfe, 0x3a, 0xe2, 0xd9, 0x22, 0x76, 0xda, 0xca,
	0x69, 0x05, 0xe9, 0x23, 0xe8, 0xf8, 0x51, 0x16, 0xe7, 0x4e, 0x67, 0x62, 0x4d, 0x47, 0x41, 0x09,
	0xe8, 0x13, 0x18, 0xa8, 0xc3, 0xf9, 0xbb, 0x6b, 0xe6, 0x74, 0xd5, 0x17, 0x5b, 0x81, 0x91, 0x5d,
	0xbf, 0x91, 0xdd, 0x63, 0xe8, 0x16, 0x18, 0x78, 0xec, 0x0c, 0x94, 0x6f, 0x8d, 0xe8, 0x04, 0x86,
	0x87, 0x4c, 0x9e, 0x14, 0x1b, 0xc9, 0xaf, 0x37, 0xcc, 0x01, 0x75, 0x69, 0x8a, 0x30, 0xc7, 0x40,
	0x5c, 0x2c, 0xd2, 0x98, 0xdd, 0x39, 0x43, 0x65, 0xb3, 0xc6, 0x78, 0xb7, 0xc8, 0x0f, 0x15, 0xed,
	0xce, 0x68, 0x62, 0x4d, 0xfb, 0x41, 0x8d, 0x31, 0xaf, 0x28, 0x8e, 0x33, 0x96, 0xe7, 0xce, 0xbe,
	0xa2, 0xa0, 0x82, 0xe8, 0x53, 0x05, 0xac, 0x6c, 0xe4, 0xce, 0x78, 0x62, 0x4f, 0x3b, 0x81, 0x29,
	0xa2, 0x04, 0xec, 0x90, 0xdd, 0x39, 0x07, 0xca, 0x1d, 0x1e, 0xdd, 0x3f, 0x91, 0xfd, 0x25, 0x4b,
	0x99, 0x51, 0xc9, 0x6f, 0x4b, 0xf6, 0xe7, 0x91, 0x8c, 0x1c, 0x6b, 0x62, 0x4f, 0x87, 0xde, 0xa3,
	0xe7, 0x49, 0xbe, 0x7a, 0xbe, 0x53, 0xa5, 0xa0, 0xd6, 0xc2, 0x1a, 0xff, 0x18, 0x25, 0x4c, 0x33,
	0xa4, 0x6b, 0xbc, 0x95, 0xd0, 0x67, 0x30, 0xde, 0x56, 0xfc, 0x98, 0x5d, 0x4a, 0x5d, 0xa9, 0x1d,
	0x69, 0xc9, 0x89, 0x48, 0x7c, 0x91, 0x4b, 0x55, 0x34, 0x3b, 0xa8, 0x31, 0xde, 0x9d, 0xf0, 0xf4,
	0x98, 0x27, 0x5c, 0xaa, 0xc2, 0xd9, 0x41, 0x8d, 0xb1, 0x76, 0x15, 0x77, 0xb9, 0xd3, 0x9b, 0xd8,
	0x53, 0x3b, 0xd8, 0x0a, 0xd4, 0x2d, 0x5b, 0x8a, 0x34, 0x65, 0x4b, 0xa9, 0xca, 0xd7, 0x0f, 0xb6,
	0x02, 0xac, 0x20, 0xfa, 0x58, 0xcc, 0xab, 0x0a, 0x96, 0x88, 0xfe, 0xf0, 0x61, 0x05, 0x87, 0xde,
	0x43, 0x45, 0x84, 0x21, 0x47, 0x1e, 0x4c, 0x3d, 0xf7, 0x67, 0xe8, 0xcd, 0x59, 0xb4, 0x41, 0x1e,
	0xeb, 0x3e, 0xb3, 0xcc, 0x3e, 0xdb, 0x76, 0x4c, 0xab, 0xd1, 0x31, 0x46, 0xbf, 0xda, 0x8d, 0x7e,
	0x75, 0xff, 0xb0, 0x60, 0x14, 0xae, 0xc5, 0xad, 0xfa, 0xfe, 0x3f, 0x34, 0xdc, 0x6c, 0xf9, 0xf6,
	0x6e, 0xcb, 0xef, 0xb4, 0x53, 0xe7, 0x83, 0x76, 0x72, 0x7f, 0x05, 0x12, 0x88, 0x8b, 0xb2, 0x2f,
	0x8d, 0xd1, 0xad, 0xdb, 0xda, 0xda, 0x69, 0xeb, 0xfb, 0xa7, 0x7e, 0x03, 0xb4, 0xf6, 0x10, 0xb0,
	0xbc, 0xd8, 0xc8, 0xcf, 0xf9, 0x78, 0x0a, 0xe0, 0x47, 0x69, 0xcc, 0xe3, 0x48, 0x32, 0x6c, 0x45,
	0x0c, 0xda, 0x90, 0xd0, 0xaf, 0x61, 0xbf, 0x34, 0xd7, 0xf4, 0xd8, 0x14, 0xba, 0x0c, 0x0e, 0x0e,
	0x99, 0xf4, 0xd7, 0xfc, 0x3a, 0xaf, 0x12, 0xdb, 0x99, 0x68, 0xeb, 0xc3, 0x89, 0xbe, 0x7f, 0x7a,
	0x12, 0x46, 0x21, 0x93, 0x52, 0xb5, 0x51, 0xb1, 0x91, 0x86, 0x05, 0xeb, 0x53, 0x16, 0x5a, 0xcd,
	0x12, 0x62, 0xf7, 0xaa, 0x6f, 0xf5, 0x44, 0x69, 0xd4, 0xd8, 0x20, 0xed, 0xe6, 0x06, 0x71, 0xe7,
	0xb8, 0x70, 0xb7, 0x5e, 0x31, 0xb9, 0xef, 0x00, 0x4a, 0x70, 0xcc, 0x73, 0xa9, 0x87, 0xfe, 0x81,
	0x1e, 0x7a, 0x43, 0xd3, 0x50, 0x72, 0x7f, 0x81, 0x21, 0xce, 0xff, 0xd1, 0x1d, 0x97, 0x7a, 0xfd,
	0xdf, 0x3f, 0xf4, 0x93, 0x7c, 0x75, 0x5a, 0x24, 0x9a, 0x15, 0x8d, 0xdc, 0x09, 0x74, 0x8f, 0xb2,
	0x4c, 0xdb, 0x64, 0x59, 0x86, 0x1a, 0xfa, 0x49, 0x29, 0x91, 0xfb, 0xde, 0x82, 0x31, 0xfa, 0x0e,
	0xb9, 0x9c, 0x8b, 0xdb, 0xf4, 0xcb, 0xdc, 0x9b, 0x6f, 0x8c, 0xfd, 0x89, 0x37, 0xa6, 0xfd, 0x91,
	0x37, 0xa6, 0xd3, 0x7c, 0x63, 0xaa, 0x5d, 0xdc, 0x6d, 0xee, 0x62, 0xbd, 0x69, 0x7b, 0xdb, 0x4d,
	0xfb, 0x9b, 0x05, 0xe3, 0xe6, 0xe2, 0xf8, 0x82, 0xa0, 0x9f, 0xc0, 0xa0, 0x32, 0x90, 0x3b, 0x76,
	0xb9, 0xe8, 0x6a, 0x01, 0x9d, 0xc2, 0xc1, 0x9a, 0xaf, 0xd6, 0x2c, 0xdf, 0xb6, 0x69, 0xb9, 0x45,
	0x77, 0xc5, 0xee, 0x0c, 0x46, 0xc6, 0x5c, 0xbd, 0xfd, 0xb7, 0x89, 0x72, 0xbf, 0x51, 0x8d, 0xaf,
	0x66, 0x01, 0x55, 0x3f, 0x3b, 0x07, 0xee, 0xd3, 0xc6, 0xba, 0x7a, 0x4b, 0xc7, 0xd0, 0x12, 0x57,
	0x4a, 0xb1, 0x1f, 0xb4, 0xc4, 0x95, 0xfb, 0x0c, 0xc6, 0x73, 0x96, 0x44, 0x69, 0x5c, 0x6b, 0x7c,
	0x74, 0xa1, 0xcd, 0x12, 0xa0, 0x01, 0x5b, 0x32, 0x7e, 0x53, 0x3d, 0x4e, 0x6a, 0x2d, 0x8d, 0x01,
	0x7c, 0x2f, 0x0c, 0x65, 0x94, 0xc9, 0xc5, 0x9c, 0xec, 0x51, 0x02, 0x23, 0xdf, 0x0b, 0xeb, 0x6c,
	0x88, 0x45, 0x0f, 0x60, 0xe8, 0x7b, 0x61, 0x15, 0x33, 0x69, 0x69, 0x95, 0x3a, 0x26, 0x62, 0x53,
	0x0a, 0x63, 0xdf, 0x0b, 0x8d, 0x28, 0x48, 0x7b, 0xf6, 0x7b, 0x0b, 0xfe, 0x17, 0xb2, 0x34, 0x3e,
	0x17, 0xfe, 0x86, 0xb3, 0x54, 0xee, 0x38, 0x0d, 0x3d, 0x7f, 0xeb, 0xf4, 0x01, 0xec, 0x87, 0x9e,
	0xbf, 0x7d, 0xe1, 0x88, 0x45, 0x1f, 0xc2, 0x01, 0xaa, 0x18, 0x6f, 0x29, 0x69, 0xd1, 0x21, 0xf4,
	0x42, 0xcf, 0xc7, 0x07, 0x81, 0xd8, 0x18, 0x06, 0x6a, 0xd4, 0x61, 0xb4, 0xe9, 0x23, 0x20, 0xa1,
	0xe7, 0x37, 0x76, 0x28, 0xe9, 0xd0, 0xc7, 0x40, 0x4d, 0x69, 0x39, 0x73, 0xa4, 0xab, 0x3d, 0x98,
	0x7b, 0x89, 0xf4, 0x2a, 0xb7, 0xc6, 0x94, 0x92, 0x3e, 0x32, 0x10, 0x7a, 0x7e, 0x35, 0x9e, 0x64,
	0x40, 0xf7, 0x61, 0x10, 0x7a, 0x7e, 0x39, 0x56, 0x04, 0x30, 0x7d, 0x7d, 0xaf, 0x47, 0x88, 0x0c,
	0xb5, 0xcc, 0xa8, 0x23, 0x19, 0xcd, 0xde, 0x5b, 0xe6, 0xc3, 0x8e, 0x2a, 0x88, 0x16, 0x29, 0x97,
	0x3a, 0xed, 0x3d, 0x74, 0x15, 0xb0, 0x28, 0x7e, 0x57, 0xf3, 0x80, 0xae, 0x90, 0xa7, 0x13, 0x71,
	0x83, 0x0c, 0xec, 0xab, 0xa7, 0x59, 0xd7, 0xc6, 0xa6, 0x00, 0xdd, 0xa3, 0x34, 0x0e, 0xc4, 0x05,
	0x69, 0xd3, 0x11, 0xf4, 0xeb, 0x22, 0x75, 0xf4, 0xcd, 0x21, 0xc3, 0x4c, 0x91, 0x6e, 0xa4, 0x69,
	0xad, 0x78, 0xea, 0x21, 0x8d, 0x47, 0x69, 0x8c, 0x22, 0xd2, 0x57, 0x34, 0xaa, 0x74, 0xb5, 0xcb,
	0x01, 0x1a, 0xc2, 0xb8, 0xce, 0x6e, 0x58, 0x46, 0x60, 0xb6, 0x02, 0x50, 0x99, 0xd5, 0x31, 0x97,
	0xbf, 0x59, 0x8c, 0x98, 0xb1, 0x2a, 0x3a, 0x6f, 0x8b, 0x0e, 0xa0, 0xa3, 0x12, 0xa8, 0x63, 0x7d,
	0xb1, 0x94, 0x5c, 0xa4, 0xc4, 0x46, 0x78, 0xc8, 0xa4, 0x86, 0x6d, 0x45, 0xea, 0x5a, 0xdc, 0x32,
	0xdd, 0x30, 0x9d, 0xd9, 0x57, 0x30, 0x78, 0x91, 0x5f, 0xcd, 0x45, 0xd5, 0x21, 0xa7, 0x22, 0x4b,
	0xa2, 0x0d, 0x22, 0xb2, 0x37, 0xfb, 0xcb, 0x32, 0x1e, 0x57, 0x4c, 0xae, 0xbc, 0x25, 0x7b, 0xe5,
	0x59, 0x9e, 0xf2, 0x82, 0x58, 0xea, 0xcc, 0x8b, 0xb3, 0x14, 0x99, 0x2a, 0xcf, 0xe7, 0xb7, 0x82,
	0xd8, 0x98, 0x11, 0x9e, 0xd7, 0x19, 0x63, 0xa4, 0x8d, 0xf1, 0x9e, 0xf2, 0xe2, 0xa5, 0x28, 0x32,
	0xd2, 0xa9, 0x00, 0xbf, 0x61, 0xa4, 0xab, 0xbf, 0x09, 0xf9, 0x1d, 0xe9, 0xe9, 0x6f, 0x42, 0x76,
	0xc3, 0x52, 0xd2, 0xd7, 0xe8, 0x88, 0xaf, 0xd6, 0x58, 0xff, 0xf2, 0xa3, 0x53, 0x9e, 0x32, 0x02,
	0xfa, 0x23, 0x0c, 0x60, 0x88, 0x6a, 0x68, 0xf7, 0x50, 0x24, 0x17, 0x64, 0x84, 0xfd, 0x88, 0x86,
	0x7d, 0xb1, 0x11, 0x45, 0x76, 0x59, 0x6c, 0x50, 0x67, 0x1f, 0x29, 0x44, 0x69, 0x98, 0x44, 0x9b,
	0x0d, 0xcb, 0x50, 0x36, 0x9e, 0xbd, 0x81, 0xc1, 0x51, 0x96, 0x89, 0x0c, 0x9f, 0x02, 0x65, 0x5d,
	0x28, 0x58, 0x8e, 0x46, 0x49, 0x19, 0xfe, 0xaa, 0x3b, 0x2b, 0x64, 0x39, 0x90, 0xc7, 0xd1, 0xf2,
	0xea, 0xec, 0xf2, 0x65, 0x91, 0xc6, 0x79, 0x49, 0xf4, 0xab, 0x28, 0x5d, 0xbd, 0xbe, 0x3e, 0xe7,
	0xd7, 0xe5, 0x34, 0x1a, 0xf7, 0x28, 0x6b, 0x5f, 0x74, 0xd5, 0xdf, 0x8d, 0xef, 0xff, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0xff, 0x6b, 0x58, 0x84, 0x0c, 0x00, 0x00,
}
