// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_haiwangbuyu.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgId int32

const (
	MsgId_ZERO                     MsgId = 0
	MsgId_INTO_ROOM_Req            MsgId = 1
	MsgId_INTO_ROOM_Res            MsgId = 2
	MsgId_EXIST_ROOM_Req           MsgId = 3
	MsgId_EXIST_ROOM_Res           MsgId = 4
	MsgId_SHOOT_Req                MsgId = 5
	MsgId_SHOOT_Res                MsgId = 6
	MsgId_HIT_Req                  MsgId = 7
	MsgId_HIT_Res                  MsgId = 8
	MsgId_FISHTIDE_Req             MsgId = 9
	MsgId_FISHTIDEFORECAST_Req     MsgId = 10
	MsgId_UPGRADE_Req              MsgId = 11
	MsgId_UPGRADE_Res              MsgId = 12
	MsgId_REFRESHFISH_Req          MsgId = 13
	MsgId_DEAD_Req                 MsgId = 14
	MsgId_DEAD_Res                 MsgId = 15
	MsgId_CHANGEMODEL_Req          MsgId = 16
	MsgId_CHANGEMODEL_Res          MsgId = 17
	MsgId_CHANGELOCKFISH_Req       MsgId = 18
	MsgId_CHANGELOCKFISH_Res       MsgId = 19
	MsgId_CHANGECALCULATEROBOT_Req MsgId = 20
	MsgId_CHANGESCENE_Req          MsgId = 21
	MsgId_SKILLHIT_Req             MsgId = 22
	MsgId_SKILLHIT_Res             MsgId = 23
	MsgId_SOMEONEENTER_Req         MsgId = 24
	MsgId_TEST_Req                 MsgId = 25
	MsgId_FISHTIDEEND_Req          MsgId = 26
	MsgId_SKILL_Req                MsgId = 27
	MsgId_SKILL_Res                MsgId = 28
	MsgId_TURN_Req                 MsgId = 29
	MsgId_BOSSFORECAST_Req         MsgId = 30
	MsgId_SKILLEND_Req             MsgId = 31
)

var MsgId_name = map[int32]string{
	0:  "ZERO",
	1:  "INTO_ROOM_Req",
	2:  "INTO_ROOM_Res",
	3:  "EXIST_ROOM_Req",
	4:  "EXIST_ROOM_Res",
	5:  "SHOOT_Req",
	6:  "SHOOT_Res",
	7:  "HIT_Req",
	8:  "HIT_Res",
	9:  "FISHTIDE_Req",
	10: "FISHTIDEFORECAST_Req",
	11: "UPGRADE_Req",
	12: "UPGRADE_Res",
	13: "REFRESHFISH_Req",
	14: "DEAD_Req",
	15: "DEAD_Res",
	16: "CHANGEMODEL_Req",
	17: "CHANGEMODEL_Res",
	18: "CHANGELOCKFISH_Req",
	19: "CHANGELOCKFISH_Res",
	20: "CHANGECALCULATEROBOT_Req",
	21: "CHANGESCENE_Req",
	22: "SKILLHIT_Req",
	23: "SKILLHIT_Res",
	24: "SOMEONEENTER_Req",
	25: "TEST_Req",
	26: "FISHTIDEEND_Req",
	27: "SKILL_Req",
	28: "SKILL_Res",
	29: "TURN_Req",
	30: "BOSSFORECAST_Req",
	31: "SKILLEND_Req",
}

var MsgId_value = map[string]int32{
	"ZERO":                     0,
	"INTO_ROOM_Req":            1,
	"INTO_ROOM_Res":            2,
	"EXIST_ROOM_Req":           3,
	"EXIST_ROOM_Res":           4,
	"SHOOT_Req":                5,
	"SHOOT_Res":                6,
	"HIT_Req":                  7,
	"HIT_Res":                  8,
	"FISHTIDE_Req":             9,
	"FISHTIDEFORECAST_Req":     10,
	"UPGRADE_Req":              11,
	"UPGRADE_Res":              12,
	"REFRESHFISH_Req":          13,
	"DEAD_Req":                 14,
	"DEAD_Res":                 15,
	"CHANGEMODEL_Req":          16,
	"CHANGEMODEL_Res":          17,
	"CHANGELOCKFISH_Req":       18,
	"CHANGELOCKFISH_Res":       19,
	"CHANGECALCULATEROBOT_Req": 20,
	"CHANGESCENE_Req":          21,
	"SKILLHIT_Req":             22,
	"SKILLHIT_Res":             23,
	"SOMEONEENTER_Req":         24,
	"TEST_Req":                 25,
	"FISHTIDEEND_Req":          26,
	"SKILL_Req":                27,
	"SKILL_Res":                28,
	"TURN_Req":                 29,
	"BOSSFORECAST_Req":         30,
	"SKILLEND_Req":             31,
}

func (x MsgId) String() string {
	return proto.EnumName(MsgId_name, int32(x))
}

func (MsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{0}
}

type ERROR int32

const (
	ERROR_ERROR_CODE_OK           ERROR = 0
	ERROR_ERROR_CODE_NOT_INTOROOM ERROR = 10000
	ERROR_ERROR_CODE_NOT_ENOUGH   ERROR = 10001
	ERROR_ERROR_CODE_LESS_MIN     ERROR = 10002
)

var ERROR_name = map[int32]string{
	0:     "ERROR_CODE_OK",
	10000: "ERROR_CODE_NOT_INTOROOM",
	10001: "ERROR_CODE_NOT_ENOUGH",
	10002: "ERROR_CODE_LESS_MIN",
}

var ERROR_value = map[string]int32{
	"ERROR_CODE_OK":           0,
	"ERROR_CODE_NOT_INTOROOM": 10000,
	"ERROR_CODE_NOT_ENOUGH":   10001,
	"ERROR_CODE_LESS_MIN":     10002,
}

func (x ERROR) String() string {
	return proto.EnumName(ERROR_name, int32(x))
}

func (ERROR) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{1}
}

type Type int32

const (
	Type_ZREO    Type = 0
	Type_SMALL   Type = 1
	Type_MIDDLE  Type = 2
	Type_BIG     Type = 3
	Type_BOSS    Type = 4
	Type_PILE    Type = 5
	Type_KING    Type = 6
	Type_SPECIAL Type = 10
)

var Type_name = map[int32]string{
	0:  "ZREO",
	1:  "SMALL",
	2:  "MIDDLE",
	3:  "BIG",
	4:  "BOSS",
	5:  "PILE",
	6:  "KING",
	10: "SPECIAL",
}

var Type_value = map[string]int32{
	"ZREO":    0,
	"SMALL":   1,
	"MIDDLE":  2,
	"BIG":     3,
	"BOSS":    4,
	"PILE":    5,
	"KING":    6,
	"SPECIAL": 10,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{2}
}

//发送给客户端所有消息协议封包，buff是具体的结构体内容，需要端对照相应的协议解析
type Msg struct {
	MainCmd              int32    `protobuf:"varint,1,opt,name=mainCmd,proto3" json:"mainCmd,omitempty"`
	SubCmd               int32    `protobuf:"varint,2,opt,name=subCmd,proto3" json:"subCmd,omitempty"`
	Buff                 []byte   `protobuf:"bytes,3,opt,name=buff,proto3" json:"buff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMainCmd() int32 {
	if m != nil {
		return m.MainCmd
	}
	return 0
}

func (m *Msg) GetSubCmd() int32 {
	if m != nil {
		return m.SubCmd
	}
	return 0
}

func (m *Msg) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

//牌桌信息
type TableInfo struct {
	TableId              int32       `protobuf:"varint,1,opt,name=tableId,proto3" json:"tableId,omitempty"`
	TableName            string      `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	UserInfoArr          []*UserInfo `protobuf:"bytes,3,rep,name=userInfoArr,proto3" json:"userInfoArr,omitempty"`
	Fishes               []*Fish     `protobuf:"bytes,4,rep,name=fishes,proto3" json:"fishes,omitempty"`
	SceneId              int32       `protobuf:"varint,5,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	FishTide             bool        `protobuf:"varint,6,opt,name=fishTide,proto3" json:"fishTide,omitempty"`
	ServerTime           int64       `protobuf:"varint,7,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TableInfo) Reset()         { *m = TableInfo{} }
func (m *TableInfo) String() string { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()    {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{1}
}

func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableInfo.Unmarshal(m, b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return xxx_messageInfo_TableInfo.Size(m)
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

func (m *TableInfo) GetTableId() int32 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *TableInfo) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *TableInfo) GetUserInfoArr() []*UserInfo {
	if m != nil {
		return m.UserInfoArr
	}
	return nil
}

func (m *TableInfo) GetFishes() []*Fish {
	if m != nil {
		return m.Fishes
	}
	return nil
}

func (m *TableInfo) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *TableInfo) GetFishTide() bool {
	if m != nil {
		return m.FishTide
	}
	return false
}

func (m *TableInfo) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

//用户信息
type UserInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Head                 string   `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Amount               int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChairId              int32    `protobuf:"varint,6,opt,name=chairId,proto3" json:"chairId,omitempty"`
	BulletLv             int32    `protobuf:"varint,7,opt,name=bulletLv,proto3" json:"bulletLv,omitempty"`
	Auto                 bool     `protobuf:"varint,8,opt,name=auto,proto3" json:"auto,omitempty"`
	Speed                bool     `protobuf:"varint,9,opt,name=speed,proto3" json:"speed,omitempty"`
	Lock                 bool     `protobuf:"varint,10,opt,name=lock,proto3" json:"lock,omitempty"`
	LockFishId           int32    `protobuf:"varint,11,opt,name=lockFishId,proto3" json:"lockFishId,omitempty"`
	CalculateRobot       bool     `protobuf:"varint,12,opt,name=calculateRobot,proto3" json:"calculateRobot,omitempty"`
	IsRobot              bool     `protobuf:"varint,13,opt,name=isRobot,proto3" json:"isRobot,omitempty"`
	Skills               []*Skill `protobuf:"bytes,14,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UserInfo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UserInfo) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *UserInfo) GetBulletLv() int32 {
	if m != nil {
		return m.BulletLv
	}
	return 0
}

func (m *UserInfo) GetAuto() bool {
	if m != nil {
		return m.Auto
	}
	return false
}

func (m *UserInfo) GetSpeed() bool {
	if m != nil {
		return m.Speed
	}
	return false
}

func (m *UserInfo) GetLock() bool {
	if m != nil {
		return m.Lock
	}
	return false
}

func (m *UserInfo) GetLockFishId() int32 {
	if m != nil {
		return m.LockFishId
	}
	return 0
}

func (m *UserInfo) GetCalculateRobot() bool {
	if m != nil {
		return m.CalculateRobot
	}
	return false
}

func (m *UserInfo) GetIsRobot() bool {
	if m != nil {
		return m.IsRobot
	}
	return false
}

func (m *UserInfo) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Fish struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BornTime             int64          `protobuf:"varint,2,opt,name=bornTime,proto3" json:"bornTime,omitempty"`
	BornPoint            *Point         `protobuf:"bytes,3,opt,name=bornPoint,proto3" json:"bornPoint,omitempty"`
	Line                 []*Point       `protobuf:"bytes,4,rep,name=line,proto3" json:"line,omitempty"`
	TypeId               Type           `protobuf:"varint,5,opt,name=typeId,proto3,enum=msg.Type" json:"typeId,omitempty"`
	IsDead               bool           `protobuf:"varint,6,opt,name=isDead,proto3" json:"isDead,omitempty"`
	FishId               string         `protobuf:"bytes,7,opt,name=fishId,proto3" json:"fishId,omitempty"`
	Speed                []int32        `protobuf:"varint,8,rep,packed,name=speed,proto3" json:"speed,omitempty"`
	Num                  int32          `protobuf:"varint,9,opt,name=num,proto3" json:"num,omitempty"`
	SkillId              int32          `protobuf:"varint,10,opt,name=skillId,proto3" json:"skillId,omitempty"`
	FormationInfo        *FormationInfo `protobuf:"bytes,11,opt,name=formationInfo,proto3" json:"formationInfo,omitempty"`
	BornIndex            int32          `protobuf:"varint,12,opt,name=bornIndex,proto3" json:"bornIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Fish) Reset()         { *m = Fish{} }
func (m *Fish) String() string { return proto.CompactTextString(m) }
func (*Fish) ProtoMessage()    {}
func (*Fish) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{3}
}

func (m *Fish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fish.Unmarshal(m, b)
}
func (m *Fish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fish.Marshal(b, m, deterministic)
}
func (m *Fish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fish.Merge(m, src)
}
func (m *Fish) XXX_Size() int {
	return xxx_messageInfo_Fish.Size(m)
}
func (m *Fish) XXX_DiscardUnknown() {
	xxx_messageInfo_Fish.DiscardUnknown(m)
}

var xxx_messageInfo_Fish proto.InternalMessageInfo

func (m *Fish) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fish) GetBornTime() int64 {
	if m != nil {
		return m.BornTime
	}
	return 0
}

func (m *Fish) GetBornPoint() *Point {
	if m != nil {
		return m.BornPoint
	}
	return nil
}

func (m *Fish) GetLine() []*Point {
	if m != nil {
		return m.Line
	}
	return nil
}

func (m *Fish) GetTypeId() Type {
	if m != nil {
		return m.TypeId
	}
	return Type_ZREO
}

func (m *Fish) GetIsDead() bool {
	if m != nil {
		return m.IsDead
	}
	return false
}

func (m *Fish) GetFishId() string {
	if m != nil {
		return m.FishId
	}
	return ""
}

func (m *Fish) GetSpeed() []int32 {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *Fish) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Fish) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *Fish) GetFormationInfo() *FormationInfo {
	if m != nil {
		return m.FormationInfo
	}
	return nil
}

func (m *Fish) GetBornIndex() int32 {
	if m != nil {
		return m.BornIndex
	}
	return 0
}

type Point struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{4}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type EnterRoomReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomReq) Reset()         { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string { return proto.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()    {}
func (*EnterRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{5}
}

func (m *EnterRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomReq.Unmarshal(m, b)
}
func (m *EnterRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomReq.Marshal(b, m, deterministic)
}
func (m *EnterRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomReq.Merge(m, src)
}
func (m *EnterRoomReq) XXX_Size() int {
	return xxx_messageInfo_EnterRoomReq.Size(m)
}
func (m *EnterRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomReq proto.InternalMessageInfo

func (m *EnterRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EnterRoomReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type EnterRoomRes struct {
	TableInfo            *TableInfo `protobuf:"bytes,1,opt,name=tableInfo,proto3" json:"tableInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnterRoomRes) Reset()         { *m = EnterRoomRes{} }
func (m *EnterRoomRes) String() string { return proto.CompactTextString(m) }
func (*EnterRoomRes) ProtoMessage()    {}
func (*EnterRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{6}
}

func (m *EnterRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomRes.Unmarshal(m, b)
}
func (m *EnterRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomRes.Marshal(b, m, deterministic)
}
func (m *EnterRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomRes.Merge(m, src)
}
func (m *EnterRoomRes) XXX_Size() int {
	return xxx_messageInfo_EnterRoomRes.Size(m)
}
func (m *EnterRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomRes proto.InternalMessageInfo

func (m *EnterRoomRes) GetTableInfo() *TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type ExistRoomReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistRoomReq) Reset()         { *m = ExistRoomReq{} }
func (m *ExistRoomReq) String() string { return proto.CompactTextString(m) }
func (*ExistRoomReq) ProtoMessage()    {}
func (*ExistRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{7}
}

func (m *ExistRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRoomReq.Unmarshal(m, b)
}
func (m *ExistRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRoomReq.Marshal(b, m, deterministic)
}
func (m *ExistRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRoomReq.Merge(m, src)
}
func (m *ExistRoomReq) XXX_Size() int {
	return xxx_messageInfo_ExistRoomReq.Size(m)
}
func (m *ExistRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRoomReq proto.InternalMessageInfo

func (m *ExistRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ExistRoomRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistRoomRes) Reset()         { *m = ExistRoomRes{} }
func (m *ExistRoomRes) String() string { return proto.CompactTextString(m) }
func (*ExistRoomRes) ProtoMessage()    {}
func (*ExistRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{8}
}

func (m *ExistRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRoomRes.Unmarshal(m, b)
}
func (m *ExistRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRoomRes.Marshal(b, m, deterministic)
}
func (m *ExistRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRoomRes.Merge(m, src)
}
func (m *ExistRoomRes) XXX_Size() int {
	return xxx_messageInfo_ExistRoomRes.Size(m)
}
func (m *ExistRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRoomRes proto.InternalMessageInfo

func (m *ExistRoomRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ShootReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Point                *Point   `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	BulletType           int32    `protobuf:"varint,3,opt,name=bulletType,proto3" json:"bulletType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShootReq) Reset()         { *m = ShootReq{} }
func (m *ShootReq) String() string { return proto.CompactTextString(m) }
func (*ShootReq) ProtoMessage()    {}
func (*ShootReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{9}
}

func (m *ShootReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShootReq.Unmarshal(m, b)
}
func (m *ShootReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShootReq.Marshal(b, m, deterministic)
}
func (m *ShootReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShootReq.Merge(m, src)
}
func (m *ShootReq) XXX_Size() int {
	return xxx_messageInfo_ShootReq.Size(m)
}
func (m *ShootReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShootReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShootReq proto.InternalMessageInfo

func (m *ShootReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ShootReq) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *ShootReq) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

type ShootRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Point                *Point   `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	BulletType           int32    `protobuf:"varint,3,opt,name=bulletType,proto3" json:"bulletType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShootRes) Reset()         { *m = ShootRes{} }
func (m *ShootRes) String() string { return proto.CompactTextString(m) }
func (*ShootRes) ProtoMessage()    {}
func (*ShootRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{10}
}

func (m *ShootRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShootRes.Unmarshal(m, b)
}
func (m *ShootRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShootRes.Marshal(b, m, deterministic)
}
func (m *ShootRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShootRes.Merge(m, src)
}
func (m *ShootRes) XXX_Size() int {
	return xxx_messageInfo_ShootRes.Size(m)
}
func (m *ShootRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ShootRes.DiscardUnknown(m)
}

var xxx_messageInfo_ShootRes proto.InternalMessageInfo

func (m *ShootRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ShootRes) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *ShootRes) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

type HitReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FishId               int32    `protobuf:"varint,2,opt,name=fishId,proto3" json:"fishId,omitempty"`
	BulletLv             int32    `protobuf:"varint,3,opt,name=bulletLv,proto3" json:"bulletLv,omitempty"`
	IsPenetrate          bool     `protobuf:"varint,4,opt,name=isPenetrate,proto3" json:"isPenetrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HitReq) Reset()         { *m = HitReq{} }
func (m *HitReq) String() string { return proto.CompactTextString(m) }
func (*HitReq) ProtoMessage()    {}
func (*HitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{11}
}

func (m *HitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HitReq.Unmarshal(m, b)
}
func (m *HitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HitReq.Marshal(b, m, deterministic)
}
func (m *HitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HitReq.Merge(m, src)
}
func (m *HitReq) XXX_Size() int {
	return xxx_messageInfo_HitReq.Size(m)
}
func (m *HitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HitReq.DiscardUnknown(m)
}

var xxx_messageInfo_HitReq proto.InternalMessageInfo

func (m *HitReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HitReq) GetFishId() int32 {
	if m != nil {
		return m.FishId
	}
	return 0
}

func (m *HitReq) GetBulletLv() int32 {
	if m != nil {
		return m.BulletLv
	}
	return 0
}

func (m *HitReq) GetIsPenetrate() bool {
	if m != nil {
		return m.IsPenetrate
	}
	return false
}

type HitRes struct {
	UserId               int64     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Fish                 *DeadFish `protobuf:"bytes,2,opt,name=fish,proto3" json:"fish,omitempty"`
	Key                  string    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	CoinChange           int32     `protobuf:"varint,4,opt,name=coinChange,proto3" json:"coinChange,omitempty"`
	IsEmpty              int32     `protobuf:"varint,5,opt,name=isEmpty,proto3" json:"isEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HitRes) Reset()         { *m = HitRes{} }
func (m *HitRes) String() string { return proto.CompactTextString(m) }
func (*HitRes) ProtoMessage()    {}
func (*HitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{12}
}

func (m *HitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HitRes.Unmarshal(m, b)
}
func (m *HitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HitRes.Marshal(b, m, deterministic)
}
func (m *HitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HitRes.Merge(m, src)
}
func (m *HitRes) XXX_Size() int {
	return xxx_messageInfo_HitRes.Size(m)
}
func (m *HitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HitRes.DiscardUnknown(m)
}

var xxx_messageInfo_HitRes proto.InternalMessageInfo

func (m *HitRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HitRes) GetFish() *DeadFish {
	if m != nil {
		return m.Fish
	}
	return nil
}

func (m *HitRes) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HitRes) GetCoinChange() int32 {
	if m != nil {
		return m.CoinChange
	}
	return 0
}

func (m *HitRes) GetIsEmpty() int32 {
	if m != nil {
		return m.IsEmpty
	}
	return 0
}

type FishTideForecastReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FishTideForecastReq) Reset()         { *m = FishTideForecastReq{} }
func (m *FishTideForecastReq) String() string { return proto.CompactTextString(m) }
func (*FishTideForecastReq) ProtoMessage()    {}
func (*FishTideForecastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{13}
}

func (m *FishTideForecastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FishTideForecastReq.Unmarshal(m, b)
}
func (m *FishTideForecastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FishTideForecastReq.Marshal(b, m, deterministic)
}
func (m *FishTideForecastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FishTideForecastReq.Merge(m, src)
}
func (m *FishTideForecastReq) XXX_Size() int {
	return xxx_messageInfo_FishTideForecastReq.Size(m)
}
func (m *FishTideForecastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FishTideForecastReq.DiscardUnknown(m)
}

var xxx_messageInfo_FishTideForecastReq proto.InternalMessageInfo

type FishTideReq struct {
	Formation            int32    `protobuf:"varint,1,opt,name=formation,proto3" json:"formation,omitempty"`
	Line                 int32    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FishTideReq) Reset()         { *m = FishTideReq{} }
func (m *FishTideReq) String() string { return proto.CompactTextString(m) }
func (*FishTideReq) ProtoMessage()    {}
func (*FishTideReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{14}
}

func (m *FishTideReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FishTideReq.Unmarshal(m, b)
}
func (m *FishTideReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FishTideReq.Marshal(b, m, deterministic)
}
func (m *FishTideReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FishTideReq.Merge(m, src)
}
func (m *FishTideReq) XXX_Size() int {
	return xxx_messageInfo_FishTideReq.Size(m)
}
func (m *FishTideReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FishTideReq.DiscardUnknown(m)
}

var xxx_messageInfo_FishTideReq proto.InternalMessageInfo

func (m *FishTideReq) GetFormation() int32 {
	if m != nil {
		return m.Formation
	}
	return 0
}

func (m *FishTideReq) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

type UpgradeReq struct {
	IsAdd                bool     `protobuf:"varint,1,opt,name=isAdd,proto3" json:"isAdd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeReq) Reset()         { *m = UpgradeReq{} }
func (m *UpgradeReq) String() string { return proto.CompactTextString(m) }
func (*UpgradeReq) ProtoMessage()    {}
func (*UpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{15}
}

func (m *UpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeReq.Unmarshal(m, b)
}
func (m *UpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeReq.Marshal(b, m, deterministic)
}
func (m *UpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeReq.Merge(m, src)
}
func (m *UpgradeReq) XXX_Size() int {
	return xxx_messageInfo_UpgradeReq.Size(m)
}
func (m *UpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeReq proto.InternalMessageInfo

func (m *UpgradeReq) GetIsAdd() bool {
	if m != nil {
		return m.IsAdd
	}
	return false
}

type UpgradeRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Lv                   int32    `protobuf:"varint,2,opt,name=lv,proto3" json:"lv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeRes) Reset()         { *m = UpgradeRes{} }
func (m *UpgradeRes) String() string { return proto.CompactTextString(m) }
func (*UpgradeRes) ProtoMessage()    {}
func (*UpgradeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{16}
}

func (m *UpgradeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeRes.Unmarshal(m, b)
}
func (m *UpgradeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeRes.Marshal(b, m, deterministic)
}
func (m *UpgradeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeRes.Merge(m, src)
}
func (m *UpgradeRes) XXX_Size() int {
	return xxx_messageInfo_UpgradeRes.Size(m)
}
func (m *UpgradeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeRes proto.InternalMessageInfo

func (m *UpgradeRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpgradeRes) GetLv() int32 {
	if m != nil {
		return m.Lv
	}
	return 0
}

type RefreshFishReq struct {
	Fish                 []*Fish  `protobuf:"bytes,1,rep,name=fish,proto3" json:"fish,omitempty"`
	Offset               []*Point `protobuf:"bytes,2,rep,name=offset,proto3" json:"offset,omitempty"`
	IsSummon             bool     `protobuf:"varint,3,opt,name=isSummon,proto3" json:"isSummon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshFishReq) Reset()         { *m = RefreshFishReq{} }
func (m *RefreshFishReq) String() string { return proto.CompactTextString(m) }
func (*RefreshFishReq) ProtoMessage()    {}
func (*RefreshFishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{17}
}

func (m *RefreshFishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshFishReq.Unmarshal(m, b)
}
func (m *RefreshFishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshFishReq.Marshal(b, m, deterministic)
}
func (m *RefreshFishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshFishReq.Merge(m, src)
}
func (m *RefreshFishReq) XXX_Size() int {
	return xxx_messageInfo_RefreshFishReq.Size(m)
}
func (m *RefreshFishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshFishReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshFishReq proto.InternalMessageInfo

func (m *RefreshFishReq) GetFish() []*Fish {
	if m != nil {
		return m.Fish
	}
	return nil
}

func (m *RefreshFishReq) GetOffset() []*Point {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *RefreshFishReq) GetIsSummon() bool {
	if m != nil {
		return m.IsSummon
	}
	return false
}

type DeadReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeadReq) Reset()         { *m = DeadReq{} }
func (m *DeadReq) String() string { return proto.CompactTextString(m) }
func (*DeadReq) ProtoMessage()    {}
func (*DeadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{18}
}

func (m *DeadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadReq.Unmarshal(m, b)
}
func (m *DeadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadReq.Marshal(b, m, deterministic)
}
func (m *DeadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadReq.Merge(m, src)
}
func (m *DeadReq) XXX_Size() int {
	return xxx_messageInfo_DeadReq.Size(m)
}
func (m *DeadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeadReq proto.InternalMessageInfo

func (m *DeadReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeadRes struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeadRes) Reset()         { *m = DeadRes{} }
func (m *DeadRes) String() string { return proto.CompactTextString(m) }
func (*DeadRes) ProtoMessage()    {}
func (*DeadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{19}
}

func (m *DeadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadRes.Unmarshal(m, b)
}
func (m *DeadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadRes.Marshal(b, m, deterministic)
}
func (m *DeadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadRes.Merge(m, src)
}
func (m *DeadRes) XXX_Size() int {
	return xxx_messageInfo_DeadRes.Size(m)
}
func (m *DeadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeadRes proto.InternalMessageInfo

func (m *DeadRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChangemModelReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ModelId              int32    `protobuf:"varint,2,opt,name=modelId,proto3" json:"modelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangemModelReq) Reset()         { *m = ChangemModelReq{} }
func (m *ChangemModelReq) String() string { return proto.CompactTextString(m) }
func (*ChangemModelReq) ProtoMessage()    {}
func (*ChangemModelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{20}
}

func (m *ChangemModelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangemModelReq.Unmarshal(m, b)
}
func (m *ChangemModelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangemModelReq.Marshal(b, m, deterministic)
}
func (m *ChangemModelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangemModelReq.Merge(m, src)
}
func (m *ChangemModelReq) XXX_Size() int {
	return xxx_messageInfo_ChangemModelReq.Size(m)
}
func (m *ChangemModelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangemModelReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangemModelReq proto.InternalMessageInfo

func (m *ChangemModelReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangemModelReq) GetModelId() int32 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

type ChangemModelRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ModelId              int32    `protobuf:"varint,2,opt,name=modelId,proto3" json:"modelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangemModelRes) Reset()         { *m = ChangemModelRes{} }
func (m *ChangemModelRes) String() string { return proto.CompactTextString(m) }
func (*ChangemModelRes) ProtoMessage()    {}
func (*ChangemModelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{21}
}

func (m *ChangemModelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangemModelRes.Unmarshal(m, b)
}
func (m *ChangemModelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangemModelRes.Marshal(b, m, deterministic)
}
func (m *ChangemModelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangemModelRes.Merge(m, src)
}
func (m *ChangemModelRes) XXX_Size() int {
	return xxx_messageInfo_ChangemModelRes.Size(m)
}
func (m *ChangemModelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangemModelRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChangemModelRes proto.InternalMessageInfo

func (m *ChangemModelRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangemModelRes) GetModelId() int32 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

type ChangemLockFishReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FishId               int32    `protobuf:"varint,2,opt,name=fishId,proto3" json:"fishId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangemLockFishReq) Reset()         { *m = ChangemLockFishReq{} }
func (m *ChangemLockFishReq) String() string { return proto.CompactTextString(m) }
func (*ChangemLockFishReq) ProtoMessage()    {}
func (*ChangemLockFishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{22}
}

func (m *ChangemLockFishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangemLockFishReq.Unmarshal(m, b)
}
func (m *ChangemLockFishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangemLockFishReq.Marshal(b, m, deterministic)
}
func (m *ChangemLockFishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangemLockFishReq.Merge(m, src)
}
func (m *ChangemLockFishReq) XXX_Size() int {
	return xxx_messageInfo_ChangemLockFishReq.Size(m)
}
func (m *ChangemLockFishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangemLockFishReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangemLockFishReq proto.InternalMessageInfo

func (m *ChangemLockFishReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangemLockFishReq) GetFishId() int32 {
	if m != nil {
		return m.FishId
	}
	return 0
}

type ChangemLockFishRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FishId               int32    `protobuf:"varint,2,opt,name=fishId,proto3" json:"fishId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangemLockFishRes) Reset()         { *m = ChangemLockFishRes{} }
func (m *ChangemLockFishRes) String() string { return proto.CompactTextString(m) }
func (*ChangemLockFishRes) ProtoMessage()    {}
func (*ChangemLockFishRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{23}
}

func (m *ChangemLockFishRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangemLockFishRes.Unmarshal(m, b)
}
func (m *ChangemLockFishRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangemLockFishRes.Marshal(b, m, deterministic)
}
func (m *ChangemLockFishRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangemLockFishRes.Merge(m, src)
}
func (m *ChangemLockFishRes) XXX_Size() int {
	return xxx_messageInfo_ChangemLockFishRes.Size(m)
}
func (m *ChangemLockFishRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangemLockFishRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChangemLockFishRes proto.InternalMessageInfo

func (m *ChangemLockFishRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangemLockFishRes) GetFishId() int32 {
	if m != nil {
		return m.FishId
	}
	return 0
}

type ChangeCalculateRobot_Req struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeCalculateRobot_Req) Reset()         { *m = ChangeCalculateRobot_Req{} }
func (m *ChangeCalculateRobot_Req) String() string { return proto.CompactTextString(m) }
func (*ChangeCalculateRobot_Req) ProtoMessage()    {}
func (*ChangeCalculateRobot_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{24}
}

func (m *ChangeCalculateRobot_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeCalculateRobot_Req.Unmarshal(m, b)
}
func (m *ChangeCalculateRobot_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeCalculateRobot_Req.Marshal(b, m, deterministic)
}
func (m *ChangeCalculateRobot_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeCalculateRobot_Req.Merge(m, src)
}
func (m *ChangeCalculateRobot_Req) XXX_Size() int {
	return xxx_messageInfo_ChangeCalculateRobot_Req.Size(m)
}
func (m *ChangeCalculateRobot_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeCalculateRobot_Req.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeCalculateRobot_Req proto.InternalMessageInfo

func (m *ChangeCalculateRobot_Req) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ChangemSceneReq struct {
	SceneId              int32    `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangemSceneReq) Reset()         { *m = ChangemSceneReq{} }
func (m *ChangemSceneReq) String() string { return proto.CompactTextString(m) }
func (*ChangemSceneReq) ProtoMessage()    {}
func (*ChangemSceneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{25}
}

func (m *ChangemSceneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangemSceneReq.Unmarshal(m, b)
}
func (m *ChangemSceneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangemSceneReq.Marshal(b, m, deterministic)
}
func (m *ChangemSceneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangemSceneReq.Merge(m, src)
}
func (m *ChangemSceneReq) XXX_Size() int {
	return xxx_messageInfo_ChangemSceneReq.Size(m)
}
func (m *ChangemSceneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangemSceneReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangemSceneReq proto.InternalMessageInfo

func (m *ChangemSceneReq) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

type SkillHitReq struct {
	FishId               string   `protobuf:"bytes,1,opt,name=fishId,proto3" json:"fishId,omitempty"`
	SkillId              int32    `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`
	FishIds              []int32  `protobuf:"varint,3,rep,packed,name=fishIds,proto3" json:"fishIds,omitempty"`
	Point                *Point   `protobuf:"bytes,4,opt,name=point,proto3" json:"point,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillHitReq) Reset()         { *m = SkillHitReq{} }
func (m *SkillHitReq) String() string { return proto.CompactTextString(m) }
func (*SkillHitReq) ProtoMessage()    {}
func (*SkillHitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{26}
}

func (m *SkillHitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillHitReq.Unmarshal(m, b)
}
func (m *SkillHitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillHitReq.Marshal(b, m, deterministic)
}
func (m *SkillHitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillHitReq.Merge(m, src)
}
func (m *SkillHitReq) XXX_Size() int {
	return xxx_messageInfo_SkillHitReq.Size(m)
}
func (m *SkillHitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillHitReq.DiscardUnknown(m)
}

var xxx_messageInfo_SkillHitReq proto.InternalMessageInfo

func (m *SkillHitReq) GetFishId() string {
	if m != nil {
		return m.FishId
	}
	return ""
}

func (m *SkillHitReq) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *SkillHitReq) GetFishIds() []int32 {
	if m != nil {
		return m.FishIds
	}
	return nil
}

func (m *SkillHitReq) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *SkillHitReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SkillHitRes struct {
	FishIds              []*DeadFish `protobuf:"bytes,1,rep,name=fishIds,proto3" json:"fishIds,omitempty"`
	Fishes               []int32     `protobuf:"varint,2,rep,packed,name=fishes,proto3" json:"fishes,omitempty"`
	SkillId              int32       `protobuf:"varint,3,opt,name=skillId,proto3" json:"skillId,omitempty"`
	UserId               int64       `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Point                *Point      `protobuf:"bytes,5,opt,name=point,proto3" json:"point,omitempty"`
	CoinChange           int32       `protobuf:"varint,6,opt,name=coinChange,proto3" json:"coinChange,omitempty"`
	FishId               string      `protobuf:"bytes,7,opt,name=fishId,proto3" json:"fishId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SkillHitRes) Reset()         { *m = SkillHitRes{} }
func (m *SkillHitRes) String() string { return proto.CompactTextString(m) }
func (*SkillHitRes) ProtoMessage()    {}
func (*SkillHitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{27}
}

func (m *SkillHitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillHitRes.Unmarshal(m, b)
}
func (m *SkillHitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillHitRes.Marshal(b, m, deterministic)
}
func (m *SkillHitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillHitRes.Merge(m, src)
}
func (m *SkillHitRes) XXX_Size() int {
	return xxx_messageInfo_SkillHitRes.Size(m)
}
func (m *SkillHitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillHitRes.DiscardUnknown(m)
}

var xxx_messageInfo_SkillHitRes proto.InternalMessageInfo

func (m *SkillHitRes) GetFishIds() []*DeadFish {
	if m != nil {
		return m.FishIds
	}
	return nil
}

func (m *SkillHitRes) GetFishes() []int32 {
	if m != nil {
		return m.Fishes
	}
	return nil
}

func (m *SkillHitRes) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *SkillHitRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SkillHitRes) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *SkillHitRes) GetCoinChange() int32 {
	if m != nil {
		return m.CoinChange
	}
	return 0
}

func (m *SkillHitRes) GetFishId() string {
	if m != nil {
		return m.FishId
	}
	return ""
}

type DeadFish struct {
	FishId               int32    `protobuf:"varint,1,opt,name=fishId,proto3" json:"fishId,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeadFish) Reset()         { *m = DeadFish{} }
func (m *DeadFish) String() string { return proto.CompactTextString(m) }
func (*DeadFish) ProtoMessage()    {}
func (*DeadFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{28}
}

func (m *DeadFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadFish.Unmarshal(m, b)
}
func (m *DeadFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadFish.Marshal(b, m, deterministic)
}
func (m *DeadFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadFish.Merge(m, src)
}
func (m *DeadFish) XXX_Size() int {
	return xxx_messageInfo_DeadFish.Size(m)
}
func (m *DeadFish) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadFish.DiscardUnknown(m)
}

var xxx_messageInfo_DeadFish proto.InternalMessageInfo

func (m *DeadFish) GetFishId() int32 {
	if m != nil {
		return m.FishId
	}
	return 0
}

func (m *DeadFish) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type SomeoneEnter_Req struct {
	UserInfoArr          []*UserInfo `protobuf:"bytes,1,rep,name=userInfoArr,proto3" json:"userInfoArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SomeoneEnter_Req) Reset()         { *m = SomeoneEnter_Req{} }
func (m *SomeoneEnter_Req) String() string { return proto.CompactTextString(m) }
func (*SomeoneEnter_Req) ProtoMessage()    {}
func (*SomeoneEnter_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{29}
}

func (m *SomeoneEnter_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeoneEnter_Req.Unmarshal(m, b)
}
func (m *SomeoneEnter_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeoneEnter_Req.Marshal(b, m, deterministic)
}
func (m *SomeoneEnter_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeoneEnter_Req.Merge(m, src)
}
func (m *SomeoneEnter_Req) XXX_Size() int {
	return xxx_messageInfo_SomeoneEnter_Req.Size(m)
}
func (m *SomeoneEnter_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeoneEnter_Req.DiscardUnknown(m)
}

var xxx_messageInfo_SomeoneEnter_Req proto.InternalMessageInfo

func (m *SomeoneEnter_Req) GetUserInfoArr() []*UserInfo {
	if m != nil {
		return m.UserInfoArr
	}
	return nil
}

type FormationInfo struct {
	Radius               float32  `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
	Overlying            float32  `protobuf:"fixed32,2,opt,name=overlying,proto3" json:"overlying,omitempty"`
	Angle                float32  `protobuf:"fixed32,3,opt,name=angle,proto3" json:"angle,omitempty"`
	Point                *Point   `protobuf:"bytes,4,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormationInfo) Reset()         { *m = FormationInfo{} }
func (m *FormationInfo) String() string { return proto.CompactTextString(m) }
func (*FormationInfo) ProtoMessage()    {}
func (*FormationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{30}
}

func (m *FormationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormationInfo.Unmarshal(m, b)
}
func (m *FormationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormationInfo.Marshal(b, m, deterministic)
}
func (m *FormationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormationInfo.Merge(m, src)
}
func (m *FormationInfo) XXX_Size() int {
	return xxx_messageInfo_FormationInfo.Size(m)
}
func (m *FormationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FormationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FormationInfo proto.InternalMessageInfo

func (m *FormationInfo) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *FormationInfo) GetOverlying() float32 {
	if m != nil {
		return m.Overlying
	}
	return 0
}

func (m *FormationInfo) GetAngle() float32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *FormationInfo) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type TestReq struct {
	Func                 int32    `protobuf:"varint,1,opt,name=func,proto3" json:"func,omitempty"`
	FishId               string   `protobuf:"bytes,2,opt,name=fishId,proto3" json:"fishId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReq) Reset()         { *m = TestReq{} }
func (m *TestReq) String() string { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()    {}
func (*TestReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{31}
}

func (m *TestReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReq.Unmarshal(m, b)
}
func (m *TestReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReq.Marshal(b, m, deterministic)
}
func (m *TestReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReq.Merge(m, src)
}
func (m *TestReq) XXX_Size() int {
	return xxx_messageInfo_TestReq.Size(m)
}
func (m *TestReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReq.DiscardUnknown(m)
}

var xxx_messageInfo_TestReq proto.InternalMessageInfo

func (m *TestReq) GetFunc() int32 {
	if m != nil {
		return m.Func
	}
	return 0
}

func (m *TestReq) GetFishId() string {
	if m != nil {
		return m.FishId
	}
	return ""
}

type FishtideEndReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FishtideEndReq) Reset()         { *m = FishtideEndReq{} }
func (m *FishtideEndReq) String() string { return proto.CompactTextString(m) }
func (*FishtideEndReq) ProtoMessage()    {}
func (*FishtideEndReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{32}
}

func (m *FishtideEndReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FishtideEndReq.Unmarshal(m, b)
}
func (m *FishtideEndReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FishtideEndReq.Marshal(b, m, deterministic)
}
func (m *FishtideEndReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FishtideEndReq.Merge(m, src)
}
func (m *FishtideEndReq) XXX_Size() int {
	return xxx_messageInfo_FishtideEndReq.Size(m)
}
func (m *FishtideEndReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FishtideEndReq.DiscardUnknown(m)
}

var xxx_messageInfo_FishtideEndReq proto.InternalMessageInfo

type Skill struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Interval             int64    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Dur                  int64    `protobuf:"varint,3,opt,name=dur,proto3" json:"dur,omitempty"`
	Chance               int32    `protobuf:"varint,4,opt,name=chance,proto3" json:"chance,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	LastTime             int64    `protobuf:"varint,6,opt,name=lastTime,proto3" json:"lastTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{33}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *Skill) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Skill) GetDur() int64 {
	if m != nil {
		return m.Dur
	}
	return 0
}

func (m *Skill) GetChance() int32 {
	if m != nil {
		return m.Chance
	}
	return 0
}

func (m *Skill) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Skill) GetLastTime() int64 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

type SkillReq struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Fishes               []int32  `protobuf:"varint,2,rep,packed,name=fishes,proto3" json:"fishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillReq) Reset()         { *m = SkillReq{} }
func (m *SkillReq) String() string { return proto.CompactTextString(m) }
func (*SkillReq) ProtoMessage()    {}
func (*SkillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{34}
}

func (m *SkillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillReq.Unmarshal(m, b)
}
func (m *SkillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillReq.Marshal(b, m, deterministic)
}
func (m *SkillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillReq.Merge(m, src)
}
func (m *SkillReq) XXX_Size() int {
	return xxx_messageInfo_SkillReq.Size(m)
}
func (m *SkillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillReq.DiscardUnknown(m)
}

var xxx_messageInfo_SkillReq proto.InternalMessageInfo

func (m *SkillReq) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *SkillReq) GetFishes() []int32 {
	if m != nil {
		return m.Fishes
	}
	return nil
}

type SkillRes struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Fishes               []int32  `protobuf:"varint,2,rep,packed,name=fishes,proto3" json:"fishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillRes) Reset()         { *m = SkillRes{} }
func (m *SkillRes) String() string { return proto.CompactTextString(m) }
func (*SkillRes) ProtoMessage()    {}
func (*SkillRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{35}
}

func (m *SkillRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillRes.Unmarshal(m, b)
}
func (m *SkillRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillRes.Marshal(b, m, deterministic)
}
func (m *SkillRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillRes.Merge(m, src)
}
func (m *SkillRes) XXX_Size() int {
	return xxx_messageInfo_SkillRes.Size(m)
}
func (m *SkillRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillRes.DiscardUnknown(m)
}

var xxx_messageInfo_SkillRes proto.InternalMessageInfo

func (m *SkillRes) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *SkillRes) GetFishes() []int32 {
	if m != nil {
		return m.Fishes
	}
	return nil
}

type TurnReq struct {
	IsTurn               bool        `protobuf:"varint,1,opt,name=isTurn,proto3" json:"isTurn,omitempty"`
	TurnInfo             []*TurnInfo `protobuf:"bytes,2,rep,name=turnInfo,proto3" json:"turnInfo,omitempty"`
	Angle                int32       `protobuf:"varint,3,opt,name=angle,proto3" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TurnReq) Reset()         { *m = TurnReq{} }
func (m *TurnReq) String() string { return proto.CompactTextString(m) }
func (*TurnReq) ProtoMessage()    {}
func (*TurnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{36}
}

func (m *TurnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnReq.Unmarshal(m, b)
}
func (m *TurnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnReq.Marshal(b, m, deterministic)
}
func (m *TurnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnReq.Merge(m, src)
}
func (m *TurnReq) XXX_Size() int {
	return xxx_messageInfo_TurnReq.Size(m)
}
func (m *TurnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnReq.DiscardUnknown(m)
}

var xxx_messageInfo_TurnReq proto.InternalMessageInfo

func (m *TurnReq) GetIsTurn() bool {
	if m != nil {
		return m.IsTurn
	}
	return false
}

func (m *TurnReq) GetTurnInfo() []*TurnInfo {
	if m != nil {
		return m.TurnInfo
	}
	return nil
}

func (m *TurnReq) GetAngle() int32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

type TurnInfo struct {
	FishId               int32    `protobuf:"varint,1,opt,name=fishId,proto3" json:"fishId,omitempty"`
	Location             int32    `protobuf:"varint,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnInfo) Reset()         { *m = TurnInfo{} }
func (m *TurnInfo) String() string { return proto.CompactTextString(m) }
func (*TurnInfo) ProtoMessage()    {}
func (*TurnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{37}
}

func (m *TurnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnInfo.Unmarshal(m, b)
}
func (m *TurnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnInfo.Marshal(b, m, deterministic)
}
func (m *TurnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnInfo.Merge(m, src)
}
func (m *TurnInfo) XXX_Size() int {
	return xxx_messageInfo_TurnInfo.Size(m)
}
func (m *TurnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TurnInfo proto.InternalMessageInfo

func (m *TurnInfo) GetFishId() int32 {
	if m != nil {
		return m.FishId
	}
	return 0
}

func (m *TurnInfo) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

type BossForecastReq struct {
	BossId               string   `protobuf:"bytes,1,opt,name=bossId,proto3" json:"bossId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BossForecastReq) Reset()         { *m = BossForecastReq{} }
func (m *BossForecastReq) String() string { return proto.CompactTextString(m) }
func (*BossForecastReq) ProtoMessage()    {}
func (*BossForecastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{38}
}

func (m *BossForecastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BossForecastReq.Unmarshal(m, b)
}
func (m *BossForecastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BossForecastReq.Marshal(b, m, deterministic)
}
func (m *BossForecastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BossForecastReq.Merge(m, src)
}
func (m *BossForecastReq) XXX_Size() int {
	return xxx_messageInfo_BossForecastReq.Size(m)
}
func (m *BossForecastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BossForecastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BossForecastReq proto.InternalMessageInfo

func (m *BossForecastReq) GetBossId() string {
	if m != nil {
		return m.BossId
	}
	return ""
}

type SkillEndReq struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	CoinChange           int32    `protobuf:"varint,2,opt,name=coinChange,proto3" json:"coinChange,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillEndReq) Reset()         { *m = SkillEndReq{} }
func (m *SkillEndReq) String() string { return proto.CompactTextString(m) }
func (*SkillEndReq) ProtoMessage()    {}
func (*SkillEndReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f5d9ea564f351, []int{39}
}

func (m *SkillEndReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillEndReq.Unmarshal(m, b)
}
func (m *SkillEndReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillEndReq.Marshal(b, m, deterministic)
}
func (m *SkillEndReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillEndReq.Merge(m, src)
}
func (m *SkillEndReq) XXX_Size() int {
	return xxx_messageInfo_SkillEndReq.Size(m)
}
func (m *SkillEndReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillEndReq.DiscardUnknown(m)
}

var xxx_messageInfo_SkillEndReq proto.InternalMessageInfo

func (m *SkillEndReq) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *SkillEndReq) GetCoinChange() int32 {
	if m != nil {
		return m.CoinChange
	}
	return 0
}

func (m *SkillEndReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("msg.MsgId", MsgId_name, MsgId_value)
	proto.RegisterEnum("msg.ERROR", ERROR_name, ERROR_value)
	proto.RegisterEnum("msg.Type", Type_name, Type_value)
	proto.RegisterType((*Msg)(nil), "msg.Msg")
	proto.RegisterType((*TableInfo)(nil), "msg.TableInfo")
	proto.RegisterType((*UserInfo)(nil), "msg.UserInfo")
	proto.RegisterType((*Fish)(nil), "msg.Fish")
	proto.RegisterType((*Point)(nil), "msg.Point")
	proto.RegisterType((*EnterRoomReq)(nil), "msg.EnterRoomReq")
	proto.RegisterType((*EnterRoomRes)(nil), "msg.EnterRoomRes")
	proto.RegisterType((*ExistRoomReq)(nil), "msg.ExistRoomReq")
	proto.RegisterType((*ExistRoomRes)(nil), "msg.ExistRoomRes")
	proto.RegisterType((*ShootReq)(nil), "msg.ShootReq")
	proto.RegisterType((*ShootRes)(nil), "msg.ShootRes")
	proto.RegisterType((*HitReq)(nil), "msg.HitReq")
	proto.RegisterType((*HitRes)(nil), "msg.HitRes")
	proto.RegisterType((*FishTideForecastReq)(nil), "msg.FishTideForecastReq")
	proto.RegisterType((*FishTideReq)(nil), "msg.FishTideReq")
	proto.RegisterType((*UpgradeReq)(nil), "msg.UpgradeReq")
	proto.RegisterType((*UpgradeRes)(nil), "msg.UpgradeRes")
	proto.RegisterType((*RefreshFishReq)(nil), "msg.RefreshFishReq")
	proto.RegisterType((*DeadReq)(nil), "msg.DeadReq")
	proto.RegisterType((*DeadRes)(nil), "msg.DeadRes")
	proto.RegisterType((*ChangemModelReq)(nil), "msg.ChangemModelReq")
	proto.RegisterType((*ChangemModelRes)(nil), "msg.ChangemModelRes")
	proto.RegisterType((*ChangemLockFishReq)(nil), "msg.ChangemLockFishReq")
	proto.RegisterType((*ChangemLockFishRes)(nil), "msg.ChangemLockFishRes")
	proto.RegisterType((*ChangeCalculateRobot_Req)(nil), "msg.ChangeCalculateRobot_Req")
	proto.RegisterType((*ChangemSceneReq)(nil), "msg.ChangemSceneReq")
	proto.RegisterType((*SkillHitReq)(nil), "msg.SkillHitReq")
	proto.RegisterType((*SkillHitRes)(nil), "msg.SkillHitRes")
	proto.RegisterType((*DeadFish)(nil), "msg.DeadFish")
	proto.RegisterType((*SomeoneEnter_Req)(nil), "msg.SomeoneEnter_Req")
	proto.RegisterType((*FormationInfo)(nil), "msg.FormationInfo")
	proto.RegisterType((*TestReq)(nil), "msg.TestReq")
	proto.RegisterType((*FishtideEndReq)(nil), "msg.FishtideEndReq")
	proto.RegisterType((*Skill)(nil), "msg.Skill")
	proto.RegisterType((*SkillReq)(nil), "msg.SkillReq")
	proto.RegisterType((*SkillRes)(nil), "msg.SkillRes")
	proto.RegisterType((*TurnReq)(nil), "msg.TurnReq")
	proto.RegisterType((*TurnInfo)(nil), "msg.TurnInfo")
	proto.RegisterType((*BossForecastReq)(nil), "msg.BossForecastReq")
	proto.RegisterType((*SkillEndReq)(nil), "msg.SkillEndReq")
}

func init() { proto.RegisterFile("game_haiwangbuyu.proto", fileDescriptor_208f5d9ea564f351) }

var fileDescriptor_208f5d9ea564f351 = []byte{
	// 1778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x6f, 0xe3, 0xc8,
	0x11, 0x5e, 0x92, 0xa2, 0x1e, 0x25, 0x5b, 0xe6, 0xf6, 0x78, 0xbc, 0xdc, 0x89, 0x77, 0xe2, 0x65,
	0x80, 0x8d, 0x77, 0x12, 0x4c, 0x80, 0x49, 0x02, 0xec, 0x61, 0x91, 0x40, 0x96, 0x68, 0x5b, 0xb0,
	0x24, 0x1a, 0x4d, 0x19, 0x08, 0x92, 0x83, 0x41, 0x49, 0x2d, 0x89, 0x18, 0x89, 0xf4, 0xb0, 0x29,
	0xc7, 0x3e, 0xe4, 0x37, 0xe4, 0x75, 0xca, 0xff, 0xca, 0x29, 0xff, 0x20, 0x87, 0x5c, 0x73, 0x0e,
	0xaa, 0xbb, 0xf9, 0x90, 0xfc, 0x18, 0x64, 0x80, 0x3d, 0xb9, 0xbf, 0xaa, 0x62, 0x75, 0xbd, 0xab,
	0x2d, 0x38, 0x98, 0x07, 0x2b, 0x76, 0xbd, 0x08, 0xc2, 0x3f, 0x06, 0xd1, 0x7c, 0xbc, 0xbe, 0x5f,
	0xbf, 0xbd, 0x49, 0xe2, 0x34, 0x26, 0xc6, 0x8a, 0xcf, 0x9d, 0x0b, 0x30, 0x06, 0x7c, 0x4e, 0x6c,
	0xa8, 0xad, 0x82, 0x30, 0xea, 0xac, 0xa6, 0xb6, 0x76, 0xa4, 0x1d, 0x9b, 0x34, 0x83, 0xe4, 0x00,
	0xaa, 0x7c, 0x3d, 0x46, 0x86, 0x2e, 0x18, 0x0a, 0x11, 0x02, 0x95, 0xf1, 0x7a, 0x36, 0xb3, 0x8d,
	0x23, 0xed, 0x78, 0x87, 0x8a, 0xb3, 0xf3, 0x1f, 0x0d, 0x1a, 0xa3, 0x60, 0xbc, 0x64, 0xbd, 0x68,
	0x16, 0xa3, 0xce, 0x54, 0x80, 0x5c, 0xa7, 0x82, 0xe4, 0x10, 0x1a, 0xe2, 0x38, 0x0c, 0x56, 0x4c,
	0xa8, 0x6d, 0xd0, 0x82, 0x40, 0x7e, 0x01, 0xcd, 0x35, 0x67, 0x09, 0xea, 0x68, 0x27, 0x89, 0x6d,
	0x1c, 0x19, 0xc7, 0xcd, 0x77, 0xbb, 0x6f, 0x57, 0x7c, 0xfe, 0xf6, 0x4a, 0xd1, 0x69, 0x59, 0x82,
	0x7c, 0x0d, 0xd5, 0x59, 0xc8, 0x17, 0x8c, 0xdb, 0x15, 0x21, 0xdb, 0x10, 0xb2, 0xa7, 0x21, 0x5f,
	0x50, 0xc5, 0x40, 0x5b, 0xf8, 0x84, 0x45, 0x68, 0x8b, 0x29, 0x6d, 0x51, 0x90, 0xbc, 0x82, 0x3a,
	0xca, 0x8c, 0xc2, 0x29, 0xb3, 0xab, 0x47, 0xda, 0x71, 0x9d, 0xe6, 0x98, 0xbc, 0x06, 0xe0, 0x2c,
	0xb9, 0x65, 0xc9, 0x28, 0x5c, 0x31, 0xbb, 0x76, 0xa4, 0x1d, 0x1b, 0xb4, 0x44, 0x71, 0xfe, 0xab,
	0x43, 0x3d, 0x33, 0x09, 0x03, 0x25, 0x8c, 0x92, 0xde, 0x1a, 0x54, 0x21, 0xbc, 0x00, 0x4f, 0x25,
	0x5f, 0x73, 0x4c, 0x2c, 0x30, 0x38, 0xbb, 0x13, 0x31, 0x34, 0x29, 0x1e, 0x31, 0xac, 0x0b, 0x16,
	0x4c, 0xed, 0x8a, 0x90, 0x14, 0x67, 0xd4, 0x1c, 0xac, 0xe2, 0x75, 0x94, 0x0a, 0xdb, 0x0d, 0xaa,
	0x10, 0x3a, 0x35, 0x59, 0x04, 0x21, 0x5e, 0x59, 0x95, 0x4e, 0x29, 0x88, 0x77, 0x8e, 0xd7, 0xcb,
	0x25, 0x4b, 0xfb, 0xb7, 0xc2, 0x6c, 0x93, 0xe6, 0x18, 0x6f, 0x08, 0xd6, 0x69, 0x6c, 0xd7, 0x85,
	0xb3, 0xe2, 0x4c, 0xf6, 0xc1, 0xe4, 0x37, 0x8c, 0x4d, 0xed, 0x86, 0x20, 0x4a, 0x80, 0x92, 0xcb,
	0x78, 0xf2, 0xde, 0x06, 0x29, 0x89, 0x67, 0x0c, 0x09, 0xfe, 0xc5, 0xe0, 0xf6, 0xa6, 0x76, 0x53,
	0xe8, 0x2e, 0x51, 0xc8, 0x37, 0xd0, 0x9a, 0x04, 0xcb, 0xc9, 0x7a, 0x19, 0xa4, 0x8c, 0xc6, 0xe3,
	0x38, 0xb5, 0x77, 0xc4, 0xd7, 0x5b, 0x54, 0xb4, 0x3d, 0xe4, 0x52, 0x60, 0x57, 0x08, 0x64, 0x90,
	0x38, 0x50, 0xe5, 0xef, 0xc3, 0xe5, 0x92, 0xdb, 0x2d, 0x91, 0x4d, 0x10, 0xd9, 0xf4, 0x91, 0x44,
	0x15, 0xc7, 0xf9, 0xb7, 0x0e, 0x15, 0xbc, 0x90, 0xb4, 0x40, 0x0f, 0xb3, 0xf2, 0xd2, 0x43, 0xe9,
	0x78, 0x9c, 0x44, 0x22, 0x5f, 0xba, 0x08, 0x56, 0x8e, 0xc9, 0x31, 0x34, 0xf0, 0x7c, 0x19, 0x87,
	0x51, 0x2a, 0x42, 0x9e, 0xe9, 0x16, 0x14, 0x5a, 0x30, 0xc9, 0x6b, 0xa8, 0x2c, 0xc3, 0x88, 0xa9,
	0x72, 0x2a, 0x0b, 0x09, 0x3a, 0x16, 0x5c, 0x7a, 0x7f, 0x93, 0x15, 0x53, 0x4b, 0x15, 0x1c, 0x92,
	0xa8, 0x62, 0x60, 0xce, 0x42, 0xde, 0xc5, 0x4c, 0xca, 0xa2, 0x52, 0x08, 0xe9, 0x33, 0x19, 0xbb,
	0x9a, 0xc8, 0xb0, 0x42, 0x45, 0x06, 0xea, 0x47, 0xc6, 0xb1, 0x99, 0x65, 0xc0, 0x02, 0x23, 0x5a,
	0xaf, 0x44, 0x56, 0x4c, 0x8a, 0x47, 0x51, 0xc8, 0x18, 0x83, 0xde, 0x54, 0xa4, 0x05, 0x0b, 0x59,
	0x42, 0xf2, 0x1d, 0xec, 0xce, 0xe2, 0x64, 0x15, 0xa4, 0x61, 0x1c, 0x61, 0x41, 0x8a, 0xe4, 0x34,
	0xdf, 0x11, 0xd9, 0x0c, 0x65, 0x0e, 0xdd, 0x14, 0xc4, 0x76, 0x44, 0xdf, 0x7b, 0xd1, 0x94, 0xdd,
	0x89, 0x74, 0x99, 0xb4, 0x20, 0x38, 0x3f, 0x01, 0x53, 0x46, 0x65, 0x07, 0xb4, 0x3b, 0x15, 0x6a,
	0xed, 0x0e, 0xd1, 0xbd, 0x1a, 0x09, 0xda, 0xbd, 0x73, 0x02, 0x3b, 0x6e, 0x94, 0xb2, 0x84, 0xc6,
	0xf1, 0x8a, 0xb2, 0x0f, 0x9f, 0xd2, 0x0c, 0xce, 0xf7, 0x1b, 0x3a, 0x38, 0xf9, 0xb9, 0x9a, 0x12,
	0xc2, 0x19, 0x4d, 0x38, 0xd3, 0x12, 0xce, 0xe4, 0x23, 0x86, 0x16, 0x02, 0xce, 0x37, 0xb0, 0xe3,
	0xde, 0x85, 0x3c, 0xfd, 0x88, 0x05, 0x5b, 0x72, 0xfc, 0x49, 0xb9, 0x29, 0xd4, 0xfd, 0x45, 0x1c,
	0xa7, 0xcf, 0x79, 0x73, 0x04, 0xe6, 0x8d, 0xa8, 0x26, 0xfd, 0x41, 0x35, 0x49, 0x06, 0xb6, 0x8b,
	0x6c, 0xbc, 0xd1, 0xfd, 0x0d, 0x53, 0x7d, 0x5e, 0xa2, 0x94, 0x6e, 0xe1, 0x3f, 0xe0, 0x2d, 0xb7,
	0x50, 0x3d, 0x0f, 0x9f, 0xf5, 0xa4, 0x28, 0x4b, 0x35, 0xe5, 0x55, 0x59, 0x96, 0x07, 0x89, 0xb1,
	0x35, 0x48, 0x8e, 0xa0, 0x19, 0xf2, 0x4b, 0x16, 0xb1, 0x34, 0x09, 0x52, 0x26, 0x26, 0x56, 0x9d,
	0x96, 0x49, 0xce, 0x9f, 0x35, 0x75, 0xf1, 0xd3, 0xce, 0x7d, 0x0d, 0x15, 0xbc, 0x4a, 0xf9, 0x26,
	0xa7, 0x3c, 0x36, 0x8a, 0x98, 0xde, 0x82, 0x85, 0x4d, 0xf0, 0x9e, 0xdd, 0x8b, 0xeb, 0x1b, 0x14,
	0x8f, 0xe8, 0xef, 0x24, 0x0e, 0xa3, 0xce, 0x22, 0x88, 0xe6, 0xf2, 0x62, 0x93, 0x96, 0x28, 0x72,
	0xb8, 0xb8, 0xab, 0x9b, 0xf4, 0x3e, 0x9b, 0xf6, 0x0a, 0x3a, 0x2f, 0xe1, 0xc5, 0xa9, 0x9a, 0xee,
	0xa7, 0x71, 0xc2, 0x26, 0x01, 0xc7, 0xb0, 0x38, 0xbf, 0x85, 0x66, 0x46, 0xc6, 0x28, 0x1d, 0x42,
	0x23, 0xef, 0x10, 0x55, 0xf1, 0x05, 0x41, 0x8c, 0x45, 0x9c, 0x0e, 0x32, 0x52, 0xe2, 0xec, 0x38,
	0x00, 0x57, 0x37, 0xf3, 0x24, 0x90, 0xdf, 0xef, 0x83, 0x19, 0xf2, 0xf6, 0x54, 0xfa, 0x5a, 0xa7,
	0x12, 0x38, 0xbf, 0x2a, 0xc9, 0x3c, 0x1d, 0x90, 0x16, 0xe8, 0xcb, 0x5b, 0xa5, 0x5b, 0x5f, 0xde,
	0x3a, 0x31, 0xb4, 0x28, 0x9b, 0x25, 0x8c, 0x2f, 0x44, 0x48, 0xd8, 0x07, 0xf2, 0x95, 0x0a, 0x99,
	0xb6, 0xbd, 0xec, 0x64, 0xb8, 0x1c, 0xa8, 0xc6, 0xb3, 0x19, 0x67, 0x58, 0x2f, 0xdb, 0xe3, 0x4b,
	0x71, 0x30, 0xad, 0x21, 0xf7, 0xd7, 0xab, 0x55, 0x1c, 0x89, 0xb8, 0xd6, 0x69, 0x8e, 0x9d, 0x2f,
	0xa1, 0x86, 0x09, 0xc0, 0x9b, 0xb6, 0xa6, 0x6b, 0xc1, 0xe2, 0x0f, 0x58, 0x1d, 0xd8, 0x93, 0xc1,
	0x5f, 0x0d, 0xe2, 0x29, 0x5b, 0x3e, 0x57, 0x6b, 0xf8, 0xd6, 0x40, 0x99, 0xbc, 0xd8, 0x32, 0xf8,
	0x50, 0x09, 0xff, 0x04, 0x25, 0x5d, 0x20, 0x4a, 0x49, 0x5f, 0xad, 0xa5, 0x4f, 0x28, 0xfc, 0x47,
	0xb5, 0xf0, 0xff, 0x5b, 0xcb, 0x3b, 0xb0, 0xa5, 0x96, 0xce, 0xc6, 0xf6, 0xbb, 0x7e, 0x6e, 0x40,
	0xfd, 0x2c, 0x0f, 0x82, 0x8f, 0x4f, 0x14, 0x14, 0x2d, 0xbd, 0x5e, 0xb4, 0x8d, 0xd7, 0x8b, 0xf3,
	0x77, 0x0d, 0x9a, 0x62, 0x35, 0x16, 0xfd, 0xad, 0x0c, 0xd1, 0x36, 0xd6, 0x4b, 0x69, 0x6d, 0xe8,
	0x9b, 0x6b, 0xc3, 0x86, 0x9a, 0x94, 0xe1, 0xe2, 0xa5, 0x65, 0xd2, 0x0c, 0x16, 0x73, 0xa7, 0xf2,
	0xd4, 0xdc, 0x29, 0x5c, 0x30, 0x37, 0x5c, 0xf8, 0xd7, 0x86, 0x55, 0x9c, 0xfc, 0xb4, 0xb8, 0x43,
	0x2b, 0xbd, 0xe6, 0xf2, 0x3e, 0xcf, 0xaf, 0x3c, 0xc8, 0x5f, 0x72, 0xba, 0xb0, 0xa5, 0xfc, 0x7c,
	0x53, 0xe6, 0x1b, 0x9b, 0xe6, 0x17, 0x26, 0x54, 0x1e, 0x1f, 0x9a, 0xe6, 0x33, 0x43, 0xb3, 0x34,
	0x44, 0xaa, 0x0f, 0x86, 0xc8, 0x13, 0x9b, 0xda, 0xf9, 0x0e, 0xea, 0x99, 0xe1, 0x5b, 0xe1, 0x36,
	0x37, 0xb6, 0xf9, 0x24, 0x4e, 0xe4, 0x8c, 0xd0, 0xa8, 0x04, 0x4e, 0x07, 0x2c, 0x3f, 0x5e, 0xb1,
	0x38, 0x62, 0x62, 0xcf, 0x89, 0x2a, 0xd8, 0x7a, 0xec, 0x6a, 0x1f, 0x7b, 0xec, 0x3a, 0x7f, 0x82,
	0xdd, 0x8d, 0x65, 0x8e, 0x36, 0x24, 0xc1, 0x34, 0x5c, 0x73, 0x61, 0x83, 0x4e, 0x15, 0xc2, 0x21,
	0x16, 0xdf, 0xb2, 0x64, 0x79, 0x1f, 0x46, 0x73, 0x61, 0x87, 0x4e, 0x0b, 0x02, 0x5a, 0x18, 0x44,
	0xf3, 0xa5, 0xdc, 0x16, 0x3a, 0x95, 0xe0, 0xe3, 0x29, 0x77, 0x7e, 0x0d, 0xb5, 0x11, 0x13, 0x43,
	0x13, 0xe7, 0xe0, 0x6c, 0x1d, 0x4d, 0x94, 0xeb, 0xe2, 0xbc, 0xd5, 0x08, 0x45, 0xd0, 0x2c, 0x68,
	0x61, 0xc0, 0xd2, 0x70, 0xca, 0xdc, 0x08, 0x67, 0x8b, 0xf3, 0x0f, 0x0d, 0x4c, 0x51, 0x23, 0xe5,
	0xe4, 0x6a, 0x9b, 0xc9, 0xc5, 0x31, 0x85, 0x91, 0xba, 0x0d, 0x96, 0xd9, 0x6b, 0x2e, 0xc3, 0xb8,
	0x15, 0xa6, 0xeb, 0x44, 0x98, 0x6f, 0x50, 0x3c, 0xe2, 0xdd, 0x93, 0x45, 0x10, 0x4d, 0xb2, 0x8d,
	0xa0, 0x10, 0xba, 0xba, 0x0c, 0x57, 0x61, 0xaa, 0x76, 0x81, 0x04, 0xa8, 0x7b, 0x19, 0xf0, 0x54,
	0xbc, 0x14, 0xab, 0x52, 0x77, 0x86, 0x9d, 0xef, 0xa1, 0x2e, 0xdf, 0x9b, 0xaa, 0xf7, 0x1e, 0xb7,
	0xee, 0x89, 0x62, 0x2d, 0x7d, 0xcd, 0x3f, 0xe1, 0xeb, 0x31, 0xd4, 0x46, 0xeb, 0x24, 0x52, 0xcd,
	0x1c, 0x72, 0x04, 0x6a, 0x8f, 0x28, 0x44, 0xbe, 0x85, 0x7a, 0xba, 0x4e, 0xe4, 0x23, 0x4f, 0x2f,
	0x15, 0xcc, 0x48, 0x11, 0x69, 0xce, 0xde, 0x4c, 0xb3, 0xa9, 0xd2, 0xec, 0xfc, 0x06, 0xea, 0x99,
	0xec, 0x93, 0x25, 0x8c, 0xf1, 0x89, 0x27, 0x72, 0x05, 0xca, 0x91, 0x91, 0x63, 0xe7, 0x5b, 0xd8,
	0x3b, 0x89, 0x39, 0x2f, 0x6d, 0x50, 0x54, 0x33, 0x8e, 0x39, 0x2f, 0x06, 0x8f, 0x44, 0xce, 0xb5,
	0x9a, 0x04, 0x32, 0xeb, 0xcf, 0xc4, 0x63, 0xb3, 0x1d, 0xf5, 0xc7, 0xda, 0x51, 0x35, 0xba, 0x51,
	0x6e, 0xf4, 0x37, 0xff, 0xac, 0x80, 0x39, 0xe0, 0xf3, 0xde, 0x94, 0xd4, 0xa1, 0xf2, 0x7b, 0x97,
	0x7a, 0xd6, 0x67, 0xe4, 0x73, 0xd8, 0xed, 0x0d, 0x47, 0xde, 0x35, 0xf5, 0xbc, 0x01, 0x76, 0x99,
	0xa5, 0x6d, 0x93, 0xb8, 0xa5, 0x13, 0x02, 0x2d, 0xf7, 0x77, 0x3d, 0x7f, 0x54, 0x88, 0x19, 0x0f,
	0x68, 0xdc, 0xaa, 0x90, 0x5d, 0x68, 0xf8, 0xe7, 0x9e, 0x37, 0x12, 0x22, 0x66, 0x19, 0x72, 0xab,
	0x4a, 0x9a, 0x50, 0x3b, 0xef, 0x49, 0x5e, 0xad, 0x00, 0xdc, 0xaa, 0x13, 0x0b, 0x76, 0x4e, 0x7b,
	0xfe, 0xf9, 0xa8, 0xd7, 0x75, 0x05, 0xbb, 0x41, 0x6c, 0xd8, 0xcf, 0x28, 0xa7, 0x1e, 0x75, 0x3b,
	0x6d, 0x5f, 0x7e, 0x08, 0x64, 0x0f, 0x9a, 0x57, 0x97, 0x67, 0xb4, 0xad, 0x44, 0x9b, 0x9b, 0x04,
	0x6e, 0xed, 0x90, 0x17, 0xb0, 0x47, 0xdd, 0x53, 0xea, 0xfa, 0xe7, 0xa8, 0x42, 0x48, 0xed, 0x92,
	0x1d, 0xa8, 0x77, 0xdd, 0x76, 0x57, 0xa0, 0x56, 0x09, 0x71, 0x6b, 0x0f, 0x3f, 0xe8, 0x9c, 0xb7,
	0x87, 0x67, 0xee, 0xc0, 0xeb, 0xba, 0x7d, 0x21, 0x62, 0x3d, 0x24, 0x72, 0xeb, 0x73, 0x72, 0x00,
	0x44, 0x12, 0xfb, 0x5e, 0xe7, 0x22, 0xd7, 0x4e, 0x1e, 0xa5, 0x73, 0xeb, 0x05, 0x39, 0x04, 0x5b,
	0xd2, 0x3b, 0xed, 0x7e, 0xe7, 0xaa, 0xdf, 0x1e, 0xb9, 0xd4, 0x3b, 0x51, 0xf1, 0xd9, 0x2f, 0xae,
	0xf0, 0x3b, 0xee, 0x50, 0xba, 0xf3, 0x12, 0x63, 0xe1, 0x5f, 0xf4, 0xfa, 0xfd, 0x2c, 0x54, 0x07,
	0x5b, 0x14, 0x6e, 0x7d, 0x41, 0xf6, 0xc1, 0xf2, 0xbd, 0x81, 0xeb, 0x0d, 0x5d, 0x77, 0x38, 0x72,
	0xa9, 0x90, 0xb3, 0xd1, 0xa9, 0x91, 0xab, 0xe2, 0xf4, 0x25, 0x2a, 0xcf, 0x22, 0xe8, 0x0e, 0xa5,
	0xdf, 0xaf, 0x44, 0x46, 0x50, 0x95, 0x80, 0x3f, 0x2a, 0x43, 0x6e, 0x1d, 0x0a, 0x05, 0x57, 0x74,
	0x28, 0x98, 0x5f, 0xe1, 0x25, 0x27, 0x9e, 0xef, 0x6f, 0x84, 0xff, 0x75, 0x6e, 0x4c, 0xa6, 0xf3,
	0xc7, 0x6f, 0x22, 0x30, 0x5d, 0x4a, 0x3d, 0x8a, 0x85, 0x23, 0x0e, 0xd7, 0x1d, 0xaf, 0xeb, 0x5e,
	0x7b, 0x17, 0xd6, 0x67, 0xe4, 0x10, 0xbe, 0x28, 0x91, 0x86, 0xde, 0xe8, 0x1a, 0x4b, 0x0b, 0x2b,
	0xc6, 0xfa, 0xcb, 0x90, 0xbc, 0x82, 0x97, 0x5b, 0x5c, 0x77, 0xe8, 0x5d, 0x9d, 0x9d, 0x5b, 0x7f,
	0x1d, 0x12, 0x1b, 0x5e, 0x94, 0x78, 0x7d, 0xd7, 0xf7, 0xaf, 0x07, 0xbd, 0xa1, 0xf5, 0xb7, 0xe1,
	0x9b, 0x3f, 0x40, 0x05, 0xff, 0x73, 0x14, 0x45, 0x4c, 0x5d, 0x2c, 0xe2, 0x06, 0x98, 0xfe, 0xa0,
	0xdd, 0xef, 0x5b, 0x1a, 0x01, 0xa8, 0x0e, 0x7a, 0xdd, 0x6e, 0xdf, 0xb5, 0x74, 0x52, 0x03, 0xe3,
	0xa4, 0x77, 0x66, 0x19, 0x28, 0x89, 0x9e, 0x58, 0x15, 0x3c, 0x5d, 0xf6, 0xfa, 0xae, 0x65, 0xe2,
	0xe9, 0xa2, 0x37, 0x3c, 0x93, 0x65, 0xe9, 0x5f, 0xba, 0x9d, 0x5e, 0xbb, 0x6f, 0xc1, 0xb8, 0x2a,
	0x7e, 0xf0, 0xf9, 0xe5, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xe3, 0x85, 0x22, 0x0a, 0x12,
	0x00, 0x00,
}
