// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yhhwd.proto

package yhhwd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//枚举消息类型
type MsgIDC2S int32

const (
	MsgIDC2S_STARTID  MsgIDC2S = 0
	MsgIDC2S_AskSence MsgIDC2S = 1
	MsgIDC2S_Bet      MsgIDC2S = 2
	MsgIDC2S_Test     MsgIDC2S = 3
)

var MsgIDC2S_name = map[int32]string{
	0: "STARTID",
	1: "AskSence",
	2: "Bet",
	3: "Test",
}

var MsgIDC2S_value = map[string]int32{
	"STARTID":  0,
	"AskSence": 1,
	"Bet":      2,
	"Test":     3,
}

func (x MsgIDC2S) String() string {
	return proto.EnumName(MsgIDC2S_name, int32(x))
}

func (MsgIDC2S) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{0}
}

//枚举消息类型
type ReMsgIDS2C int32

const (
	ReMsgIDS2C_RESTARTID ReMsgIDS2C = 0
	ReMsgIDS2C_SenceID   ReMsgIDS2C = 1
	ReMsgIDS2C_BetRet    ReMsgIDS2C = 2
	ReMsgIDS2C_BetFailID ReMsgIDS2C = 3
)

var ReMsgIDS2C_name = map[int32]string{
	0: "RESTARTID",
	1: "SenceID",
	2: "BetRet",
	3: "BetFailID",
}

var ReMsgIDS2C_value = map[string]int32{
	"RESTARTID": 0,
	"SenceID":   1,
	"BetRet":    2,
	"BetFailID": 3,
}

func (x ReMsgIDS2C) String() string {
	return proto.EnumName(ReMsgIDS2C_name, int32(x))
}

func (ReMsgIDS2C) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{1}
}

type UserBet struct {
	BetMoney             int32    `protobuf:"varint,1,opt,name=BetMoney,proto3" json:"BetMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBet) Reset()         { *m = UserBet{} }
func (m *UserBet) String() string { return proto.CompactTextString(m) }
func (*UserBet) ProtoMessage()    {}
func (*UserBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{0}
}

func (m *UserBet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBet.Unmarshal(m, b)
}
func (m *UserBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBet.Marshal(b, m, deterministic)
}
func (m *UserBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBet.Merge(m, src)
}
func (m *UserBet) XXX_Size() int {
	return xxx_messageInfo_UserBet.Size(m)
}
func (m *UserBet) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBet.DiscardUnknown(m)
}

var xxx_messageInfo_UserBet proto.InternalMessageInfo

func (m *UserBet) GetBetMoney() int32 {
	if m != nil {
		return m.BetMoney
	}
	return 0
}

type BetFail struct {
	FailID               int32    `protobuf:"varint,1,opt,name=FailID,proto3" json:"FailID,omitempty"`
	Reson                string   `protobuf:"bytes,2,opt,name=Reson,proto3" json:"Reson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetFail) Reset()         { *m = BetFail{} }
func (m *BetFail) String() string { return proto.CompactTextString(m) }
func (*BetFail) ProtoMessage()    {}
func (*BetFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{1}
}

func (m *BetFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetFail.Unmarshal(m, b)
}
func (m *BetFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetFail.Marshal(b, m, deterministic)
}
func (m *BetFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetFail.Merge(m, src)
}
func (m *BetFail) XXX_Size() int {
	return xxx_messageInfo_BetFail.Size(m)
}
func (m *BetFail) XXX_DiscardUnknown() {
	xxx_messageInfo_BetFail.DiscardUnknown(m)
}

var xxx_messageInfo_BetFail proto.InternalMessageInfo

func (m *BetFail) GetFailID() int32 {
	if m != nil {
		return m.FailID
	}
	return 0
}

func (m *BetFail) GetReson() string {
	if m != nil {
		return m.Reson
	}
	return ""
}

type LineInfo struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Gold                 int64    `protobuf:"varint,3,opt,name=Gold,proto3" json:"Gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineInfo) Reset()         { *m = LineInfo{} }
func (m *LineInfo) String() string { return proto.CompactTextString(m) }
func (*LineInfo) ProtoMessage()    {}
func (*LineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{2}
}

func (m *LineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineInfo.Unmarshal(m, b)
}
func (m *LineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineInfo.Marshal(b, m, deterministic)
}
func (m *LineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineInfo.Merge(m, src)
}
func (m *LineInfo) XXX_Size() int {
	return xxx_messageInfo_LineInfo.Size(m)
}
func (m *LineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LineInfo proto.InternalMessageInfo

func (m *LineInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LineInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LineInfo) GetGold() int64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

type BetRes struct {
	UserGold             int64        `protobuf:"varint,1,opt,name=UserGold,proto3" json:"UserGold,omitempty"`
	AllResArr            []*SingleRes `protobuf:"bytes,2,rep,name=AllResArr,proto3" json:"AllResArr,omitempty"`
	BEnterFree           bool         `protobuf:"varint,6,opt,name=bEnterFree,proto3" json:"bEnterFree,omitempty"`
	FreeGames            int32        `protobuf:"varint,7,opt,name=FreeGames,proto3" json:"FreeGames,omitempty"`
	Cheat                int32        `protobuf:"varint,10,opt,name=Cheat,proto3" json:"Cheat,omitempty"`
	BloodPool            int64        `protobuf:"varint,11,opt,name=BloodPool,proto3" json:"BloodPool,omitempty"`
	Count                int32        `protobuf:"varint,12,opt,name=Count,proto3" json:"Count,omitempty"`
	UserTotalWin         int64        `protobuf:"varint,13,opt,name=UserTotalWin,proto3" json:"UserTotalWin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BetRes) Reset()         { *m = BetRes{} }
func (m *BetRes) String() string { return proto.CompactTextString(m) }
func (*BetRes) ProtoMessage()    {}
func (*BetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{3}
}

func (m *BetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetRes.Unmarshal(m, b)
}
func (m *BetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetRes.Marshal(b, m, deterministic)
}
func (m *BetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetRes.Merge(m, src)
}
func (m *BetRes) XXX_Size() int {
	return xxx_messageInfo_BetRes.Size(m)
}
func (m *BetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BetRes.DiscardUnknown(m)
}

var xxx_messageInfo_BetRes proto.InternalMessageInfo

func (m *BetRes) GetUserGold() int64 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *BetRes) GetAllResArr() []*SingleRes {
	if m != nil {
		return m.AllResArr
	}
	return nil
}

func (m *BetRes) GetBEnterFree() bool {
	if m != nil {
		return m.BEnterFree
	}
	return false
}

func (m *BetRes) GetFreeGames() int32 {
	if m != nil {
		return m.FreeGames
	}
	return 0
}

func (m *BetRes) GetCheat() int32 {
	if m != nil {
		return m.Cheat
	}
	return 0
}

func (m *BetRes) GetBloodPool() int64 {
	if m != nil {
		return m.BloodPool
	}
	return 0
}

func (m *BetRes) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *BetRes) GetUserTotalWin() int64 {
	if m != nil {
		return m.UserTotalWin
	}
	return 0
}

type SingleRes struct {
	IconArr              []int32  `protobuf:"varint,2,rep,packed,name=IconArr,proto3" json:"IconArr,omitempty"`
	Odds                 int32    `protobuf:"varint,3,opt,name=Odds,proto3" json:"Odds,omitempty"`
	Gold                 int64    `protobuf:"varint,4,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Line                 []int32  `protobuf:"varint,5,rep,packed,name=Line,proto3" json:"Line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRes) Reset()         { *m = SingleRes{} }
func (m *SingleRes) String() string { return proto.CompactTextString(m) }
func (*SingleRes) ProtoMessage()    {}
func (*SingleRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{4}
}

func (m *SingleRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRes.Unmarshal(m, b)
}
func (m *SingleRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRes.Marshal(b, m, deterministic)
}
func (m *SingleRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRes.Merge(m, src)
}
func (m *SingleRes) XXX_Size() int {
	return xxx_messageInfo_SingleRes.Size(m)
}
func (m *SingleRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRes.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRes proto.InternalMessageInfo

func (m *SingleRes) GetIconArr() []int32 {
	if m != nil {
		return m.IconArr
	}
	return nil
}

func (m *SingleRes) GetOdds() int32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func (m *SingleRes) GetGold() int64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *SingleRes) GetLine() []int32 {
	if m != nil {
		return m.Line
	}
	return nil
}

//场景消息
type Sence struct {
	Gold                 int64    `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"`
	BetValue             []int32  `protobuf:"varint,2,rep,packed,name=BetValue,proto3" json:"BetValue,omitempty"`
	JackpotGold          int64    `protobuf:"varint,3,opt,name=JackpotGold,proto3" json:"JackpotGold,omitempty"`
	FreeGameTimes        int32    `protobuf:"varint,4,opt,name=FreeGameTimes,proto3" json:"FreeGameTimes,omitempty"`
	FreeGameGold         int64    `protobuf:"varint,5,opt,name=FreeGameGold,proto3" json:"FreeGameGold,omitempty"`
	LastBetIndex         int32    `protobuf:"varint,8,opt,name=LastBetIndex,proto3" json:"LastBetIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sence) Reset()         { *m = Sence{} }
func (m *Sence) String() string { return proto.CompactTextString(m) }
func (*Sence) ProtoMessage()    {}
func (*Sence) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{5}
}

func (m *Sence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sence.Unmarshal(m, b)
}
func (m *Sence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sence.Marshal(b, m, deterministic)
}
func (m *Sence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sence.Merge(m, src)
}
func (m *Sence) XXX_Size() int {
	return xxx_messageInfo_Sence.Size(m)
}
func (m *Sence) XXX_DiscardUnknown() {
	xxx_messageInfo_Sence.DiscardUnknown(m)
}

var xxx_messageInfo_Sence proto.InternalMessageInfo

func (m *Sence) GetGold() int64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *Sence) GetBetValue() []int32 {
	if m != nil {
		return m.BetValue
	}
	return nil
}

func (m *Sence) GetJackpotGold() int64 {
	if m != nil {
		return m.JackpotGold
	}
	return 0
}

func (m *Sence) GetFreeGameTimes() int32 {
	if m != nil {
		return m.FreeGameTimes
	}
	return 0
}

func (m *Sence) GetFreeGameGold() int64 {
	if m != nil {
		return m.FreeGameGold
	}
	return 0
}

func (m *Sence) GetLastBetIndex() int32 {
	if m != nil {
		return m.LastBetIndex
	}
	return 0
}

type TestMsg struct {
	Result               int32    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMsg) Reset()         { *m = TestMsg{} }
func (m *TestMsg) String() string { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()    {}
func (*TestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8f6930881a753c, []int{6}
}

func (m *TestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMsg.Unmarshal(m, b)
}
func (m *TestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMsg.Marshal(b, m, deterministic)
}
func (m *TestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg.Merge(m, src)
}
func (m *TestMsg) XXX_Size() int {
	return xxx_messageInfo_TestMsg.Size(m)
}
func (m *TestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg proto.InternalMessageInfo

func (m *TestMsg) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("MsgIDC2S", MsgIDC2S_name, MsgIDC2S_value)
	proto.RegisterEnum("ReMsgIDS2C", ReMsgIDS2C_name, ReMsgIDS2C_value)
	proto.RegisterType((*UserBet)(nil), "UserBet")
	proto.RegisterType((*BetFail)(nil), "BetFail")
	proto.RegisterType((*LineInfo)(nil), "LineInfo")
	proto.RegisterType((*BetRes)(nil), "BetRes")
	proto.RegisterType((*SingleRes)(nil), "SingleRes")
	proto.RegisterType((*Sence)(nil), "Sence")
	proto.RegisterType((*TestMsg)(nil), "TestMsg")
}

func init() { proto.RegisterFile("yhhwd.proto", fileDescriptor_fa8f6930881a753c) }

var fileDescriptor_fa8f6930881a753c = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x9b, 0xa6, 0x49, 0xa6, 0xad, 0x14, 0x59, 0x08, 0x59, 0x08, 0xa1, 0x10, 0x81, 0x14,
	0xed, 0x61, 0x0f, 0xe5, 0x00, 0xd7, 0xa6, 0xdd, 0x5d, 0x65, 0xb5, 0x15, 0xc8, 0x2d, 0x70, 0xce,
	0x36, 0x43, 0x5b, 0x6d, 0xb0, 0x57, 0xb1, 0x2b, 0xd8, 0x5f, 0xc8, 0x7f, 0xe2, 0x84, 0xec, 0x7c,
	0xf6, 0x14, 0xbf, 0xd7, 0x79, 0xd3, 0x37, 0xcf, 0x63, 0x98, 0x3c, 0x1f, 0x0e, 0xbf, 0x8b, 0xab,
	0xa7, 0x4a, 0x6a, 0x19, 0x7f, 0x00, 0xef, 0x9b, 0xc2, 0x2a, 0x45, 0x4d, 0x5f, 0x83, 0x9f, 0xa2,
	0x5e, 0x4b, 0x81, 0xcf, 0x8c, 0x44, 0x24, 0x71, 0x79, 0x87, 0xe3, 0x4f, 0xe0, 0xa5, 0xa8, 0x6f,
	0xf2, 0x63, 0x49, 0x5f, 0xc1, 0xd8, 0x7c, 0xb3, 0x55, 0x53, 0xd4, 0x20, 0xfa, 0x12, 0x5c, 0x8e,
	0x4a, 0x0a, 0x76, 0x11, 0x91, 0x24, 0xe0, 0x35, 0x88, 0xef, 0xc0, 0xbf, 0x3f, 0x0a, 0xcc, 0xc4,
	0x4f, 0x69, 0x2a, 0x32, 0x51, 0xe0, 0x9f, 0x46, 0x58, 0x03, 0xc3, 0x2e, 0xe5, 0x49, 0x68, 0xab,
	0x73, 0x79, 0x0d, 0x28, 0x85, 0xd1, 0xad, 0x2c, 0x0b, 0xe6, 0x44, 0x24, 0x71, 0xb8, 0x3d, 0xc7,
	0xff, 0x08, 0x8c, 0x53, 0xd4, 0x1c, 0x95, 0xf1, 0x6a, 0x6c, 0xdb, 0x12, 0x62, 0x4b, 0x3a, 0x4c,
	0x13, 0x08, 0x16, 0x65, 0xc9, 0x51, 0x2d, 0xaa, 0x8a, 0x5d, 0x44, 0x4e, 0x32, 0x99, 0xc3, 0xd5,
	0xe6, 0x28, 0xf6, 0x25, 0x72, 0x54, 0xbc, 0xff, 0x91, 0xbe, 0x05, 0x78, 0xb8, 0x16, 0x1a, 0xab,
	0x9b, 0x0a, 0x91, 0x8d, 0x23, 0x92, 0xf8, 0x7c, 0xc0, 0xd0, 0x37, 0x10, 0x98, 0xef, 0x6d, 0xfe,
	0x0b, 0x15, 0xf3, 0xac, 0xbd, 0x9e, 0xb0, 0xc6, 0x0f, 0x98, 0x6b, 0x06, 0x8d, 0x71, 0x03, 0x8c,
	0x26, 0x2d, 0xa5, 0x2c, 0xbe, 0x4a, 0x59, 0xb2, 0x89, 0xb5, 0xd6, 0x13, 0xfd, 0xb0, 0xd3, 0xe1,
	0xb0, 0x31, 0x4c, 0x8d, 0xfb, 0xad, 0xd4, 0x79, 0xf9, 0xe3, 0x28, 0xd8, 0xcc, 0xca, 0xce, 0xb8,
	0x38, 0x87, 0xa0, 0x9b, 0x81, 0x32, 0xf0, 0xb2, 0x9d, 0x14, 0xed, 0x80, 0x2e, 0x6f, 0xa1, 0xc9,
	0xed, 0x4b, 0x51, 0x28, 0x9b, 0x9b, 0xcb, 0xed, 0xb9, 0xcb, 0x72, 0xd4, 0x67, 0x69, 0x38, 0x73,
	0x2f, 0xcc, 0xb5, 0x72, 0x7b, 0x8e, 0xff, 0x12, 0x70, 0x37, 0x28, 0x76, 0xd8, 0x29, 0xc8, 0x40,
	0x51, 0xaf, 0xc7, 0xf7, 0xbc, 0x3c, 0x61, 0xf3, 0xa7, 0x1d, 0xa6, 0x11, 0x4c, 0xee, 0xf2, 0xdd,
	0xe3, 0x93, 0xd4, 0x83, 0x4b, 0x1b, 0x52, 0xf4, 0x3d, 0xcc, 0xda, 0xe4, 0xb6, 0x47, 0x13, 0xe7,
	0xc8, 0x1a, 0x3c, 0x27, 0x4d, 0x10, 0x2d, 0x61, 0x1b, 0xb9, 0x75, 0x10, 0x43, 0xce, 0xd4, 0xdc,
	0xe7, 0x4a, 0xa7, 0xa8, 0xeb, 0x65, 0xf2, 0x6d, 0xa3, 0x33, 0x2e, 0x7e, 0x07, 0xde, 0x16, 0x95,
	0x5e, 0xab, 0xbd, 0x59, 0x57, 0x8e, 0xea, 0x54, 0xea, 0x76, 0x5d, 0x6b, 0x74, 0xf9, 0x19, 0xfc,
	0xb5, 0xda, 0x67, 0xab, 0xe5, 0x7c, 0x43, 0x27, 0xe0, 0x6d, 0xb6, 0x0b, 0xbe, 0xcd, 0x56, 0xe1,
	0x0b, 0x3a, 0x05, 0x7f, 0xa1, 0x1e, 0x6d, 0x0e, 0x21, 0xa1, 0x1e, 0x38, 0x29, 0xea, 0xf0, 0x82,
	0xfa, 0x30, 0x32, 0x2d, 0x43, 0xe7, 0x72, 0x09, 0xc0, 0xd1, 0x6a, 0x37, 0xf3, 0x25, 0x9d, 0x41,
	0xc0, 0xaf, 0x7b, 0xb5, 0x69, 0x65, 0xa4, 0xd9, 0x2a, 0x24, 0x14, 0x9a, 0x7d, 0x35, 0xfa, 0x19,
	0x04, 0xcd, 0x0b, 0xca, 0x56, 0xa1, 0xf3, 0x30, 0xb6, 0xcf, 0xef, 0xe3, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0x61, 0x57, 0x9a, 0x8d, 0x03, 0x00, 0x00,
}
