// Code generated by protoc-gen-go. DO NOT EDIT.
// source: run_faster.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端到服务器发送消息的类型
type ReceiveMessageType int32

const (
	ReceiveMessageType_C2SStartID      ReceiveMessageType = 0
	ReceiveMessageType_C2STips         ReceiveMessageType = 1
	ReceiveMessageType_C2SPutCards     ReceiveMessageType = 2
	ReceiveMessageType_C2SCancelHangUp ReceiveMessageType = 3
	ReceiveMessageType_C2SDemandCards  ReceiveMessageType = 4
)

var ReceiveMessageType_name = map[int32]string{
	0: "C2SStartID",
	1: "C2STips",
	2: "C2SPutCards",
	3: "C2SCancelHangUp",
	4: "C2SDemandCards",
}

var ReceiveMessageType_value = map[string]int32{
	"C2SStartID":      0,
	"C2STips":         1,
	"C2SPutCards":     2,
	"C2SCancelHangUp": 3,
	"C2SDemandCards":  4,
}

func (x ReceiveMessageType) String() string {
	return proto.EnumName(ReceiveMessageType_name, int32(x))
}

func (ReceiveMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{0}
}

// 服务器发送给客户端的消息类型
type SendToClientMessageType int32

const (
	SendToClientMessageType_S2CStartID       SendToClientMessageType = 0
	SendToClientMessageType_S2CGameStatus    SendToClientMessageType = 1
	SendToClientMessageType_S2CSceneMessage  SendToClientMessageType = 2
	SendToClientMessageType_S2CDeal          SendToClientMessageType = 3
	SendToClientMessageType_S2CCurrentPlayer SendToClientMessageType = 4
	SendToClientMessageType_S2CTips          SendToClientMessageType = 5
	SendToClientMessageType_S2CPutInfo       SendToClientMessageType = 6
	SendToClientMessageType_S2CSettleInfo    SendToClientMessageType = 7
	SendToClientMessageType_S2CShowCards     SendToClientMessageType = 8
	SendToClientMessageType_S2CUserExit      SendToClientMessageType = 9
	SendToClientMessageType_S2CUserStatus    SendToClientMessageType = 10
	SendToClientMessageType_S2CUserSitDown   SendToClientMessageType = 11
)

var SendToClientMessageType_name = map[int32]string{
	0:  "S2CStartID",
	1:  "S2CGameStatus",
	2:  "S2CSceneMessage",
	3:  "S2CDeal",
	4:  "S2CCurrentPlayer",
	5:  "S2CTips",
	6:  "S2CPutInfo",
	7:  "S2CSettleInfo",
	8:  "S2CShowCards",
	9:  "S2CUserExit",
	10: "S2CUserStatus",
	11: "S2CUserSitDown",
}

var SendToClientMessageType_value = map[string]int32{
	"S2CStartID":       0,
	"S2CGameStatus":    1,
	"S2CSceneMessage":  2,
	"S2CDeal":          3,
	"S2CCurrentPlayer": 4,
	"S2CTips":          5,
	"S2CPutInfo":       6,
	"S2CSettleInfo":    7,
	"S2CShowCards":     8,
	"S2CUserExit":      9,
	"S2CUserStatus":    10,
	"S2CUserSitDown":   11,
}

func (x SendToClientMessageType) String() string {
	return proto.EnumName(SendToClientMessageType_name, int32(x))
}

func (SendToClientMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{1}
}

// 用户状态
type UserStatus int32

const (
	UserStatus_UserInitStatus UserStatus = 0
	UserStatus_UserNormal     UserStatus = 1
	UserStatus_UserHangUp     UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "UserInitStatus",
	1: "UserNormal",
	2: "UserHangUp",
}

var UserStatus_value = map[string]int32{
	"UserInitStatus": 0,
	"UserNormal":     1,
	"UserHangUp":     2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{2}
}

// 错误列表
type ErrList int32

const (
	ErrList_InitErr      ErrList = 0
	ErrList_TimeOut      ErrList = 1
	ErrList_WrongfulType ErrList = 2
	ErrList_NotGreater   ErrList = 3
)

var ErrList_name = map[int32]string{
	0: "InitErr",
	1: "TimeOut",
	2: "WrongfulType",
	3: "NotGreater",
}

var ErrList_value = map[string]int32{
	"InitErr":      0,
	"TimeOut":      1,
	"WrongfulType": 2,
	"NotGreater":   3,
}

func (x ErrList) String() string {
	return proto.EnumName(ErrList_name, int32(x))
}

func (ErrList) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{3}
}

// 游戏阶段
type GameStatus int32

const (
	GameStatus_GameInitStatus GameStatus = 0
	GameStatus_ReadyStatus    GameStatus = 1
	GameStatus_DealStatus     GameStatus = 2
	GameStatus_PutCardStatus  GameStatus = 3
	GameStatus_SettleStatus   GameStatus = 4
	GameStatus_GameOver       GameStatus = 5
)

var GameStatus_name = map[int32]string{
	0: "GameInitStatus",
	1: "ReadyStatus",
	2: "DealStatus",
	3: "PutCardStatus",
	4: "SettleStatus",
	5: "GameOver",
}

var GameStatus_value = map[string]int32{
	"GameInitStatus": 0,
	"ReadyStatus":    1,
	"DealStatus":     2,
	"PutCardStatus":  3,
	"SettleStatus":   4,
	"GameOver":       5,
}

func (x GameStatus) String() string {
	return proto.EnumName(GameStatus_name, int32(x))
}

func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{4}
}

//牌的类型
type CardsType int32

const (
	CardsType_Normal                         CardsType = 0
	CardsType_SingleCard                     CardsType = 1
	CardsType_Pair                           CardsType = 2
	CardsType_SerialPair                     CardsType = 3
	CardsType_Sequence                       CardsType = 4
	CardsType_Triplet                        CardsType = 5
	CardsType_TripletWithSingle              CardsType = 6
	CardsType_TripletWithTwo                 CardsType = 7
	CardsType_SerialTriplet                  CardsType = 8
	CardsType_IncompleteSerialTripletWithTwo CardsType = 9
	CardsType_SerialTripletWithTwo           CardsType = 10
	CardsType_QuartetWithThree               CardsType = 11
	CardsType_Bomb                           CardsType = 12
)

var CardsType_name = map[int32]string{
	0:  "Normal",
	1:  "SingleCard",
	2:  "Pair",
	3:  "SerialPair",
	4:  "Sequence",
	5:  "Triplet",
	6:  "TripletWithSingle",
	7:  "TripletWithTwo",
	8:  "SerialTriplet",
	9:  "IncompleteSerialTripletWithTwo",
	10: "SerialTripletWithTwo",
	11: "QuartetWithThree",
	12: "Bomb",
}

var CardsType_value = map[string]int32{
	"Normal":                         0,
	"SingleCard":                     1,
	"Pair":                           2,
	"SerialPair":                     3,
	"Sequence":                       4,
	"Triplet":                        5,
	"TripletWithSingle":              6,
	"TripletWithTwo":                 7,
	"SerialTriplet":                  8,
	"IncompleteSerialTripletWithTwo": 9,
	"SerialTripletWithTwo":           10,
	"QuartetWithThree":               11,
	"Bomb":                           12,
}

func (x CardsType) String() string {
	return proto.EnumName(CardsType_name, int32(x))
}

func (CardsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{5}
}

// 打牌操作类型
type UserActionType int32

const (
	UserActionType_NoPermission UserActionType = 0
	UserActionType_PutCard      UserActionType = 1
	UserActionType_TakeOverCard UserActionType = 2
)

var UserActionType_name = map[int32]string{
	0: "NoPermission",
	1: "PutCard",
	2: "TakeOverCard",
}

var UserActionType_value = map[string]int32{
	"NoPermission": 0,
	"PutCard":      1,
	"TakeOverCard": 2,
}

func (x UserActionType) String() string {
	return proto.EnumName(UserActionType_name, int32(x))
}

func (UserActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{6}
}

// 游戏状态消息
type StatusMessageRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status"`
	StatusTime           int32    `protobuf:"varint,2,opt,name=StatusTime,proto3" json:"StatusTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessageRes) Reset()         { *m = StatusMessageRes{} }
func (m *StatusMessageRes) String() string { return proto.CompactTextString(m) }
func (*StatusMessageRes) ProtoMessage()    {}
func (*StatusMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{0}
}

func (m *StatusMessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessageRes.Unmarshal(m, b)
}
func (m *StatusMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessageRes.Marshal(b, m, deterministic)
}
func (m *StatusMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessageRes.Merge(m, src)
}
func (m *StatusMessageRes) XXX_Size() int {
	return xxx_messageInfo_StatusMessageRes.Size(m)
}
func (m *StatusMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessageRes proto.InternalMessageInfo

func (m *StatusMessageRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StatusMessageRes) GetStatusTime() int32 {
	if m != nil {
		return m.StatusTime
	}
	return 0
}

// 发牌消息
type DealRes struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	FirstActionChairId   int32    `protobuf:"varint,2,opt,name=FirstActionChairId,proto3" json:"FirstActionChairId"`
	FirstActionUserId    int64    `protobuf:"varint,3,opt,name=FirstActionUserId,proto3" json:"FirstActionUserId"`
	UserId               int64    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,5,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealRes) Reset()         { *m = DealRes{} }
func (m *DealRes) String() string { return proto.CompactTextString(m) }
func (*DealRes) ProtoMessage()    {}
func (*DealRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{1}
}

func (m *DealRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealRes.Unmarshal(m, b)
}
func (m *DealRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealRes.Marshal(b, m, deterministic)
}
func (m *DealRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealRes.Merge(m, src)
}
func (m *DealRes) XXX_Size() int {
	return xxx_messageInfo_DealRes.Size(m)
}
func (m *DealRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DealRes.DiscardUnknown(m)
}

var xxx_messageInfo_DealRes proto.InternalMessageInfo

func (m *DealRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *DealRes) GetFirstActionChairId() int32 {
	if m != nil {
		return m.FirstActionChairId
	}
	return 0
}

func (m *DealRes) GetFirstActionUserId() int64 {
	if m != nil {
		return m.FirstActionUserId
	}
	return 0
}

func (m *DealRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DealRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 广播当前操作玩家
type CurrentPlayerRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	ActionTime           int32    `protobuf:"varint,3,opt,name=ActionTime,proto3" json:"ActionTime"`
	Permission           bool     `protobuf:"varint,4,opt,name=Permission,proto3" json:"Permission"`
	ActionType           int32    `protobuf:"varint,5,opt,name=ActionType,proto3" json:"ActionType"`
	IsFinalEnd           bool     `protobuf:"varint,6,opt,name=IsFinalEnd,proto3" json:"IsFinalEnd"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentPlayerRes) Reset()         { *m = CurrentPlayerRes{} }
func (m *CurrentPlayerRes) String() string { return proto.CompactTextString(m) }
func (*CurrentPlayerRes) ProtoMessage()    {}
func (*CurrentPlayerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{2}
}

func (m *CurrentPlayerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentPlayerRes.Unmarshal(m, b)
}
func (m *CurrentPlayerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentPlayerRes.Marshal(b, m, deterministic)
}
func (m *CurrentPlayerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentPlayerRes.Merge(m, src)
}
func (m *CurrentPlayerRes) XXX_Size() int {
	return xxx_messageInfo_CurrentPlayerRes.Size(m)
}
func (m *CurrentPlayerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentPlayerRes.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentPlayerRes proto.InternalMessageInfo

func (m *CurrentPlayerRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CurrentPlayerRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *CurrentPlayerRes) GetActionTime() int32 {
	if m != nil {
		return m.ActionTime
	}
	return 0
}

func (m *CurrentPlayerRes) GetPermission() bool {
	if m != nil {
		return m.Permission
	}
	return false
}

func (m *CurrentPlayerRes) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *CurrentPlayerRes) GetIsFinalEnd() bool {
	if m != nil {
		return m.IsFinalEnd
	}
	return false
}

// 通知提示信息
type TipsRes struct {
	Cards                [][]byte `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TipsRes) Reset()         { *m = TipsRes{} }
func (m *TipsRes) String() string { return proto.CompactTextString(m) }
func (*TipsRes) ProtoMessage()    {}
func (*TipsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{3}
}

func (m *TipsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TipsRes.Unmarshal(m, b)
}
func (m *TipsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TipsRes.Marshal(b, m, deterministic)
}
func (m *TipsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TipsRes.Merge(m, src)
}
func (m *TipsRes) XXX_Size() int {
	return xxx_messageInfo_TipsRes.Size(m)
}
func (m *TipsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TipsRes.DiscardUnknown(m)
}

var xxx_messageInfo_TipsRes proto.InternalMessageInfo

func (m *TipsRes) GetCards() [][]byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 广播出牌请求结果
type PutInfoRes struct {
	ErrNum               int32    `protobuf:"varint,1,opt,name=ErrNum,proto3" json:"ErrNum"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=IsSuccess,proto3" json:"IsSuccess"`
	Cards                []byte   `protobuf:"bytes,3,opt,name=Cards,proto3" json:"Cards"`
	CardType             int32    `protobuf:"varint,4,opt,name=CardType,proto3" json:"CardType"`
	UserId               int64    `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,6,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutInfoRes) Reset()         { *m = PutInfoRes{} }
func (m *PutInfoRes) String() string { return proto.CompactTextString(m) }
func (*PutInfoRes) ProtoMessage()    {}
func (*PutInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{4}
}

func (m *PutInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutInfoRes.Unmarshal(m, b)
}
func (m *PutInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutInfoRes.Marshal(b, m, deterministic)
}
func (m *PutInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutInfoRes.Merge(m, src)
}
func (m *PutInfoRes) XXX_Size() int {
	return xxx_messageInfo_PutInfoRes.Size(m)
}
func (m *PutInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PutInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_PutInfoRes proto.InternalMessageInfo

func (m *PutInfoRes) GetErrNum() int32 {
	if m != nil {
		return m.ErrNum
	}
	return 0
}

func (m *PutInfoRes) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *PutInfoRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *PutInfoRes) GetCardType() int32 {
	if m != nil {
		return m.CardType
	}
	return 0
}

func (m *PutInfoRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PutInfoRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 广播结算信息
type SettleInfoRes struct {
	ResultList           []*SettleResult `protobuf:"bytes,1,rep,name=ResultList,proto3" json:"ResultList"`
	SettleType           int32           `protobuf:"varint,2,opt,name=SettleType,proto3" json:"SettleType"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SettleInfoRes) Reset()         { *m = SettleInfoRes{} }
func (m *SettleInfoRes) String() string { return proto.CompactTextString(m) }
func (*SettleInfoRes) ProtoMessage()    {}
func (*SettleInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{5}
}

func (m *SettleInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleInfoRes.Unmarshal(m, b)
}
func (m *SettleInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleInfoRes.Marshal(b, m, deterministic)
}
func (m *SettleInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleInfoRes.Merge(m, src)
}
func (m *SettleInfoRes) XXX_Size() int {
	return xxx_messageInfo_SettleInfoRes.Size(m)
}
func (m *SettleInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_SettleInfoRes proto.InternalMessageInfo

func (m *SettleInfoRes) GetResultList() []*SettleResult {
	if m != nil {
		return m.ResultList
	}
	return nil
}

func (m *SettleInfoRes) GetSettleType() int32 {
	if m != nil {
		return m.SettleType
	}
	return 0
}

// 结算结果
type SettleResult struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	Result               int64    `protobuf:"varint,3,opt,name=Result,proto3" json:"Result"`
	CardCount            int32    `protobuf:"varint,4,opt,name=CardCount,proto3" json:"CardCount"`
	BoomSettle           int64    `protobuf:"varint,5,opt,name=BoomSettle,proto3" json:"BoomSettle"`
	TakeSingleRisk       bool     `protobuf:"varint,6,opt,name=takeSingleRisk,proto3" json:"takeSingleRisk"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleResult) Reset()         { *m = SettleResult{} }
func (m *SettleResult) String() string { return proto.CompactTextString(m) }
func (*SettleResult) ProtoMessage()    {}
func (*SettleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{6}
}

func (m *SettleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleResult.Unmarshal(m, b)
}
func (m *SettleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleResult.Marshal(b, m, deterministic)
}
func (m *SettleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleResult.Merge(m, src)
}
func (m *SettleResult) XXX_Size() int {
	return xxx_messageInfo_SettleResult.Size(m)
}
func (m *SettleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleResult.DiscardUnknown(m)
}

var xxx_messageInfo_SettleResult proto.InternalMessageInfo

func (m *SettleResult) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SettleResult) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *SettleResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SettleResult) GetCardCount() int32 {
	if m != nil {
		return m.CardCount
	}
	return 0
}

func (m *SettleResult) GetBoomSettle() int64 {
	if m != nil {
		return m.BoomSettle
	}
	return 0
}

func (m *SettleResult) GetTakeSingleRisk() bool {
	if m != nil {
		return m.TakeSingleRisk
	}
	return false
}

// 广播摊牌信息
type ShowCardsRes struct {
	ShowList             []*SeatUserInfoRes `protobuf:"bytes,1,rep,name=ShowList,proto3" json:"ShowList"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ShowCardsRes) Reset()         { *m = ShowCardsRes{} }
func (m *ShowCardsRes) String() string { return proto.CompactTextString(m) }
func (*ShowCardsRes) ProtoMessage()    {}
func (*ShowCardsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{7}
}

func (m *ShowCardsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCardsRes.Unmarshal(m, b)
}
func (m *ShowCardsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCardsRes.Marshal(b, m, deterministic)
}
func (m *ShowCardsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCardsRes.Merge(m, src)
}
func (m *ShowCardsRes) XXX_Size() int {
	return xxx_messageInfo_ShowCardsRes.Size(m)
}
func (m *ShowCardsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCardsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCardsRes proto.InternalMessageInfo

func (m *ShowCardsRes) GetShowList() []*SeatUserInfoRes {
	if m != nil {
		return m.ShowList
	}
	return nil
}

// 场景消息
type SceneMessageRes struct {
	UserData             []*SeatUserInfoRes `protobuf:"bytes,1,rep,name=UserData,proto3" json:"UserData"`
	GameStatus           int32              `protobuf:"varint,2,opt,name=GameStatus,proto3" json:"GameStatus"`
	StatusTimeLeft       int64              `protobuf:"varint,3,opt,name=StatusTimeLeft,proto3" json:"StatusTimeLeft"`
	RoomCost             int64              `protobuf:"varint,4,opt,name=RoomCost,proto3" json:"RoomCost"`
	MinLimit             int64              `protobuf:"varint,5,opt,name=MinLimit,proto3" json:"MinLimit"`
	Reconnect            bool               `protobuf:"varint,6,opt,name=Reconnect,proto3" json:"Reconnect"`
	RoomID               int64              `protobuf:"varint,7,opt,name=RoomID,proto3" json:"RoomID"`
	LeftCards            []*LeftCards       `protobuf:"bytes,8,rep,name=LeftCards,proto3" json:"LeftCards"`
	RoomLevel            int32              `protobuf:"varint,9,opt,name=RoomLevel,proto3" json:"RoomLevel"`
	StandardNullCard     []byte             `protobuf:"bytes,10,opt,name=StandardNullCard,proto3" json:"StandardNullCard"`
	CurrentPlayer        *CurrentPlayerRes  `protobuf:"bytes,11,opt,name=CurrentPlayer,proto3" json:"CurrentPlayer"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SceneMessageRes) Reset()         { *m = SceneMessageRes{} }
func (m *SceneMessageRes) String() string { return proto.CompactTextString(m) }
func (*SceneMessageRes) ProtoMessage()    {}
func (*SceneMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{8}
}

func (m *SceneMessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneMessageRes.Unmarshal(m, b)
}
func (m *SceneMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneMessageRes.Marshal(b, m, deterministic)
}
func (m *SceneMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneMessageRes.Merge(m, src)
}
func (m *SceneMessageRes) XXX_Size() int {
	return xxx_messageInfo_SceneMessageRes.Size(m)
}
func (m *SceneMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_SceneMessageRes proto.InternalMessageInfo

func (m *SceneMessageRes) GetUserData() []*SeatUserInfoRes {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *SceneMessageRes) GetGameStatus() int32 {
	if m != nil {
		return m.GameStatus
	}
	return 0
}

func (m *SceneMessageRes) GetStatusTimeLeft() int64 {
	if m != nil {
		return m.StatusTimeLeft
	}
	return 0
}

func (m *SceneMessageRes) GetRoomCost() int64 {
	if m != nil {
		return m.RoomCost
	}
	return 0
}

func (m *SceneMessageRes) GetMinLimit() int64 {
	if m != nil {
		return m.MinLimit
	}
	return 0
}

func (m *SceneMessageRes) GetReconnect() bool {
	if m != nil {
		return m.Reconnect
	}
	return false
}

func (m *SceneMessageRes) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SceneMessageRes) GetLeftCards() []*LeftCards {
	if m != nil {
		return m.LeftCards
	}
	return nil
}

func (m *SceneMessageRes) GetRoomLevel() int32 {
	if m != nil {
		return m.RoomLevel
	}
	return 0
}

func (m *SceneMessageRes) GetStandardNullCard() []byte {
	if m != nil {
		return m.StandardNullCard
	}
	return nil
}

func (m *SceneMessageRes) GetCurrentPlayer() *CurrentPlayerRes {
	if m != nil {
		return m.CurrentPlayer
	}
	return nil
}

//游戏中玩家的数据
type SeatUserInfoRes struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName"`
	Head                 string   `protobuf:"bytes,2,opt,name=Head,proto3" json:"Head"`
	Coin                 int64    `protobuf:"varint,3,opt,name=Coin,proto3" json:"Coin"`
	ChairId              int32    `protobuf:"varint,4,opt,name=ChairId,proto3" json:"ChairId"`
	Cards                []byte   `protobuf:"bytes,5,opt,name=Cards,proto3" json:"Cards"`
	Status               int32    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status"`
	UserId               int64    `protobuf:"varint,7,opt,name=UserId,proto3" json:"UserId"`
	Address              string   `protobuf:"bytes,8,opt,name=Address,proto3" json:"Address"`
	LastCards            []byte   `protobuf:"bytes,9,opt,name=LastCards,proto3" json:"LastCards"`
	CardsLen             int32    `protobuf:"varint,10,opt,name=CardsLen,proto3" json:"CardsLen"`
	Sex                  int32    `protobuf:"varint,11,opt,name=Sex,proto3" json:"Sex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatUserInfoRes) Reset()         { *m = SeatUserInfoRes{} }
func (m *SeatUserInfoRes) String() string { return proto.CompactTextString(m) }
func (*SeatUserInfoRes) ProtoMessage()    {}
func (*SeatUserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{9}
}

func (m *SeatUserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatUserInfoRes.Unmarshal(m, b)
}
func (m *SeatUserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatUserInfoRes.Marshal(b, m, deterministic)
}
func (m *SeatUserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatUserInfoRes.Merge(m, src)
}
func (m *SeatUserInfoRes) XXX_Size() int {
	return xxx_messageInfo_SeatUserInfoRes.Size(m)
}
func (m *SeatUserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatUserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_SeatUserInfoRes proto.InternalMessageInfo

func (m *SeatUserInfoRes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SeatUserInfoRes) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *SeatUserInfoRes) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *SeatUserInfoRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *SeatUserInfoRes) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SeatUserInfoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SeatUserInfoRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SeatUserInfoRes) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SeatUserInfoRes) GetLastCards() []byte {
	if m != nil {
		return m.LastCards
	}
	return nil
}

func (m *SeatUserInfoRes) GetCardsLen() int32 {
	if m != nil {
		return m.CardsLen
	}
	return 0
}

func (m *SeatUserInfoRes) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 记牌器剩余牌
type LeftCards struct {
	Count                int32    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count"`
	CardValue            []byte   `protobuf:"bytes,2,opt,name=CardValue,proto3" json:"CardValue"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeftCards) Reset()         { *m = LeftCards{} }
func (m *LeftCards) String() string { return proto.CompactTextString(m) }
func (*LeftCards) ProtoMessage()    {}
func (*LeftCards) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{10}
}

func (m *LeftCards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeftCards.Unmarshal(m, b)
}
func (m *LeftCards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeftCards.Marshal(b, m, deterministic)
}
func (m *LeftCards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeftCards.Merge(m, src)
}
func (m *LeftCards) XXX_Size() int {
	return xxx_messageInfo_LeftCards.Size(m)
}
func (m *LeftCards) XXX_DiscardUnknown() {
	xxx_messageInfo_LeftCards.DiscardUnknown(m)
}

var xxx_messageInfo_LeftCards proto.InternalMessageInfo

func (m *LeftCards) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LeftCards) GetCardValue() []byte {
	if m != nil {
		return m.CardValue
	}
	return nil
}

// 广播用户退出信息
type UserExitRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExitRes) Reset()         { *m = UserExitRes{} }
func (m *UserExitRes) String() string { return proto.CompactTextString(m) }
func (*UserExitRes) ProtoMessage()    {}
func (*UserExitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{11}
}

func (m *UserExitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExitRes.Unmarshal(m, b)
}
func (m *UserExitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExitRes.Marshal(b, m, deterministic)
}
func (m *UserExitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExitRes.Merge(m, src)
}
func (m *UserExitRes) XXX_Size() int {
	return xxx_messageInfo_UserExitRes.Size(m)
}
func (m *UserExitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExitRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserExitRes proto.InternalMessageInfo

func (m *UserExitRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserExitRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 玩家状态信息
type UserStatusRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	IsHangUp             bool     `protobuf:"varint,3,opt,name=IsHangUp,proto3" json:"IsHangUp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStatusRes) Reset()         { *m = UserStatusRes{} }
func (m *UserStatusRes) String() string { return proto.CompactTextString(m) }
func (*UserStatusRes) ProtoMessage()    {}
func (*UserStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{12}
}

func (m *UserStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStatusRes.Unmarshal(m, b)
}
func (m *UserStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStatusRes.Marshal(b, m, deterministic)
}
func (m *UserStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStatusRes.Merge(m, src)
}
func (m *UserStatusRes) XXX_Size() int {
	return xxx_messageInfo_UserStatusRes.Size(m)
}
func (m *UserStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserStatusRes proto.InternalMessageInfo

func (m *UserStatusRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserStatusRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *UserStatusRes) GetIsHangUp() bool {
	if m != nil {
		return m.IsHangUp
	}
	return false
}

// 广播用户坐下信息
type UserSitDownRes struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChairId              int32    `protobuf:"varint,2,opt,name=ChairId,proto3" json:"ChairId"`
	UserName             string   `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName"`
	Head                 string   `protobuf:"bytes,4,opt,name=Head,proto3" json:"Head"`
	Coin                 int64    `protobuf:"varint,5,opt,name=Coin,proto3" json:"Coin"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	Sex                  int32    `protobuf:"varint,7,opt,name=Sex,proto3" json:"Sex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSitDownRes) Reset()         { *m = UserSitDownRes{} }
func (m *UserSitDownRes) String() string { return proto.CompactTextString(m) }
func (*UserSitDownRes) ProtoMessage()    {}
func (*UserSitDownRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{13}
}

func (m *UserSitDownRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSitDownRes.Unmarshal(m, b)
}
func (m *UserSitDownRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSitDownRes.Marshal(b, m, deterministic)
}
func (m *UserSitDownRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSitDownRes.Merge(m, src)
}
func (m *UserSitDownRes) XXX_Size() int {
	return xxx_messageInfo_UserSitDownRes.Size(m)
}
func (m *UserSitDownRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSitDownRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserSitDownRes proto.InternalMessageInfo

func (m *UserSitDownRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserSitDownRes) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *UserSitDownRes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserSitDownRes) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UserSitDownRes) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserSitDownRes) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserSitDownRes) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 提示请求
type TipsReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TipsReq) Reset()         { *m = TipsReq{} }
func (m *TipsReq) String() string { return proto.CompactTextString(m) }
func (*TipsReq) ProtoMessage()    {}
func (*TipsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{14}
}

func (m *TipsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TipsReq.Unmarshal(m, b)
}
func (m *TipsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TipsReq.Marshal(b, m, deterministic)
}
func (m *TipsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TipsReq.Merge(m, src)
}
func (m *TipsReq) XXX_Size() int {
	return xxx_messageInfo_TipsReq.Size(m)
}
func (m *TipsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TipsReq.DiscardUnknown(m)
}

var xxx_messageInfo_TipsReq proto.InternalMessageInfo

func (m *TipsReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 出牌请求
type PutCardsReq struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutCardsReq) Reset()         { *m = PutCardsReq{} }
func (m *PutCardsReq) String() string { return proto.CompactTextString(m) }
func (*PutCardsReq) ProtoMessage()    {}
func (*PutCardsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{15}
}

func (m *PutCardsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutCardsReq.Unmarshal(m, b)
}
func (m *PutCardsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutCardsReq.Marshal(b, m, deterministic)
}
func (m *PutCardsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutCardsReq.Merge(m, src)
}
func (m *PutCardsReq) XXX_Size() int {
	return xxx_messageInfo_PutCardsReq.Size(m)
}
func (m *PutCardsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PutCardsReq.DiscardUnknown(m)
}

var xxx_messageInfo_PutCardsReq proto.InternalMessageInfo

func (m *PutCardsReq) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 取消托管请求请求
type CancelHangUpReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelHangUpReq) Reset()         { *m = CancelHangUpReq{} }
func (m *CancelHangUpReq) String() string { return proto.CompactTextString(m) }
func (*CancelHangUpReq) ProtoMessage()    {}
func (*CancelHangUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{16}
}

func (m *CancelHangUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelHangUpReq.Unmarshal(m, b)
}
func (m *CancelHangUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelHangUpReq.Marshal(b, m, deterministic)
}
func (m *CancelHangUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelHangUpReq.Merge(m, src)
}
func (m *CancelHangUpReq) XXX_Size() int {
	return xxx_messageInfo_CancelHangUpReq.Size(m)
}
func (m *CancelHangUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelHangUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelHangUpReq proto.InternalMessageInfo

func (m *CancelHangUpReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 要牌请求
type DemandCardsReq struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemandCardsReq) Reset()         { *m = DemandCardsReq{} }
func (m *DemandCardsReq) String() string { return proto.CompactTextString(m) }
func (*DemandCardsReq) ProtoMessage()    {}
func (*DemandCardsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2213b8424a8be56, []int{17}
}

func (m *DemandCardsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemandCardsReq.Unmarshal(m, b)
}
func (m *DemandCardsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemandCardsReq.Marshal(b, m, deterministic)
}
func (m *DemandCardsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemandCardsReq.Merge(m, src)
}
func (m *DemandCardsReq) XXX_Size() int {
	return xxx_messageInfo_DemandCardsReq.Size(m)
}
func (m *DemandCardsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DemandCardsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DemandCardsReq proto.InternalMessageInfo

func (m *DemandCardsReq) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterEnum("msg.ReceiveMessageType", ReceiveMessageType_name, ReceiveMessageType_value)
	proto.RegisterEnum("msg.SendToClientMessageType", SendToClientMessageType_name, SendToClientMessageType_value)
	proto.RegisterEnum("msg.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("msg.ErrList", ErrList_name, ErrList_value)
	proto.RegisterEnum("msg.GameStatus", GameStatus_name, GameStatus_value)
	proto.RegisterEnum("msg.CardsType", CardsType_name, CardsType_value)
	proto.RegisterEnum("msg.UserActionType", UserActionType_name, UserActionType_value)
	proto.RegisterType((*StatusMessageRes)(nil), "msg.StatusMessageRes")
	proto.RegisterType((*DealRes)(nil), "msg.DealRes")
	proto.RegisterType((*CurrentPlayerRes)(nil), "msg.CurrentPlayerRes")
	proto.RegisterType((*TipsRes)(nil), "msg.TipsRes")
	proto.RegisterType((*PutInfoRes)(nil), "msg.PutInfoRes")
	proto.RegisterType((*SettleInfoRes)(nil), "msg.SettleInfoRes")
	proto.RegisterType((*SettleResult)(nil), "msg.SettleResult")
	proto.RegisterType((*ShowCardsRes)(nil), "msg.ShowCardsRes")
	proto.RegisterType((*SceneMessageRes)(nil), "msg.SceneMessageRes")
	proto.RegisterType((*SeatUserInfoRes)(nil), "msg.SeatUserInfoRes")
	proto.RegisterType((*LeftCards)(nil), "msg.LeftCards")
	proto.RegisterType((*UserExitRes)(nil), "msg.UserExitRes")
	proto.RegisterType((*UserStatusRes)(nil), "msg.UserStatusRes")
	proto.RegisterType((*UserSitDownRes)(nil), "msg.UserSitDownRes")
	proto.RegisterType((*TipsReq)(nil), "msg.TipsReq")
	proto.RegisterType((*PutCardsReq)(nil), "msg.PutCardsReq")
	proto.RegisterType((*CancelHangUpReq)(nil), "msg.CancelHangUpReq")
	proto.RegisterType((*DemandCardsReq)(nil), "msg.DemandCardsReq")
}

func init() { proto.RegisterFile("run_faster.proto", fileDescriptor_a2213b8424a8be56) }

var fileDescriptor_a2213b8424a8be56 = []byte{
	// 1308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4b, 0x6f, 0x1b, 0x37,
	0x10, 0xce, 0x6a, 0xf5, 0x1c, 0xc9, 0x32, 0xcd, 0x3a, 0xa9, 0x10, 0x14, 0x69, 0xba, 0x05, 0x82,
	0x54, 0x08, 0x8c, 0x54, 0x3d, 0xf6, 0x90, 0xc7, 0xda, 0x49, 0x54, 0x38, 0x8e, 0xbb, 0xeb, 0x34,
	0xa7, 0xa2, 0x60, 0x24, 0xda, 0x5e, 0x78, 0x97, 0x74, 0xb8, 0xdc, 0x3c, 0x7e, 0x4b, 0xef, 0x3d,
	0xb6, 0x40, 0x7f, 0x40, 0x4f, 0xfd, 0x3d, 0x3d, 0xf7, 0x58, 0x0c, 0xc9, 0x7d, 0x48, 0xb1, 0x83,
	0xc2, 0x37, 0xcd, 0xc7, 0xe1, 0x3c, 0xbe, 0x19, 0xce, 0xac, 0x80, 0xa8, 0x42, 0xfc, 0x72, 0xcc,
	0x72, 0xcd, 0xd5, 0xce, 0xb9, 0x92, 0x5a, 0x52, 0x3f, 0xcb, 0x4f, 0x82, 0x1f, 0x80, 0xc4, 0x9a,
	0xe9, 0x22, 0x7f, 0xce, 0xf3, 0x9c, 0x9d, 0xf0, 0x88, 0xe7, 0xf4, 0x06, 0x74, 0x2d, 0x36, 0xf1,
	0x6e, 0x7b, 0x77, 0x3b, 0x91, 0x93, 0xe8, 0x2d, 0x00, 0xfb, 0xeb, 0x28, 0xc9, 0xf8, 0xa4, 0x65,
	0xce, 0x1a, 0x48, 0xf0, 0x87, 0x07, 0xbd, 0x5d, 0xce, 0x52, 0xb4, 0xb1, 0x0d, 0x9d, 0x90, 0xa9,
	0xa5, 0x35, 0x31, 0x8a, 0xac, 0x40, 0x77, 0x80, 0x3e, 0x49, 0x54, 0xae, 0x1f, 0x2d, 0x74, 0x22,
	0x45, 0x78, 0xca, 0x12, 0x35, 0x5f, 0x3a, 0x4b, 0x17, 0x9c, 0xd0, 0x7b, 0xb0, 0xd5, 0x40, 0x5f,
	0xe6, 0x1c, 0xd5, 0xfd, 0xdb, 0xde, 0x5d, 0x3f, 0xfa, 0xf8, 0x00, 0xe3, 0x76, 0x2a, 0x6d, 0xa3,
	0xe2, 0x24, 0x3a, 0x81, 0x5e, 0xe9, 0xaa, 0x63, 0x5c, 0x95, 0x62, 0xf0, 0xb7, 0x07, 0x24, 0x2c,
	0x94, 0xe2, 0x42, 0x1f, 0xa6, 0xec, 0x03, 0x57, 0x2e, 0x7d, 0x67, 0xc6, 0xbb, 0xcc, 0x4c, 0x6b,
	0xc5, 0x0c, 0x12, 0x63, 0x03, 0x31, 0xc4, 0xf8, 0x96, 0x98, 0x1a, 0xc1, 0xf3, 0x43, 0xae, 0xb2,
	0x24, 0xcf, 0x13, 0x29, 0x4c, 0x70, 0xfd, 0xa8, 0x81, 0x34, 0xee, 0x7f, 0x38, 0xe7, 0x2e, 0xc6,
	0x06, 0x82, 0xe7, 0xf3, 0xfc, 0x49, 0x22, 0x58, 0xba, 0x27, 0x96, 0x93, 0xae, 0xbd, 0x5f, 0x23,
	0xc1, 0x97, 0xd0, 0x3b, 0x4a, 0xce, 0xf3, 0x35, 0xde, 0xfd, 0x8a, 0xf7, 0xe0, 0x37, 0x0f, 0xe0,
	0xb0, 0xd0, 0x73, 0x71, 0x2c, 0x5d, 0x86, 0x7b, 0x4a, 0x1d, 0x14, 0x59, 0x59, 0x60, 0x2b, 0xd1,
	0x2f, 0x60, 0x30, 0xcf, 0xe3, 0x62, 0xb1, 0xe0, 0x79, 0x6e, 0x72, 0xec, 0x47, 0x35, 0x50, 0x9b,
	0xf6, 0x9b, 0x25, 0xbd, 0x09, 0x7d, 0xfc, 0x61, 0x22, 0x6f, 0x1b, 0x6b, 0x95, 0xdc, 0x60, 0xb2,
	0x73, 0x19, 0x93, 0xdd, 0xd5, 0x82, 0xbc, 0x86, 0x8d, 0x98, 0x6b, 0x9d, 0xf2, 0x32, 0xd4, 0x6f,
	0x01, 0x22, 0x9e, 0x17, 0xa9, 0xde, 0x4f, 0x72, 0x6d, 0x92, 0x1a, 0xce, 0xb6, 0x76, 0xb2, 0xfc,
	0x64, 0xc7, 0xea, 0xd9, 0xc3, 0xa8, 0xa1, 0x64, 0xda, 0xd4, 0x9c, 0x99, 0x98, 0xca, 0x36, 0xad,
	0x90, 0xe0, 0x2f, 0x0f, 0x46, 0xcd, 0xcb, 0x57, 0x28, 0xf8, 0x0d, 0xe8, 0xda, 0xbb, 0xae, 0x19,
	0x9d, 0x84, 0x04, 0x62, 0xf2, 0xa1, 0x2c, 0x84, 0x76, 0x6c, 0xd4, 0x00, 0x06, 0xf6, 0x58, 0xca,
	0xcc, 0xfa, 0x76, 0x94, 0x34, 0x10, 0x7a, 0x07, 0xc6, 0x9a, 0x9d, 0xf1, 0x38, 0x11, 0x27, 0x29,
	0x8f, 0x92, 0xfc, 0xcc, 0x95, 0x7a, 0x0d, 0x0d, 0x1e, 0xc2, 0x28, 0x3e, 0x95, 0xef, 0x0c, 0xff,
	0xc8, 0xd1, 0x7d, 0xe8, 0xa3, 0xdc, 0x60, 0x68, 0xdb, 0x31, 0xc4, 0xb4, 0x49, 0xc5, 0x72, 0x19,
	0x55, 0x5a, 0xc1, 0xef, 0x3e, 0x6c, 0xc6, 0x0b, 0x2e, 0x78, 0xe3, 0xd5, 0xdf, 0x87, 0x3e, 0x2a,
	0xef, 0x32, 0xcd, 0x3e, 0x6d, 0xa5, 0xd4, 0xc2, 0x7c, 0x9e, 0xb2, 0x8c, 0xbb, 0x59, 0xe1, 0x88,
	0xae, 0x11, 0xcc, 0xa7, 0x9e, 0x0e, 0xfb, 0xfc, 0xb8, 0x64, 0x6b, 0x0d, 0xc5, 0x16, 0x8a, 0xa4,
	0xcc, 0x42, 0x99, 0x6b, 0xf7, 0x72, 0x2b, 0x19, 0xcf, 0x9e, 0x27, 0x62, 0x3f, 0xc9, 0x12, 0xed,
	0x18, 0xab, 0x64, 0x64, 0x3b, 0xe2, 0x0b, 0x29, 0x04, 0x5f, 0x68, 0x47, 0x55, 0x0d, 0x98, 0x1a,
	0x49, 0x99, 0xcd, 0x77, 0x27, 0x3d, 0x57, 0x23, 0x23, 0xd1, 0x7b, 0x30, 0x40, 0xaf, 0xb6, 0x95,
	0xfb, 0x26, 0xd1, 0xb1, 0x49, 0xb4, 0x42, 0xa3, 0x5a, 0xc1, 0xf8, 0x90, 0x32, 0xdb, 0xe7, 0x6f,
	0x79, 0x3a, 0x19, 0xd8, 0x8a, 0x56, 0x00, 0x9d, 0x9a, 0xe9, 0x29, 0x96, 0x4c, 0x2d, 0x0f, 0x8a,
	0x34, 0xc5, 0x2b, 0x13, 0x30, 0xaf, 0xe3, 0x23, 0x9c, 0x7e, 0x0f, 0x1b, 0x2b, 0xa3, 0x66, 0x32,
	0xbc, 0xed, 0xdd, 0x1d, 0xce, 0xae, 0x1b, 0xdf, 0xeb, 0x43, 0x28, 0x5a, 0xd5, 0x0d, 0x7e, 0x6d,
	0xc1, 0xe6, 0x5a, 0x21, 0x90, 0x1a, 0x14, 0x0f, 0x58, 0xc6, 0x4d, 0xe3, 0x0e, 0xa2, 0x4a, 0xa6,
	0x14, 0xda, 0xcf, 0x38, 0xb3, 0x7d, 0x3b, 0x88, 0xcc, 0x6f, 0xc4, 0x42, 0x99, 0x08, 0x57, 0x04,
	0xf3, 0xbb, 0xd9, 0xe2, 0xed, 0xd5, 0x16, 0xaf, 0x5e, 0x7b, 0xa7, 0xf9, 0xda, 0xeb, 0xd5, 0xd0,
	0x5d, 0x59, 0x0d, 0xf5, 0x13, 0xea, 0xad, 0x3f, 0xa1, 0x47, 0xcb, 0xa5, 0xc2, 0x79, 0xd2, 0x37,
	0xa1, 0x94, 0x22, 0x12, 0xbb, 0xcf, 0x72, 0x57, 0x86, 0x81, 0xf1, 0x51, 0x03, 0xe5, 0x54, 0xc9,
	0xf7, 0xb9, 0x30, 0x84, 0xba, 0xa9, 0x82, 0x32, 0x25, 0xe0, 0xc7, 0xfc, 0xbd, 0xa1, 0xaf, 0x13,
	0xe1, 0xcf, 0xe0, 0x41, 0xa3, 0xa4, 0x26, 0x70, 0xf3, 0xfe, 0xec, 0x6c, 0xb3, 0x42, 0xf9, 0x32,
	0x7f, 0x62, 0x69, 0x61, 0x67, 0xc2, 0x28, 0xaa, 0x81, 0xe0, 0x01, 0x0c, 0x31, 0xe0, 0xbd, 0xf7,
	0x89, 0xbe, 0xd2, 0x06, 0x08, 0x7e, 0x86, 0x0d, 0xd4, 0xb1, 0x6c, 0x5c, 0x6d, 0x89, 0xdc, 0x84,
	0xfe, 0x3c, 0x7f, 0xc6, 0xc4, 0xc9, 0xcb, 0x73, 0x53, 0xa2, 0x7e, 0x54, 0xc9, 0xc1, 0x9f, 0x1e,
	0x8c, 0x8d, 0xfd, 0x44, 0xef, 0xca, 0x77, 0xc2, 0x39, 0x28, 0x56, 0x1c, 0x14, 0xff, 0xc3, 0x41,
	0xd5, 0x2f, 0xfe, 0x25, 0xfd, 0xd2, 0xbe, 0xa0, 0x5f, 0x3a, 0xab, 0xfd, 0xc2, 0x5c, 0x3d, 0xbb,
	0xb6, 0x9e, 0x4e, 0x2c, 0xab, 0xd2, 0xab, 0xab, 0xf2, 0x55, 0xb9, 0x95, 0xde, 0x5c, 0xc6, 0x46,
	0xf0, 0x35, 0x0c, 0x0f, 0x0b, 0xf7, 0xe8, 0xf8, 0x9b, 0x8b, 0x3f, 0x1a, 0x82, 0x6f, 0x60, 0x33,
	0x64, 0x62, 0xc1, 0x53, 0x4b, 0xc6, 0xa7, 0xec, 0xdd, 0x81, 0xf1, 0x2e, 0xcf, 0x98, 0x58, 0x7e,
	0xda, 0xe4, 0xf4, 0x0c, 0x68, 0xc4, 0x17, 0x3c, 0x79, 0x5b, 0x0e, 0x40, 0xb3, 0xae, 0xc6, 0x00,
	0xe1, 0x2c, 0x8e, 0x35, 0x53, 0x7a, 0xbe, 0x4b, 0xae, 0xd1, 0x21, 0xf4, 0xc2, 0x59, 0x8c, 0x39,
	0x10, 0x8f, 0x6e, 0xc2, 0x30, 0x9c, 0xc5, 0x65, 0xb4, 0xa4, 0x45, 0x3f, 0x83, 0xcd, 0x70, 0x16,
	0x37, 0x23, 0x23, 0x3e, 0xa5, 0x30, 0x0e, 0x67, 0x71, 0x23, 0x06, 0xd2, 0x9e, 0xfe, 0xe3, 0xc1,
	0xe7, 0x31, 0x17, 0xcb, 0x23, 0x19, 0xa6, 0x09, 0x17, 0x7a, 0xcd, 0x65, 0x3c, 0x0b, 0x6b, 0x97,
	0x5b, 0xb0, 0x11, 0xcf, 0xc2, 0x7a, 0x86, 0x12, 0x0f, 0xfd, 0xa0, 0x4a, 0x63, 0x5a, 0x93, 0x16,
	0x86, 0x16, 0xcf, 0x42, 0xfc, 0xd8, 0x22, 0x3e, 0xdd, 0x06, 0x12, 0xcf, 0xc2, 0x95, 0x81, 0x41,
	0xda, 0x4e, 0xc5, 0x44, 0xdf, 0x71, 0x7e, 0xdc, 0x27, 0x00, 0xe9, 0x3a, 0x3f, 0xf5, 0xaa, 0x25,
	0x3d, 0x4a, 0x60, 0x84, 0x50, 0xb9, 0x58, 0x48, 0x1f, 0x53, 0x8e, 0x67, 0x61, 0xf9, 0x30, 0xc8,
	0xc0, 0xdd, 0xaa, 0x1b, 0x9d, 0x00, 0x26, 0x5c, 0x42, 0xb6, 0x37, 0xc9, 0x70, 0xfa, 0x10, 0xa0,
	0xd6, 0x41, 0x0d, 0x3b, 0xb5, 0x12, 0xed, 0x6e, 0x5d, 0xc3, 0x70, 0x4c, 0xeb, 0x49, 0x95, 0xb1,
	0x94, 0x78, 0xa5, 0xec, 0x68, 0x6c, 0x4d, 0xf7, 0xa0, 0xb7, 0xa7, 0x94, 0xd9, 0xe6, 0x43, 0xe8,
	0xe1, 0xd5, 0x3d, 0xa5, 0x6c, 0x45, 0x70, 0x6b, 0xbc, 0x28, 0x34, 0xf1, 0x30, 0xe0, 0x57, 0x4a,
	0x8a, 0x93, 0xe3, 0x22, 0x45, 0x2e, 0x49, 0x0b, 0xcd, 0x1c, 0x48, 0xfd, 0x54, 0x71, 0xa6, 0xb9,
	0x22, 0xfe, 0x54, 0x37, 0x17, 0x14, 0x06, 0x82, 0xd2, 0x4a, 0x20, 0x9b, 0x30, 0x8c, 0x38, 0x5b,
	0x7e, 0xa8, 0xd8, 0x1e, 0x03, 0x20, 0xab, 0x4e, 0x6e, 0x61, 0xca, 0xae, 0xe6, 0x0e, 0xf2, 0x0d,
	0x51, 0x86, 0x38, 0x87, 0xb4, 0xe9, 0x08, 0xfa, 0x68, 0xf9, 0xc5, 0x5b, 0xae, 0x48, 0x67, 0xfa,
	0xaf, 0x67, 0x67, 0x4d, 0x6e, 0x2a, 0x0c, 0xd0, 0x75, 0x69, 0x9a, 0xb4, 0xed, 0x1a, 0xc7, 0x63,
	0xe2, 0xd1, 0x3e, 0xb4, 0x0f, 0x59, 0xa2, 0x6c, 0xe4, 0x31, 0x57, 0x09, 0x4b, 0x8d, 0xec, 0xa3,
	0xc5, 0x98, 0xbf, 0x29, 0xb8, 0x58, 0x70, 0x5b, 0xca, 0x23, 0x95, 0x9c, 0xa7, 0x5c, 0x93, 0x0e,
	0xbd, 0x0e, 0x5b, 0x4e, 0x78, 0x95, 0xe8, 0x53, 0x6b, 0x8f, 0x74, 0x31, 0xbb, 0x06, 0x7c, 0xf4,
	0x0e, 0x4b, 0x8a, 0xf5, 0x32, 0x56, 0xcb, 0xdb, 0x7d, 0x1a, 0xc0, 0xad, 0xb9, 0x58, 0xc8, 0x0c,
	0x45, 0xbe, 0x72, 0x58, 0x5e, 0x1b, 0xd0, 0x09, 0x6c, 0x5f, 0x78, 0x02, 0xd8, 0x69, 0x3f, 0x16,
	0x4c, 0x69, 0x87, 0x9d, 0x2a, 0xce, 0xc9, 0x10, 0xd3, 0x78, 0x2c, 0xb3, 0xd7, 0x64, 0x34, 0x7d,
	0x64, 0x6b, 0xdd, 0xf8, 0x74, 0x25, 0x30, 0x3a, 0x90, 0xf5, 0xa7, 0xae, 0xad, 0xa1, 0x63, 0xd4,
	0xd6, 0xf0, 0x88, 0x9d, 0x19, 0xe6, 0x0c, 0xd2, 0x7a, 0xdd, 0x35, 0x7f, 0x4e, 0xbe, 0xfb, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x8d, 0x8d, 0x23, 0x61, 0xb0, 0x0c, 0x00, 0x00,
}
