// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BRZJH.proto

package BRZJH

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端到服务器发送消息的类型
type ReceiveMessageType int32

const (
	ReceiveMessageType_StartID         ReceiveMessageType = 0
	ReceiveMessageType_BetID           ReceiveMessageType = 1
	ReceiveMessageType_SitDown         ReceiveMessageType = 2
	ReceiveMessageType_GetTrend        ReceiveMessageType = 3
	ReceiveMessageType_GetUserListInfo ReceiveMessageType = 4
	ReceiveMessageType_StandUp         ReceiveMessageType = 5
	ReceiveMessageType_ShangZhuang     ReceiveMessageType = 6
	ReceiveMessageType_GetZhuangList   ReceiveMessageType = 7
	ReceiveMessageType_XiaZhuang       ReceiveMessageType = 8
	ReceiveMessageType_tempCard        ReceiveMessageType = 9
)

var ReceiveMessageType_name = map[int32]string{
	0: "StartID",
	1: "BetID",
	2: "SitDown",
	3: "GetTrend",
	4: "GetUserListInfo",
	5: "StandUp",
	6: "ShangZhuang",
	7: "GetZhuangList",
	8: "XiaZhuang",
	9: "tempCard",
}

var ReceiveMessageType_value = map[string]int32{
	"StartID":         0,
	"BetID":           1,
	"SitDown":         2,
	"GetTrend":        3,
	"GetUserListInfo": 4,
	"StandUp":         5,
	"ShangZhuang":     6,
	"GetZhuangList":   7,
	"XiaZhuang":       8,
	"tempCard":        9,
}

func (x ReceiveMessageType) String() string {
	return proto.EnumName(ReceiveMessageType_name, int32(x))
}

func (ReceiveMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{0}
}

// 服务器发送给客户端的消息类型
type SendToClientMessageType int32

const (
	SendToClientMessageType_RestartID           SendToClientMessageType = 0
	SendToClientMessageType_BetRet              SendToClientMessageType = 1
	SendToClientMessageType_BetFailID           SendToClientMessageType = 2
	SendToClientMessageType_BetSuccessMessageID SendToClientMessageType = 3
	SendToClientMessageType_SceneID             SendToClientMessageType = 4
	SendToClientMessageType_Status              SendToClientMessageType = 6
	SendToClientMessageType_Settle              SendToClientMessageType = 7
	SendToClientMessageType_SitDownFail         SendToClientMessageType = 8
	SendToClientMessageType_BetInfo             SendToClientMessageType = 9
	SendToClientMessageType_TrendInfo           SendToClientMessageType = 10
	SendToClientMessageType_UserListInfo        SendToClientMessageType = 11
	SendToClientMessageType_SceneSettleInfo     SendToClientMessageType = 12
	SendToClientMessageType_ExitRet             SendToClientMessageType = 13
	SendToClientMessageType_KickOutUser         SendToClientMessageType = 14
	SendToClientMessageType_RoomRolesInfo       SendToClientMessageType = 15
	SendToClientMessageType_RoomSenceInfo       SendToClientMessageType = 16
	SendToClientMessageType_UserComeBack        SendToClientMessageType = 17
	SendToClientMessageType_CurrZhuang          SendToClientMessageType = 18
	SendToClientMessageType_ZhuangList          SendToClientMessageType = 19
	SendToClientMessageType_ZhuangUserCount     SendToClientMessageType = 20
	SendToClientMessageType_PokerInfo           SendToClientMessageType = 21
	SendToClientMessageType_BroadEndBet         SendToClientMessageType = 22
)

var SendToClientMessageType_name = map[int32]string{
	0:  "RestartID",
	1:  "BetRet",
	2:  "BetFailID",
	3:  "BetSuccessMessageID",
	4:  "SceneID",
	6:  "Status",
	7:  "Settle",
	8:  "SitDownFail",
	9:  "BetInfo",
	10: "TrendInfo",
	11: "UserListInfo",
	12: "SceneSettleInfo",
	13: "ExitRet",
	14: "KickOutUser",
	15: "RoomRolesInfo",
	16: "RoomSenceInfo",
	17: "UserComeBack",
	18: "CurrZhuang",
	19: "ZhuangList",
	20: "ZhuangUserCount",
	21: "PokerInfo",
	22: "BroadEndBet",
}

var SendToClientMessageType_value = map[string]int32{
	"RestartID":           0,
	"BetRet":              1,
	"BetFailID":           2,
	"BetSuccessMessageID": 3,
	"SceneID":             4,
	"Status":              6,
	"Settle":              7,
	"SitDownFail":         8,
	"BetInfo":             9,
	"TrendInfo":           10,
	"UserListInfo":        11,
	"SceneSettleInfo":     12,
	"ExitRet":             13,
	"KickOutUser":         14,
	"RoomRolesInfo":       15,
	"RoomSenceInfo":       16,
	"UserComeBack":        17,
	"CurrZhuang":          18,
	"ZhuangList":          19,
	"ZhuangUserCount":     20,
	"PokerInfo":           21,
	"BroadEndBet":         22,
}

func (x SendToClientMessageType) String() string {
	return proto.EnumName(SendToClientMessageType_name, int32(x))
}

func (SendToClientMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{1}
}

//游戏阶段
type GameStatus int32

const (
	GameStatus_StartStatus  GameStatus = 0
	GameStatus_StartMovie   GameStatus = 1
	GameStatus_BetStatus    GameStatus = 2
	GameStatus_EndBetMovie  GameStatus = 3
	GameStatus_ShowPoker    GameStatus = 4
	GameStatus_SettleStatus GameStatus = 5
)

var GameStatus_name = map[int32]string{
	0: "StartStatus",
	1: "StartMovie",
	2: "BetStatus",
	3: "EndBetMovie",
	4: "ShowPoker",
	5: "SettleStatus",
}

var GameStatus_value = map[string]int32{
	"StartStatus":  0,
	"StartMovie":   1,
	"BetStatus":    2,
	"EndBetMovie":  3,
	"ShowPoker":    4,
	"SettleStatus": 5,
}

func (x GameStatus) String() string {
	return proto.EnumName(GameStatus_name, int32(x))
}

func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{2}
}

type StatusMessage struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	StatusTime           int32    `protobuf:"varint,2,opt,name=StatusTime,proto3" json:"StatusTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{0}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StatusMessage) GetStatusTime() int32 {
	if m != nil {
		return m.StatusTime
	}
	return 0
}

// 押注失败发送的消息
type BetFailMessage struct {
	FailMessage          string   `protobuf:"bytes,1,opt,name=FailMessage,proto3" json:"FailMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetFailMessage) Reset()         { *m = BetFailMessage{} }
func (m *BetFailMessage) String() string { return proto.CompactTextString(m) }
func (*BetFailMessage) ProtoMessage()    {}
func (*BetFailMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{1}
}

func (m *BetFailMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetFailMessage.Unmarshal(m, b)
}
func (m *BetFailMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetFailMessage.Marshal(b, m, deterministic)
}
func (m *BetFailMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetFailMessage.Merge(m, src)
}
func (m *BetFailMessage) XXX_Size() int {
	return xxx_messageInfo_BetFailMessage.Size(m)
}
func (m *BetFailMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BetFailMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BetFailMessage proto.InternalMessageInfo

func (m *BetFailMessage) GetFailMessage() string {
	if m != nil {
		return m.FailMessage
	}
	return ""
}

// 押注成功时发送的消息
type BetSuccessMessage struct {
	SeatId               int32    `protobuf:"varint,1,opt,name=SeatId,proto3" json:"SeatId,omitempty"`
	BetIndex             int32    `protobuf:"varint,2,opt,name=BetIndex,proto3" json:"BetIndex,omitempty"`
	BetType              int32    `protobuf:"varint,3,opt,name=BetType,proto3" json:"BetType,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetSuccessMessage) Reset()         { *m = BetSuccessMessage{} }
func (m *BetSuccessMessage) String() string { return proto.CompactTextString(m) }
func (*BetSuccessMessage) ProtoMessage()    {}
func (*BetSuccessMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{2}
}

func (m *BetSuccessMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetSuccessMessage.Unmarshal(m, b)
}
func (m *BetSuccessMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetSuccessMessage.Marshal(b, m, deterministic)
}
func (m *BetSuccessMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetSuccessMessage.Merge(m, src)
}
func (m *BetSuccessMessage) XXX_Size() int {
	return xxx_messageInfo_BetSuccessMessage.Size(m)
}
func (m *BetSuccessMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BetSuccessMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BetSuccessMessage proto.InternalMessageInfo

func (m *BetSuccessMessage) GetSeatId() int32 {
	if m != nil {
		return m.SeatId
	}
	return 0
}

func (m *BetSuccessMessage) GetBetIndex() int32 {
	if m != nil {
		return m.BetIndex
	}
	return 0
}

func (m *BetSuccessMessage) GetBetType() int32 {
	if m != nil {
		return m.BetType
	}
	return 0
}

func (m *BetSuccessMessage) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// 服务器收到的押注信息
type Bet struct {
	BetType              int32    `protobuf:"varint,1,opt,name=BetType,proto3" json:"BetType,omitempty"`
	BetIndex             int32    `protobuf:"varint,2,opt,name=BetIndex,proto3" json:"BetIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{3}
}

func (m *Bet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bet.Unmarshal(m, b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return xxx_messageInfo_Bet.Size(m)
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetBetType() int32 {
	if m != nil {
		return m.BetType
	}
	return 0
}

func (m *Bet) GetBetIndex() int32 {
	if m != nil {
		return m.BetIndex
	}
	return 0
}

//游戏中几个玩家的数据
type SeatUser struct {
	Nick                 string   `protobuf:"bytes,1,opt,name=Nick,proto3" json:"Nick,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=Head,proto3" json:"Head,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	IsBigWinner          bool     `protobuf:"varint,4,opt,name=IsBigWinner,proto3" json:"IsBigWinner,omitempty"`
	IsMaster             bool     `protobuf:"varint,5,opt,name=IsMaster,proto3" json:"IsMaster,omitempty"`
	SeatId               int32    `protobuf:"varint,6,opt,name=SeatId,proto3" json:"SeatId,omitempty"`
	UserID               int64    `protobuf:"varint,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsMillionaire        bool     `protobuf:"varint,8,opt,name=IsMillionaire,proto3" json:"IsMillionaire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatUser) Reset()         { *m = SeatUser{} }
func (m *SeatUser) String() string { return proto.CompactTextString(m) }
func (*SeatUser) ProtoMessage()    {}
func (*SeatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{4}
}

func (m *SeatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatUser.Unmarshal(m, b)
}
func (m *SeatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatUser.Marshal(b, m, deterministic)
}
func (m *SeatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatUser.Merge(m, src)
}
func (m *SeatUser) XXX_Size() int {
	return xxx_messageInfo_SeatUser.Size(m)
}
func (m *SeatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatUser.DiscardUnknown(m)
}

var xxx_messageInfo_SeatUser proto.InternalMessageInfo

func (m *SeatUser) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *SeatUser) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *SeatUser) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SeatUser) GetIsBigWinner() bool {
	if m != nil {
		return m.IsBigWinner
	}
	return false
}

func (m *SeatUser) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *SeatUser) GetSeatId() int32 {
	if m != nil {
		return m.SeatId
	}
	return 0
}

func (m *SeatUser) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SeatUser) GetIsMillionaire() bool {
	if m != nil {
		return m.IsMillionaire
	}
	return false
}

// 发送场景数据
type SceneMessage struct {
	UserData             []*SeatUser `protobuf:"bytes,1,rep,name=UserData,proto3" json:"UserData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SceneMessage) Reset()         { *m = SceneMessage{} }
func (m *SceneMessage) String() string { return proto.CompactTextString(m) }
func (*SceneMessage) ProtoMessage()    {}
func (*SceneMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{5}
}

func (m *SceneMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneMessage.Unmarshal(m, b)
}
func (m *SceneMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneMessage.Marshal(b, m, deterministic)
}
func (m *SceneMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneMessage.Merge(m, src)
}
func (m *SceneMessage) XXX_Size() int {
	return xxx_messageInfo_SceneMessage.Size(m)
}
func (m *SceneMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SceneMessage proto.InternalMessageInfo

func (m *SceneMessage) GetUserData() []*SeatUser {
	if m != nil {
		return m.UserData
	}
	return nil
}

type UserSitDown struct {
	ChairNo              int32    `protobuf:"varint,1,opt,name=ChairNo,proto3" json:"ChairNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSitDown) Reset()         { *m = UserSitDown{} }
func (m *UserSitDown) String() string { return proto.CompactTextString(m) }
func (*UserSitDown) ProtoMessage()    {}
func (*UserSitDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{6}
}

func (m *UserSitDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSitDown.Unmarshal(m, b)
}
func (m *UserSitDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSitDown.Marshal(b, m, deterministic)
}
func (m *UserSitDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSitDown.Merge(m, src)
}
func (m *UserSitDown) XXX_Size() int {
	return xxx_messageInfo_UserSitDown.Size(m)
}
func (m *UserSitDown) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSitDown.DiscardUnknown(m)
}

var xxx_messageInfo_UserSitDown proto.InternalMessageInfo

func (m *UserSitDown) GetChairNo() int32 {
	if m != nil {
		return m.ChairNo
	}
	return 0
}

type UserSitDownFail struct {
	FailReaSon           string   `protobuf:"bytes,1,opt,name=FailReaSon,proto3" json:"FailReaSon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSitDownFail) Reset()         { *m = UserSitDownFail{} }
func (m *UserSitDownFail) String() string { return proto.CompactTextString(m) }
func (*UserSitDownFail) ProtoMessage()    {}
func (*UserSitDownFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{7}
}

func (m *UserSitDownFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSitDownFail.Unmarshal(m, b)
}
func (m *UserSitDownFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSitDownFail.Marshal(b, m, deterministic)
}
func (m *UserSitDownFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSitDownFail.Merge(m, src)
}
func (m *UserSitDownFail) XXX_Size() int {
	return xxx_messageInfo_UserSitDownFail.Size(m)
}
func (m *UserSitDownFail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSitDownFail.DiscardUnknown(m)
}

var xxx_messageInfo_UserSitDownFail proto.InternalMessageInfo

func (m *UserSitDownFail) GetFailReaSon() string {
	if m != nil {
		return m.FailReaSon
	}
	return ""
}

type Poker struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poker) Reset()         { *m = Poker{} }
func (m *Poker) String() string { return proto.CompactTextString(m) }
func (*Poker) ProtoMessage()    {}
func (*Poker) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{8}
}

func (m *Poker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poker.Unmarshal(m, b)
}
func (m *Poker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poker.Marshal(b, m, deterministic)
}
func (m *Poker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poker.Merge(m, src)
}
func (m *Poker) XXX_Size() int {
	return xxx_messageInfo_Poker.Size(m)
}
func (m *Poker) XXX_DiscardUnknown() {
	xxx_messageInfo_Poker.DiscardUnknown(m)
}

var xxx_messageInfo_Poker proto.InternalMessageInfo

func (m *Poker) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

//翻牌数据
type PokerMsg struct {
	Cards                []*Poker `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
	Win                  []bool   `protobuf:"varint,2,rep,packed,name=Win,proto3" json:"Win,omitempty"`
	Type                 []int32  `protobuf:"varint,3,rep,packed,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PokerMsg) Reset()         { *m = PokerMsg{} }
func (m *PokerMsg) String() string { return proto.CompactTextString(m) }
func (*PokerMsg) ProtoMessage()    {}
func (*PokerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{9}
}

func (m *PokerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PokerMsg.Unmarshal(m, b)
}
func (m *PokerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PokerMsg.Marshal(b, m, deterministic)
}
func (m *PokerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PokerMsg.Merge(m, src)
}
func (m *PokerMsg) XXX_Size() int {
	return xxx_messageInfo_PokerMsg.Size(m)
}
func (m *PokerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PokerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PokerMsg proto.InternalMessageInfo

func (m *PokerMsg) GetCards() []*Poker {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *PokerMsg) GetWin() []bool {
	if m != nil {
		return m.Win
	}
	return nil
}

func (m *PokerMsg) GetType() []int32 {
	if m != nil {
		return m.Type
	}
	return nil
}

//结算消息
type SettleMsg struct {
	Win                  []bool   `protobuf:"varint,2,rep,packed,name=Win,proto3" json:"Win,omitempty"`
	UserWin              []int64  `protobuf:"varint,4,rep,packed,name=UserWin,proto3" json:"UserWin,omitempty"`
	UserScore            int64    `protobuf:"varint,8,opt,name=UserScore,proto3" json:"UserScore,omitempty"`
	TotalBetInfo         []int64  `protobuf:"varint,9,rep,packed,name=TotalBetInfo,proto3" json:"TotalBetInfo,omitempty"`
	UserBetInfo          []int64  `protobuf:"varint,10,rep,packed,name=UserBetInfo,proto3" json:"UserBetInfo,omitempty"`
	TotalWin             int64    `protobuf:"varint,15,opt,name=TotalWin,proto3" json:"TotalWin,omitempty"`
	AllKill              bool     `protobuf:"varint,16,opt,name=AllKill,proto3" json:"AllKill,omitempty"`
	AllPay               bool     `protobuf:"varint,17,opt,name=AllPay,proto3" json:"AllPay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleMsg) Reset()         { *m = SettleMsg{} }
func (m *SettleMsg) String() string { return proto.CompactTextString(m) }
func (*SettleMsg) ProtoMessage()    {}
func (*SettleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{10}
}

func (m *SettleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleMsg.Unmarshal(m, b)
}
func (m *SettleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleMsg.Marshal(b, m, deterministic)
}
func (m *SettleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleMsg.Merge(m, src)
}
func (m *SettleMsg) XXX_Size() int {
	return xxx_messageInfo_SettleMsg.Size(m)
}
func (m *SettleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SettleMsg proto.InternalMessageInfo

func (m *SettleMsg) GetWin() []bool {
	if m != nil {
		return m.Win
	}
	return nil
}

func (m *SettleMsg) GetUserWin() []int64 {
	if m != nil {
		return m.UserWin
	}
	return nil
}

func (m *SettleMsg) GetUserScore() int64 {
	if m != nil {
		return m.UserScore
	}
	return 0
}

func (m *SettleMsg) GetTotalBetInfo() []int64 {
	if m != nil {
		return m.TotalBetInfo
	}
	return nil
}

func (m *SettleMsg) GetUserBetInfo() []int64 {
	if m != nil {
		return m.UserBetInfo
	}
	return nil
}

func (m *SettleMsg) GetTotalWin() int64 {
	if m != nil {
		return m.TotalWin
	}
	return 0
}

func (m *SettleMsg) GetAllKill() bool {
	if m != nil {
		return m.AllKill
	}
	return false
}

func (m *SettleMsg) GetAllPay() bool {
	if m != nil {
		return m.AllPay
	}
	return false
}

type SceneBetInfo struct {
	TotalBetInfo         []int64  `protobuf:"varint,1,rep,packed,name=TotalBetInfo,proto3" json:"TotalBetInfo,omitempty"`
	UserBetInfo          []int64  `protobuf:"varint,2,rep,packed,name=UserBetInfo,proto3" json:"UserBetInfo,omitempty"`
	UserBetTotal         int64    `protobuf:"varint,3,opt,name=UserBetTotal,proto3" json:"UserBetTotal,omitempty"`
	MasterBetType        int32    `protobuf:"varint,4,opt,name=MasterBetType,proto3" json:"MasterBetType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneBetInfo) Reset()         { *m = SceneBetInfo{} }
func (m *SceneBetInfo) String() string { return proto.CompactTextString(m) }
func (*SceneBetInfo) ProtoMessage()    {}
func (*SceneBetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{11}
}

func (m *SceneBetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneBetInfo.Unmarshal(m, b)
}
func (m *SceneBetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneBetInfo.Marshal(b, m, deterministic)
}
func (m *SceneBetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneBetInfo.Merge(m, src)
}
func (m *SceneBetInfo) XXX_Size() int {
	return xxx_messageInfo_SceneBetInfo.Size(m)
}
func (m *SceneBetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneBetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SceneBetInfo proto.InternalMessageInfo

func (m *SceneBetInfo) GetTotalBetInfo() []int64 {
	if m != nil {
		return m.TotalBetInfo
	}
	return nil
}

func (m *SceneBetInfo) GetUserBetInfo() []int64 {
	if m != nil {
		return m.UserBetInfo
	}
	return nil
}

func (m *SceneBetInfo) GetUserBetTotal() int64 {
	if m != nil {
		return m.UserBetTotal
	}
	return 0
}

func (m *SceneBetInfo) GetMasterBetType() int32 {
	if m != nil {
		return m.MasterBetType
	}
	return 0
}

type OneTrend struct {
	Win                  bool     `protobuf:"varint,1,opt,name=Win,proto3" json:"Win,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneTrend) Reset()         { *m = OneTrend{} }
func (m *OneTrend) String() string { return proto.CompactTextString(m) }
func (*OneTrend) ProtoMessage()    {}
func (*OneTrend) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{12}
}

func (m *OneTrend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneTrend.Unmarshal(m, b)
}
func (m *OneTrend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneTrend.Marshal(b, m, deterministic)
}
func (m *OneTrend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneTrend.Merge(m, src)
}
func (m *OneTrend) XXX_Size() int {
	return xxx_messageInfo_OneTrend.Size(m)
}
func (m *OneTrend) XXX_DiscardUnknown() {
	xxx_messageInfo_OneTrend.DiscardUnknown(m)
}

var xxx_messageInfo_OneTrend proto.InternalMessageInfo

func (m *OneTrend) GetWin() bool {
	if m != nil {
		return m.Win
	}
	return false
}

func (m *OneTrend) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type TableTrend struct {
	Info                 []*OneTrend `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TableTrend) Reset()         { *m = TableTrend{} }
func (m *TableTrend) String() string { return proto.CompactTextString(m) }
func (*TableTrend) ProtoMessage()    {}
func (*TableTrend) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{13}
}

func (m *TableTrend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableTrend.Unmarshal(m, b)
}
func (m *TableTrend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableTrend.Marshal(b, m, deterministic)
}
func (m *TableTrend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableTrend.Merge(m, src)
}
func (m *TableTrend) XXX_Size() int {
	return xxx_messageInfo_TableTrend.Size(m)
}
func (m *TableTrend) XXX_DiscardUnknown() {
	xxx_messageInfo_TableTrend.DiscardUnknown(m)
}

var xxx_messageInfo_TableTrend proto.InternalMessageInfo

func (m *TableTrend) GetInfo() []*OneTrend {
	if m != nil {
		return m.Info
	}
	return nil
}

type Trend struct {
	TableTrendInfo       []*TableTrend `protobuf:"bytes,1,rep,name=TableTrendInfo,proto3" json:"TableTrendInfo,omitempty"`
	AllKill              int32         `protobuf:"varint,2,opt,name=AllKill,proto3" json:"AllKill,omitempty"`
	AllPay               int32         `protobuf:"varint,3,opt,name=AllPay,proto3" json:"AllPay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Trend) Reset()         { *m = Trend{} }
func (m *Trend) String() string { return proto.CompactTextString(m) }
func (*Trend) ProtoMessage()    {}
func (*Trend) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{14}
}

func (m *Trend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trend.Unmarshal(m, b)
}
func (m *Trend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trend.Marshal(b, m, deterministic)
}
func (m *Trend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trend.Merge(m, src)
}
func (m *Trend) XXX_Size() int {
	return xxx_messageInfo_Trend.Size(m)
}
func (m *Trend) XXX_DiscardUnknown() {
	xxx_messageInfo_Trend.DiscardUnknown(m)
}

var xxx_messageInfo_Trend proto.InternalMessageInfo

func (m *Trend) GetTableTrendInfo() []*TableTrend {
	if m != nil {
		return m.TableTrendInfo
	}
	return nil
}

func (m *Trend) GetAllKill() int32 {
	if m != nil {
		return m.AllKill
	}
	return 0
}

func (m *Trend) GetAllPay() int32 {
	if m != nil {
		return m.AllPay
	}
	return 0
}

type UserInfo struct {
	NikeName             string   `protobuf:"bytes,1,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	UserGlod             int64    `protobuf:"varint,2,opt,name=UserGlod,proto3" json:"UserGlod,omitempty"`
	BetGold              int64    `protobuf:"varint,3,opt,name=BetGold,proto3" json:"BetGold,omitempty"`
	WinCount             int32    `protobuf:"varint,4,opt,name=WinCount,proto3" json:"WinCount,omitempty"`
	Head                 string   `protobuf:"bytes,5,opt,name=Head,proto3" json:"Head,omitempty"`
	Icon                 int32    `protobuf:"varint,6,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{15}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *UserInfo) GetUserGlod() int64 {
	if m != nil {
		return m.UserGlod
	}
	return 0
}

func (m *UserInfo) GetBetGold() int64 {
	if m != nil {
		return m.BetGold
	}
	return 0
}

func (m *UserInfo) GetWinCount() int32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *UserInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UserInfo) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

//用户列表
type UserList struct {
	UserList             []*UserInfo `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
	ZhuangInfo           *UserInfo   `protobuf:"bytes,2,opt,name=ZhuangInfo,proto3" json:"ZhuangInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{16}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *UserList) GetZhuangInfo() *UserInfo {
	if m != nil {
		return m.ZhuangInfo
	}
	return nil
}

type SceneUserInfo struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SceneSeatID          int32    `protobuf:"varint,2,opt,name=SceneSeatID,proto3" json:"SceneSeatID,omitempty"`
	WinGold              []int64  `protobuf:"varint,3,rep,packed,name=WinGold,proto3" json:"WinGold,omitempty"`
	UserScore            int64    `protobuf:"varint,6,opt,name=UserScore,proto3" json:"UserScore,omitempty"`
	TotalWin             int64    `protobuf:"varint,7,opt,name=TotalWin,proto3" json:"TotalWin,omitempty"`
	BetInfo              []int64  `protobuf:"varint,8,rep,packed,name=BetInfo,proto3" json:"BetInfo,omitempty"`
	AreaWin              []int64  `protobuf:"varint,9,rep,packed,name=AreaWin,proto3" json:"AreaWin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneUserInfo) Reset()         { *m = SceneUserInfo{} }
func (m *SceneUserInfo) String() string { return proto.CompactTextString(m) }
func (*SceneUserInfo) ProtoMessage()    {}
func (*SceneUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{17}
}

func (m *SceneUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneUserInfo.Unmarshal(m, b)
}
func (m *SceneUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneUserInfo.Marshal(b, m, deterministic)
}
func (m *SceneUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneUserInfo.Merge(m, src)
}
func (m *SceneUserInfo) XXX_Size() int {
	return xxx_messageInfo_SceneUserInfo.Size(m)
}
func (m *SceneUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SceneUserInfo proto.InternalMessageInfo

func (m *SceneUserInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SceneUserInfo) GetSceneSeatID() int32 {
	if m != nil {
		return m.SceneSeatID
	}
	return 0
}

func (m *SceneUserInfo) GetWinGold() []int64 {
	if m != nil {
		return m.WinGold
	}
	return nil
}

func (m *SceneUserInfo) GetUserScore() int64 {
	if m != nil {
		return m.UserScore
	}
	return 0
}

func (m *SceneUserInfo) GetTotalWin() int64 {
	if m != nil {
		return m.TotalWin
	}
	return 0
}

func (m *SceneUserInfo) GetBetInfo() []int64 {
	if m != nil {
		return m.BetInfo
	}
	return nil
}

func (m *SceneUserInfo) GetAreaWin() []int64 {
	if m != nil {
		return m.AreaWin
	}
	return nil
}

//场景上的玩家结算信息
type SceneUserSettle struct {
	UserList             []*SceneUserInfo `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SceneUserSettle) Reset()         { *m = SceneUserSettle{} }
func (m *SceneUserSettle) String() string { return proto.CompactTextString(m) }
func (*SceneUserSettle) ProtoMessage()    {}
func (*SceneUserSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{18}
}

func (m *SceneUserSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneUserSettle.Unmarshal(m, b)
}
func (m *SceneUserSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneUserSettle.Marshal(b, m, deterministic)
}
func (m *SceneUserSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneUserSettle.Merge(m, src)
}
func (m *SceneUserSettle) XXX_Size() int {
	return xxx_messageInfo_SceneUserSettle.Size(m)
}
func (m *SceneUserSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneUserSettle.DiscardUnknown(m)
}

var xxx_messageInfo_SceneUserSettle proto.InternalMessageInfo

func (m *SceneUserSettle) GetUserList() []*SceneUserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

type ExitFail struct {
	FailReason           string   `protobuf:"bytes,1,opt,name=FailReason,proto3" json:"FailReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitFail) Reset()         { *m = ExitFail{} }
func (m *ExitFail) String() string { return proto.CompactTextString(m) }
func (*ExitFail) ProtoMessage()    {}
func (*ExitFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{19}
}

func (m *ExitFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitFail.Unmarshal(m, b)
}
func (m *ExitFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitFail.Marshal(b, m, deterministic)
}
func (m *ExitFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitFail.Merge(m, src)
}
func (m *ExitFail) XXX_Size() int {
	return xxx_messageInfo_ExitFail.Size(m)
}
func (m *ExitFail) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitFail.DiscardUnknown(m)
}

var xxx_messageInfo_ExitFail proto.InternalMessageInfo

func (m *ExitFail) GetFailReason() string {
	if m != nil {
		return m.FailReason
	}
	return ""
}

type KickOutUserMsg struct {
	KickOutReason        string   `protobuf:"bytes,1,opt,name=KickOutReason,proto3" json:"KickOutReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickOutUserMsg) Reset()         { *m = KickOutUserMsg{} }
func (m *KickOutUserMsg) String() string { return proto.CompactTextString(m) }
func (*KickOutUserMsg) ProtoMessage()    {}
func (*KickOutUserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{20}
}

func (m *KickOutUserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickOutUserMsg.Unmarshal(m, b)
}
func (m *KickOutUserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickOutUserMsg.Marshal(b, m, deterministic)
}
func (m *KickOutUserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickOutUserMsg.Merge(m, src)
}
func (m *KickOutUserMsg) XXX_Size() int {
	return xxx_messageInfo_KickOutUserMsg.Size(m)
}
func (m *KickOutUserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KickOutUserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KickOutUserMsg proto.InternalMessageInfo

func (m *KickOutUserMsg) GetKickOutReason() string {
	if m != nil {
		return m.KickOutReason
	}
	return ""
}

type RoomRolesInfoMsg struct {
	BetArr               []int32  `protobuf:"varint,1,rep,packed,name=BetArr,proto3" json:"BetArr,omitempty"`
	UserBetLimit         int32    `protobuf:"varint,2,opt,name=UserBetLimit,proto3" json:"UserBetLimit,omitempty"`
	OddsInfo             int32    `protobuf:"varint,3,opt,name=OddsInfo,proto3" json:"OddsInfo,omitempty"`
	ZhuangLimit          int64    `protobuf:"varint,4,opt,name=ZhuangLimit,proto3" json:"ZhuangLimit,omitempty"`
	BetMinLimit          int64    `protobuf:"varint,5,opt,name=BetMinLimit,proto3" json:"BetMinLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRolesInfoMsg) Reset()         { *m = RoomRolesInfoMsg{} }
func (m *RoomRolesInfoMsg) String() string { return proto.CompactTextString(m) }
func (*RoomRolesInfoMsg) ProtoMessage()    {}
func (*RoomRolesInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{21}
}

func (m *RoomRolesInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRolesInfoMsg.Unmarshal(m, b)
}
func (m *RoomRolesInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRolesInfoMsg.Marshal(b, m, deterministic)
}
func (m *RoomRolesInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRolesInfoMsg.Merge(m, src)
}
func (m *RoomRolesInfoMsg) XXX_Size() int {
	return xxx_messageInfo_RoomRolesInfoMsg.Size(m)
}
func (m *RoomRolesInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRolesInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRolesInfoMsg proto.InternalMessageInfo

func (m *RoomRolesInfoMsg) GetBetArr() []int32 {
	if m != nil {
		return m.BetArr
	}
	return nil
}

func (m *RoomRolesInfoMsg) GetUserBetLimit() int32 {
	if m != nil {
		return m.UserBetLimit
	}
	return 0
}

func (m *RoomRolesInfoMsg) GetOddsInfo() int32 {
	if m != nil {
		return m.OddsInfo
	}
	return 0
}

func (m *RoomRolesInfoMsg) GetZhuangLimit() int64 {
	if m != nil {
		return m.ZhuangLimit
	}
	return 0
}

func (m *RoomRolesInfoMsg) GetBetMinLimit() int64 {
	if m != nil {
		return m.BetMinLimit
	}
	return 0
}

type ZhuangInfo struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	Gold                 int64    `protobuf:"varint,3,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Head                 string   `protobuf:"bytes,4,opt,name=Head,proto3" json:"Head,omitempty"`
	ZhuangTotalWin       int64    `protobuf:"varint,5,opt,name=ZhuangTotalWin,proto3" json:"ZhuangTotalWin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhuangInfo) Reset()         { *m = ZhuangInfo{} }
func (m *ZhuangInfo) String() string { return proto.CompactTextString(m) }
func (*ZhuangInfo) ProtoMessage()    {}
func (*ZhuangInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{22}
}

func (m *ZhuangInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhuangInfo.Unmarshal(m, b)
}
func (m *ZhuangInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhuangInfo.Marshal(b, m, deterministic)
}
func (m *ZhuangInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhuangInfo.Merge(m, src)
}
func (m *ZhuangInfo) XXX_Size() int {
	return xxx_messageInfo_ZhuangInfo.Size(m)
}
func (m *ZhuangInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhuangInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZhuangInfo proto.InternalMessageInfo

func (m *ZhuangInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ZhuangInfo) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *ZhuangInfo) GetGold() int64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *ZhuangInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *ZhuangInfo) GetZhuangTotalWin() int64 {
	if m != nil {
		return m.ZhuangTotalWin
	}
	return 0
}

type CurrZhuangInfo struct {
	UserInfo             *ZhuangInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	Lastcount            int32       `protobuf:"varint,2,opt,name=Lastcount,proto3" json:"Lastcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CurrZhuangInfo) Reset()         { *m = CurrZhuangInfo{} }
func (m *CurrZhuangInfo) String() string { return proto.CompactTextString(m) }
func (*CurrZhuangInfo) ProtoMessage()    {}
func (*CurrZhuangInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{23}
}

func (m *CurrZhuangInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrZhuangInfo.Unmarshal(m, b)
}
func (m *CurrZhuangInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrZhuangInfo.Marshal(b, m, deterministic)
}
func (m *CurrZhuangInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrZhuangInfo.Merge(m, src)
}
func (m *CurrZhuangInfo) XXX_Size() int {
	return xxx_messageInfo_CurrZhuangInfo.Size(m)
}
func (m *CurrZhuangInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrZhuangInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CurrZhuangInfo proto.InternalMessageInfo

func (m *CurrZhuangInfo) GetUserInfo() *ZhuangInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *CurrZhuangInfo) GetLastcount() int32 {
	if m != nil {
		return m.Lastcount
	}
	return 0
}

type ZhuangListInfo struct {
	CurrZhuangUserInfo   *CurrZhuangInfo `protobuf:"bytes,1,opt,name=CurrZhuangUserInfo,proto3" json:"CurrZhuangUserInfo,omitempty"`
	List                 []*ZhuangInfo   `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ZhuangListInfo) Reset()         { *m = ZhuangListInfo{} }
func (m *ZhuangListInfo) String() string { return proto.CompactTextString(m) }
func (*ZhuangListInfo) ProtoMessage()    {}
func (*ZhuangListInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{24}
}

func (m *ZhuangListInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhuangListInfo.Unmarshal(m, b)
}
func (m *ZhuangListInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhuangListInfo.Marshal(b, m, deterministic)
}
func (m *ZhuangListInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhuangListInfo.Merge(m, src)
}
func (m *ZhuangListInfo) XXX_Size() int {
	return xxx_messageInfo_ZhuangListInfo.Size(m)
}
func (m *ZhuangListInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhuangListInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZhuangListInfo proto.InternalMessageInfo

func (m *ZhuangListInfo) GetCurrZhuangUserInfo() *CurrZhuangInfo {
	if m != nil {
		return m.CurrZhuangUserInfo
	}
	return nil
}

func (m *ZhuangListInfo) GetList() []*ZhuangInfo {
	if m != nil {
		return m.List
	}
	return nil
}

//次消息一秒一次
type RoomSenceInfoMsg struct {
	RoomID               int64          `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	TrendList            *Trend         `protobuf:"bytes,2,opt,name=TrendList,proto3" json:"TrendList,omitempty"`
	GameStatus           *StatusMessage `protobuf:"bytes,3,opt,name=GameStatus,proto3" json:"GameStatus,omitempty"`
	BaseBet              int64          `protobuf:"varint,4,opt,name=BaseBet,proto3" json:"BaseBet,omitempty"`
	UserLimit            int64          `protobuf:"varint,5,opt,name=UserLimit,proto3" json:"UserLimit,omitempty"`
	AllKill              int32          `protobuf:"varint,6,opt,name=AllKill,proto3" json:"AllKill,omitempty"`
	AllPei               int32          `protobuf:"varint,7,opt,name=AllPei,proto3" json:"AllPei,omitempty"`
	OddsInfo             int32          `protobuf:"varint,8,opt,name=OddsInfo,proto3" json:"OddsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomSenceInfoMsg) Reset()         { *m = RoomSenceInfoMsg{} }
func (m *RoomSenceInfoMsg) String() string { return proto.CompactTextString(m) }
func (*RoomSenceInfoMsg) ProtoMessage()    {}
func (*RoomSenceInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{25}
}

func (m *RoomSenceInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSenceInfoMsg.Unmarshal(m, b)
}
func (m *RoomSenceInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSenceInfoMsg.Marshal(b, m, deterministic)
}
func (m *RoomSenceInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSenceInfoMsg.Merge(m, src)
}
func (m *RoomSenceInfoMsg) XXX_Size() int {
	return xxx_messageInfo_RoomSenceInfoMsg.Size(m)
}
func (m *RoomSenceInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSenceInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSenceInfoMsg proto.InternalMessageInfo

func (m *RoomSenceInfoMsg) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomSenceInfoMsg) GetTrendList() *Trend {
	if m != nil {
		return m.TrendList
	}
	return nil
}

func (m *RoomSenceInfoMsg) GetGameStatus() *StatusMessage {
	if m != nil {
		return m.GameStatus
	}
	return nil
}

func (m *RoomSenceInfoMsg) GetBaseBet() int64 {
	if m != nil {
		return m.BaseBet
	}
	return 0
}

func (m *RoomSenceInfoMsg) GetUserLimit() int64 {
	if m != nil {
		return m.UserLimit
	}
	return 0
}

func (m *RoomSenceInfoMsg) GetAllKill() int32 {
	if m != nil {
		return m.AllKill
	}
	return 0
}

func (m *RoomSenceInfoMsg) GetAllPei() int32 {
	if m != nil {
		return m.AllPei
	}
	return 0
}

func (m *RoomSenceInfoMsg) GetOddsInfo() int32 {
	if m != nil {
		return m.OddsInfo
	}
	return 0
}

type ZhuangCount struct {
	Count                int32    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhuangCount) Reset()         { *m = ZhuangCount{} }
func (m *ZhuangCount) String() string { return proto.CompactTextString(m) }
func (*ZhuangCount) ProtoMessage()    {}
func (*ZhuangCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{26}
}

func (m *ZhuangCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhuangCount.Unmarshal(m, b)
}
func (m *ZhuangCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhuangCount.Marshal(b, m, deterministic)
}
func (m *ZhuangCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhuangCount.Merge(m, src)
}
func (m *ZhuangCount) XXX_Size() int {
	return xxx_messageInfo_ZhuangCount.Size(m)
}
func (m *ZhuangCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhuangCount.DiscardUnknown(m)
}

var xxx_messageInfo_ZhuangCount proto.InternalMessageInfo

func (m *ZhuangCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//测试
type TempCardMsg struct {
	Cards                [][]byte `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TempCardMsg) Reset()         { *m = TempCardMsg{} }
func (m *TempCardMsg) String() string { return proto.CompactTextString(m) }
func (*TempCardMsg) ProtoMessage()    {}
func (*TempCardMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{27}
}

func (m *TempCardMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TempCardMsg.Unmarshal(m, b)
}
func (m *TempCardMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TempCardMsg.Marshal(b, m, deterministic)
}
func (m *TempCardMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TempCardMsg.Merge(m, src)
}
func (m *TempCardMsg) XXX_Size() int {
	return xxx_messageInfo_TempCardMsg.Size(m)
}
func (m *TempCardMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TempCardMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TempCardMsg proto.InternalMessageInfo

func (m *TempCardMsg) GetCards() [][]byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 结束下注后各个区域的下注金额
type BroadBetEnd struct {
	BetGold              []int64  `protobuf:"varint,1,rep,packed,name=BetGold,proto3" json:"BetGold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadBetEnd) Reset()         { *m = BroadBetEnd{} }
func (m *BroadBetEnd) String() string { return proto.CompactTextString(m) }
func (*BroadBetEnd) ProtoMessage()    {}
func (*BroadBetEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65a774ab30247e, []int{28}
}

func (m *BroadBetEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadBetEnd.Unmarshal(m, b)
}
func (m *BroadBetEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadBetEnd.Marshal(b, m, deterministic)
}
func (m *BroadBetEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadBetEnd.Merge(m, src)
}
func (m *BroadBetEnd) XXX_Size() int {
	return xxx_messageInfo_BroadBetEnd.Size(m)
}
func (m *BroadBetEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadBetEnd.DiscardUnknown(m)
}

var xxx_messageInfo_BroadBetEnd proto.InternalMessageInfo

func (m *BroadBetEnd) GetBetGold() []int64 {
	if m != nil {
		return m.BetGold
	}
	return nil
}

func init() {
	proto.RegisterEnum("ReceiveMessageType", ReceiveMessageType_name, ReceiveMessageType_value)
	proto.RegisterEnum("SendToClientMessageType", SendToClientMessageType_name, SendToClientMessageType_value)
	proto.RegisterEnum("GameStatus", GameStatus_name, GameStatus_value)
	proto.RegisterType((*StatusMessage)(nil), "StatusMessage")
	proto.RegisterType((*BetFailMessage)(nil), "BetFailMessage")
	proto.RegisterType((*BetSuccessMessage)(nil), "BetSuccessMessage")
	proto.RegisterType((*Bet)(nil), "Bet")
	proto.RegisterType((*SeatUser)(nil), "SeatUser")
	proto.RegisterType((*SceneMessage)(nil), "SceneMessage")
	proto.RegisterType((*UserSitDown)(nil), "UserSitDown")
	proto.RegisterType((*UserSitDownFail)(nil), "UserSitDownFail")
	proto.RegisterType((*Poker)(nil), "Poker")
	proto.RegisterType((*PokerMsg)(nil), "PokerMsg")
	proto.RegisterType((*SettleMsg)(nil), "SettleMsg")
	proto.RegisterType((*SceneBetInfo)(nil), "SceneBetInfo")
	proto.RegisterType((*OneTrend)(nil), "OneTrend")
	proto.RegisterType((*TableTrend)(nil), "TableTrend")
	proto.RegisterType((*Trend)(nil), "Trend")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*UserList)(nil), "UserList")
	proto.RegisterType((*SceneUserInfo)(nil), "SceneUserInfo")
	proto.RegisterType((*SceneUserSettle)(nil), "SceneUserSettle")
	proto.RegisterType((*ExitFail)(nil), "ExitFail")
	proto.RegisterType((*KickOutUserMsg)(nil), "KickOutUserMsg")
	proto.RegisterType((*RoomRolesInfoMsg)(nil), "RoomRolesInfoMsg")
	proto.RegisterType((*ZhuangInfo)(nil), "ZhuangInfo")
	proto.RegisterType((*CurrZhuangInfo)(nil), "CurrZhuangInfo")
	proto.RegisterType((*ZhuangListInfo)(nil), "ZhuangListInfo")
	proto.RegisterType((*RoomSenceInfoMsg)(nil), "RoomSenceInfoMsg")
	proto.RegisterType((*ZhuangCount)(nil), "ZhuangCount")
	proto.RegisterType((*TempCardMsg)(nil), "tempCardMsg")
	proto.RegisterType((*BroadBetEnd)(nil), "BroadBetEnd")
}

func init() { proto.RegisterFile("BRZJH.proto", fileDescriptor_4d65a774ab30247e) }

var fileDescriptor_4d65a774ab30247e = []byte{
	// 1467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0x4f, 0x6f, 0x1b, 0xb7,
	0x12, 0xcf, 0x6a, 0xf5, 0x67, 0x35, 0xb2, 0x24, 0x9a, 0xc9, 0x4b, 0x84, 0x87, 0xe4, 0x3d, 0x61,
	0x5f, 0x5e, 0xe3, 0xba, 0x80, 0xd0, 0x26, 0x68, 0x2f, 0x45, 0x51, 0x44, 0x56, 0xaa, 0xa8, 0x89,
	0x9d, 0x60, 0xe5, 0xc0, 0x45, 0xd0, 0xcb, 0x46, 0x62, 0x6d, 0xc2, 0xab, 0x5d, 0x63, 0x97, 0xce,
	0x9f, 0x5b, 0x4f, 0x3d, 0xf7, 0x13, 0x14, 0x3d, 0xf7, 0xd0, 0xef, 0xd2, 0x7b, 0xbf, 0x40, 0xbf,
	0x45, 0x31, 0x43, 0x72, 0x97, 0x2b, 0xa7, 0xed, 0x49, 0x9c, 0xe1, 0x0c, 0x39, 0xfc, 0xf1, 0x37,
	0xbf, 0xa5, 0xa0, 0x37, 0x8d, 0x5e, 0x7e, 0xfd, 0x78, 0x72, 0x91, 0x67, 0x2a, 0x0b, 0xe7, 0xd0,
	0x5f, 0xaa, 0x58, 0x5d, 0x16, 0x87, 0xa2, 0x28, 0xe2, 0x53, 0xc1, 0x6f, 0x42, 0x5b, 0x3b, 0x46,
	0xde, 0xd8, 0xdb, 0x6b, 0x45, 0xc6, 0xe2, 0xff, 0x01, 0xd0, 0xa3, 0x63, 0xb9, 0x11, 0xa3, 0x06,
	0xcd, 0x39, 0x9e, 0xf0, 0x3e, 0x0c, 0xa6, 0x42, 0x7d, 0x15, 0xcb, 0xc4, 0xae, 0x34, 0x86, 0x9e,
	0x63, 0xd2, 0x72, 0xdd, 0xc8, 0x75, 0x85, 0xef, 0x60, 0x77, 0x2a, 0xd4, 0xf2, 0x72, 0xb5, 0x12,
	0x45, 0xad, 0x00, 0x11, 0xab, 0xc5, 0xba, 0x2c, 0x80, 0x2c, 0xfe, 0x6f, 0x08, 0xa6, 0x42, 0x2d,
	0xd2, 0xb5, 0x78, 0x6b, 0xb6, 0x2f, 0x6d, 0x3e, 0x82, 0xce, 0x54, 0xa8, 0xe3, 0x77, 0x17, 0x62,
	0xe4, 0xd3, 0x94, 0x35, 0x71, 0xb5, 0x17, 0x85, 0xc8, 0x17, 0xb3, 0x51, 0x73, 0xec, 0xed, 0xf9,
	0x91, 0xb1, 0xc2, 0xcf, 0xc1, 0x9f, 0x0a, 0xe5, 0x26, 0x7a, 0xf5, 0xc4, 0xbf, 0xd9, 0x2e, 0xfc,
	0xdd, 0x83, 0x00, 0xab, 0xc2, 0xb5, 0x38, 0x87, 0xe6, 0x91, 0x5c, 0x9d, 0x9b, 0xf3, 0xd1, 0x18,
	0x7d, 0x8f, 0x45, 0xbc, 0xa6, 0xc4, 0x6e, 0x44, 0x63, 0x7e, 0x03, 0x5a, 0xcb, 0x55, 0x96, 0xeb,
	0x0a, 0xfd, 0x48, 0x1b, 0x08, 0xd2, 0xa2, 0x98, 0xca, 0xd3, 0x13, 0x99, 0xa6, 0x22, 0xa7, 0x22,
	0x83, 0xc8, 0x75, 0x61, 0x21, 0x8b, 0xe2, 0x30, 0x2e, 0x94, 0xc8, 0x47, 0x2d, 0x9a, 0x2e, 0x6d,
	0x07, 0xab, 0x76, 0x0d, 0xab, 0xea, 0xd4, 0x1d, 0xf7, 0xd4, 0xfc, 0x2e, 0xf4, 0x17, 0xc5, 0xa1,
	0x4c, 0x12, 0x99, 0xa5, 0xb1, 0xcc, 0xc5, 0x28, 0xa0, 0x05, 0xeb, 0xce, 0xf0, 0x53, 0xd8, 0x59,
	0xae, 0x44, 0x2a, 0xec, 0x8d, 0xfc, 0x1f, 0x02, 0xcc, 0x9f, 0xc5, 0x2a, 0x1e, 0x79, 0x63, 0x7f,
	0xaf, 0x77, 0xbf, 0x3b, 0xb1, 0xc7, 0x8f, 0xca, 0xa9, 0xf0, 0x1e, 0xf4, 0x70, 0xbc, 0x94, 0x6a,
	0x96, 0xbd, 0x49, 0x11, 0xda, 0x83, 0xb3, 0x58, 0xe6, 0x47, 0x99, 0x85, 0xd6, 0x98, 0xe1, 0x27,
	0x30, 0x74, 0x02, 0x91, 0x10, 0xc8, 0x2e, 0xfc, 0x8d, 0x44, 0xbc, 0xcc, 0x52, 0x03, 0xa5, 0xe3,
	0x09, 0xef, 0x40, 0xeb, 0x79, 0x76, 0x2e, 0x72, 0x44, 0xf1, 0x20, 0xce, 0xd7, 0x9a, 0x9d, 0x3b,
	0x91, 0x36, 0xc2, 0x23, 0x08, 0x68, 0xfa, 0xb0, 0x38, 0xe5, 0xb7, 0xab, 0x08, 0x2c, 0xb5, 0x3d,
	0xa1, 0x19, 0x13, 0xc9, 0x19, 0xf8, 0x27, 0x32, 0x1d, 0x35, 0xc6, 0xfe, 0x5e, 0x10, 0xe1, 0x10,
	0xef, 0xca, 0x10, 0xc7, 0xdf, 0x6b, 0x45, 0x34, 0x0e, 0xff, 0xf0, 0xa0, 0xbb, 0x14, 0x4a, 0x25,
	0x02, 0x57, 0xbc, 0x9a, 0x33, 0x82, 0x0e, 0x9e, 0x00, 0xbd, 0xcd, 0xb1, 0xbf, 0xe7, 0x47, 0xd6,
	0xe4, 0xb7, 0xa1, 0x4b, 0x67, 0xa3, 0x9b, 0x0e, 0x08, 0xfc, 0xca, 0xc1, 0x43, 0xd8, 0x39, 0xce,
	0x54, 0x9c, 0x10, 0x93, 0xbe, 0xcb, 0x46, 0x5d, 0x4a, 0xae, 0xf9, 0x90, 0x11, 0x98, 0x60, 0x43,
	0x80, 0x42, 0x5c, 0x17, 0x32, 0x82, 0x32, 0x70, 0xfb, 0x21, 0x6d, 0x51, 0xda, 0x58, 0xd9, 0xc3,
	0x24, 0x79, 0x22, 0x93, 0x64, 0xc4, 0xe8, 0x6e, 0xad, 0x89, 0x9c, 0x78, 0x98, 0x24, 0xcf, 0xe3,
	0x77, 0xa3, 0x5d, 0x9a, 0x30, 0x56, 0xf8, 0x93, 0x67, 0xae, 0xdb, 0x2e, 0xbf, 0x5d, 0xa4, 0xf7,
	0xcf, 0x45, 0x36, 0xae, 0x16, 0x19, 0xc2, 0x8e, 0x31, 0x29, 0xd1, 0xb0, 0xbe, 0xe6, 0x43, 0x3a,
	0x6a, 0x22, 0xdb, 0x1e, 0x6c, 0x12, 0x51, 0xea, 0xce, 0xf0, 0x63, 0x08, 0x9e, 0xa5, 0xe2, 0x38,
	0x17, 0xe9, 0xda, 0x5e, 0x85, 0x47, 0x27, 0xa8, 0x5d, 0x9f, 0xee, 0x51, 0x7d, 0x7d, 0x1f, 0x01,
	0x1c, 0xc7, 0xaf, 0x12, 0x93, 0x73, 0x07, 0x9a, 0xd2, 0x9e, 0x03, 0xa9, 0x6b, 0x17, 0x8b, 0xc8,
	0x1d, 0xa6, 0xd0, 0xd2, 0x71, 0x0f, 0x60, 0x50, 0x65, 0x2d, 0xaa, 0x8c, 0xde, 0xa4, 0x72, 0x47,
	0x5b, 0x21, 0x2e, 0xde, 0xba, 0x82, 0xf7, 0xe0, 0xad, 0x25, 0xc9, 0xe2, 0xfd, 0xb3, 0xa7, 0xdb,
	0xc9, 0x5e, 0xe5, 0x91, 0x3c, 0x17, 0x47, 0xf1, 0xc6, 0x0a, 0x64, 0x69, 0xe3, 0x1c, 0xc6, 0xcd,
	0x93, 0x4c, 0x0b, 0x89, 0x1f, 0x95, 0xb6, 0xd1, 0xad, 0x79, 0x96, 0xac, 0x0d, 0xb0, 0xd6, 0xc4,
	0xac, 0x13, 0x99, 0x1e, 0x64, 0x97, 0xa9, 0x32, 0x70, 0x96, 0x76, 0x29, 0x4b, 0x2d, 0x47, 0x96,
	0x38, 0x34, 0xe5, 0x2a, 0x4b, 0x8d, 0x80, 0xd0, 0x38, 0xfc, 0x56, 0xef, 0xfc, 0x54, 0x16, 0xca,
	0x36, 0x3f, 0x8e, 0x4b, 0x04, 0x6d, 0xf9, 0x51, 0x15, 0xf6, 0x21, 0xc0, 0xcb, 0xb3, 0xcb, 0x38,
	0x3d, 0x35, 0x7c, 0xf0, 0xea, 0x81, 0xce, 0x64, 0xf8, 0x9b, 0x07, 0x7d, 0x22, 0x5c, 0x89, 0x42,
	0x25, 0x57, 0x5e, 0x4d, 0xae, 0xc6, 0xd0, 0xa3, 0x40, 0x52, 0xb5, 0x99, 0x01, 0xd8, 0x75, 0x21,
	0x0e, 0x27, 0x32, 0x35, 0x38, 0x50, 0x23, 0x1a, 0xb3, 0xde, 0x88, 0xed, 0xed, 0x46, 0x74, 0x5b,
	0xa8, 0x73, 0xb5, 0x85, 0x2c, 0xaf, 0x03, 0xbd, 0xa6, 0xe5, 0x34, 0x5e, 0x76, 0x2e, 0x62, 0x4c,
	0xd2, 0x9d, 0x6b, 0xcd, 0xf0, 0x0b, 0x18, 0x96, 0x47, 0xd2, 0xc2, 0xc1, 0xf7, 0xaf, 0x00, 0x37,
	0x98, 0xd4, 0x8e, 0x5d, 0xa1, 0x17, 0xee, 0x43, 0xf0, 0xe8, 0xad, 0x54, 0x5b, 0x52, 0x58, 0x5c,
	0x91, 0xc2, 0x22, 0x4b, 0xc3, 0xcf, 0x60, 0xf0, 0x44, 0xae, 0xce, 0x9f, 0x5d, 0x92, 0xfe, 0xa2,
	0x3e, 0xdd, 0x85, 0xbe, 0xf1, 0xd4, 0x92, 0xea, 0xce, 0xf0, 0x57, 0x0f, 0x58, 0x94, 0x65, 0x9b,
	0x28, 0x4b, 0x44, 0x81, 0xfb, 0x63, 0xea, 0x4d, 0x68, 0x4f, 0x85, 0x7a, 0x98, 0xe7, 0x54, 0x62,
	0x2b, 0x32, 0x96, 0xd3, 0xbd, 0x4f, 0xe5, 0x46, 0x2a, 0x03, 0x7d, 0xcd, 0x87, 0x18, 0x3e, 0x5b,
	0xaf, 0x69, 0x29, 0x43, 0xf1, 0xd2, 0xc6, 0x9b, 0xd3, 0x37, 0xae, 0xd3, 0xf5, 0xb7, 0xd7, 0x75,
	0x61, 0xc4, 0x54, 0xa8, 0x43, 0x99, 0xea, 0x88, 0x96, 0x8e, 0x70, 0x5c, 0xe1, 0x8f, 0x9e, 0xcb,
	0xa9, 0xbf, 0x24, 0x89, 0xdb, 0x42, 0x8d, 0xad, 0x16, 0xe2, 0xd0, 0x74, 0x7a, 0x84, 0xc6, 0x65,
	0x13, 0x34, 0x9d, 0x26, 0xf8, 0x00, 0x06, 0x7a, 0xa7, 0x92, 0x14, 0xba, 0x9e, 0x2d, 0x6f, 0x78,
	0x02, 0x83, 0x83, 0xcb, 0x3c, 0x77, 0xaa, 0xba, 0x57, 0x35, 0x33, 0xd5, 0x85, 0x72, 0x51, 0x4d,
	0x47, 0x55, 0xa7, 0xdf, 0x86, 0xee, 0xd3, 0xb8, 0x50, 0x2b, 0x6a, 0x4c, 0x0d, 0x67, 0xe5, 0x08,
	0x73, 0x5b, 0x00, 0xd2, 0x81, 0xe2, 0xbf, 0x04, 0x5e, 0x6d, 0xb5, 0xb5, 0xc5, 0x70, 0x52, 0xaf,
	0x22, 0x7a, 0x4f, 0x28, 0xff, 0x2f, 0x34, 0x89, 0x7b, 0x0d, 0x23, 0x62, 0x4e, 0x38, 0x4d, 0x84,
	0x3f, 0x34, 0x34, 0x21, 0x96, 0x22, 0x5d, 0x09, 0x87, 0x10, 0xe8, 0xab, 0x50, 0xd6, 0x16, 0xbf,
	0x0b, 0x5d, 0x12, 0x3d, 0xb3, 0xa4, 0x47, 0x5f, 0x56, 0x2d, 0x89, 0xd5, 0x04, 0x9f, 0x00, 0xcc,
	0xe3, 0x8d, 0x30, 0x0f, 0x48, 0x9f, 0xc2, 0x06, 0x93, 0xda, 0x03, 0x33, 0x72, 0x22, 0xa8, 0xd5,
	0xe2, 0x02, 0xbf, 0x3c, 0x86, 0x22, 0xd6, 0xb4, 0xed, 0xeb, 0x92, 0xa3, 0x72, 0xb8, 0xaa, 0xdb,
	0x7e, 0xaf, 0xea, 0x0a, 0x49, 0x6d, 0x6d, 0x54, 0x57, 0xc8, 0x1a, 0x59, 0x83, 0x3a, 0x59, 0xc3,
	0xff, 0x59, 0xb2, 0x6a, 0x95, 0xc4, 0x27, 0x06, 0xdd, 0x92, 0x7e, 0xb6, 0x68, 0x03, 0x83, 0x94,
	0xd8, 0x5c, 0xe0, 0x2b, 0x02, 0x71, 0xba, 0xe1, 0xbe, 0x32, 0xca, 0x77, 0xc8, 0x3d, 0xe8, 0x4d,
	0xf3, 0x2c, 0x5e, 0x4f, 0x85, 0x7a, 0x94, 0xd6, 0x54, 0xda, 0x2b, 0x95, 0x04, 0xcd, 0xfd, 0x5f,
	0x3c, 0xe0, 0x91, 0x58, 0x09, 0xf9, 0xda, 0xbe, 0xb2, 0xe8, 0xd1, 0xd9, 0x83, 0xce, 0x52, 0xc5,
	0xb9, 0x5a, 0xcc, 0xd8, 0x35, 0xde, 0x85, 0x16, 0x0a, 0xcf, 0x8c, 0x79, 0xe4, 0xd7, 0xaf, 0x25,
	0xd6, 0xe0, 0x3b, 0x10, 0xcc, 0x85, 0x22, 0xd0, 0x99, 0xcf, 0xaf, 0xc3, 0x70, 0x2e, 0x94, 0x55,
	0x12, 0x3c, 0x0f, 0x6b, 0x9a, 0x75, 0xd2, 0xf5, 0x8b, 0x0b, 0xd6, 0xe2, 0x43, 0xe8, 0x2d, 0xcf,
	0xe2, 0xf4, 0x54, 0x9f, 0x91, 0xb5, 0xf9, 0x2e, 0xf4, 0xe7, 0x42, 0x55, 0x7c, 0x63, 0x1d, 0xde,
	0x87, 0xee, 0x37, 0x32, 0x36, 0x11, 0x01, 0x6e, 0x61, 0x0f, 0xcb, 0xba, 0xfb, 0xdf, 0xfb, 0x70,
	0x6b, 0x29, 0xd2, 0xf5, 0x71, 0x76, 0x90, 0x48, 0x91, 0x2a, 0xb7, 0xe2, 0x3e, 0x74, 0x23, 0x51,
	0x94, 0x35, 0x03, 0xe9, 0x49, 0x24, 0x14, 0xf3, 0x70, 0xca, 0xfc, 0x23, 0x58, 0xcc, 0x58, 0x83,
	0xdf, 0x82, 0xeb, 0x57, 0x1e, 0xfb, 0x8b, 0x19, 0xf3, 0xa9, 0x58, 0xd4, 0xc5, 0xc5, 0x8c, 0x35,
	0x71, 0x01, 0xcd, 0x0d, 0xd6, 0xa6, 0x31, 0x69, 0x29, 0xeb, 0xd0, 0x21, 0xaa, 0xf7, 0x22, 0x0b,
	0x30, 0xcb, 0xc8, 0x32, 0xeb, 0xe2, 0x56, 0xe5, 0x27, 0x99, 0x01, 0x67, 0x5a, 0xbd, 0x4a, 0x40,
	0x7a, 0x88, 0x92, 0xf9, 0x6c, 0xe0, 0x7a, 0xe4, 0xdc, 0xc1, 0x25, 0x50, 0x75, 0xb1, 0xda, 0x3e,
	0x6e, 0xe0, 0xc8, 0x2a, 0x1b, 0x20, 0x4a, 0x35, 0xb9, 0x64, 0x43, 0xeb, 0x2a, 0x1b, 0x86, 0x31,
	0xbb, 0xd5, 0x41, 0xb6, 0x11, 0xd3, 0x78, 0x75, 0xce, 0x76, 0xf9, 0x00, 0xa0, 0xea, 0x46, 0xc6,
	0xd1, 0x76, 0xa0, 0xbe, 0x8e, 0xa5, 0x54, 0x9d, 0x4a, 0xdc, 0x62, 0x37, 0xf0, 0x00, 0xf4, 0x4c,
	0xa5, 0x55, 0xff, 0x85, 0xc5, 0x10, 0x8f, 0x1e, 0xa5, 0x48, 0x25, 0x76, 0x73, 0x3f, 0x75, 0x1b,
	0x8b, 0xc0, 0x40, 0xc8, 0x0d, 0x52, 0xd7, 0x70, 0x0f, 0x72, 0x1c, 0x66, 0xaf, 0xa5, 0x28, 0xa1,
	0x37, 0xd3, 0x0d, 0x8c, 0xd7, 0x2b, 0xe9, 0x79, 0x1f, 0xe7, 0x97, 0x67, 0xd9, 0x1b, 0xda, 0x92,
	0x35, 0xf1, 0x10, 0x1a, 0x18, 0x93, 0xd1, 0x7a, 0xd5, 0xa6, 0x7f, 0x87, 0x0f, 0xfe, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xaf, 0x91, 0x59, 0x56, 0x2c, 0x0e, 0x00, 0x00,
}
